### PR TITLE
Expose magic version with DB.MagicVersion() method

### PR DESCRIPTION
**Pull request by deepakjois**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/388)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/388)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/388#-:-L1zeP2BN7wfOmxzyZrE:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[db.go, line 1085 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/388#-L2SzGHJfqoLHIk6_RkB:-L2SzGHJfqoLHIk6_RkC:b6kq84p) ([raw file](https://github.com/dgraph-io/badger/blob/258d272bb933a26d370baa6c66b6be42023f410d/db.go#L1085)):*
> ```Go
> //
> // Badger data files with a magic number that is different from the one reported
> // by this function will not work with the current instance of Badger.
> ```

Comma after "this function"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/388#-:-L2SzFqeVNW1t47eAyBZ:bnfp4nl)*

**Comment by deepakjois** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[db.go, line 1085 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/388#-L2SzGHJfqoLHIk6_RkB:-L2TaVhEEsz8bds34Bot:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/258d272bb933a26d370baa6c66b6be42023f410d/db.go#L1085)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Comma after "this function"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/388)*

**Pull request merged**
