### PR TITLE
Add GetOrTouch

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/94)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[kv.go, line 394 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoKZoz1BXSz7AsfUEk7:-KoKZoz1BXSz7AsfUEk8:bjagg) ([raw file](https://github.com/dgraph-io/badger/blob/34e33a0ad176fcd1897eb45c377f10247a1eaa4a/kv.go#L394)):*
> ```Go
> // GetOrTouch looks for key, if it finds it then it returns
> // else it puts the key in the LSM tree.
> func (s *KV) GetOrTouch(key []byte) error {
> ```

`Touch(..)`, no Get. Don't wait for s.BatchSet().

---

*[kv.go, line 395 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoK_Uxx6O36rUKNSxm4:-KoK_Uxx6O36rUKNSxm5:bedoif8) ([raw file](https://github.com/dgraph-io/badger/blob/34e33a0ad176fcd1897eb45c377f10247a1eaa4a/kv.go#L395)):*
> ```Go
> // else it puts the key in the LSM tree.
> func (s *KV) GetOrTouch(key []byte) error {
> 	vs, err := s.get(key)
> ```

s.Get(key) => item.Value() => nil, then do the touch.

---

*[kv.go, line 408 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoKcth-ax40MlY1IoFO:-KoKcth-ax40MlY1IoFP:brvlaw1) ([raw file](https://github.com/dgraph-io/badger/blob/34e33a0ad176fcd1897eb45c377f10247a1eaa4a/kv.go#L408)):*
> ```Go
> 		Meta: BitTouch,
> 	}
> 	return s.BatchSet([]*Entry{e})
> ```

Don't wait on it. You can put the goroutine here.

---

*[kv.go, line 475 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoKaUEMeqvLrv9SCuH-:-KoKaUEMeqvLrv9SCuH0:b-xsn5rx) ([raw file](https://github.com/dgraph-io/badger/blob/34e33a0ad176fcd1897eb45c377f10247a1eaa4a/kv.go#L475)):*
> ```Go
> 		}
> 
> 		if entry.Meta == BitTouch {
> ```

Make sure that we don't write to vlog.

---

*[kv.go, line 476 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoKbKJIQ7DK3XEr0m1A:-KoKbKJIQ7DK3XEr0m1B:b24m41k) ([raw file](https://github.com/dgraph-io/badger/blob/34e33a0ad176fcd1897eb45c377f10247a1eaa4a/kv.go#L476)):*
> ```Go
> 
> 		if entry.Meta == BitTouch {
> 			vs, err := s.get(entry.Key)
> ```

use Exists here. Optimize Exists by removing errors.Wrapf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/94)*

**Comment by pawanrawal** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[kv.go, line 394 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoKZoz1BXSz7AsfUEk7:-KoKe-e6vtWbqmNYZomO:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/34e33a0ad176fcd1897eb45c377f10247a1eaa4a/kv.go#L394)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`Touch(..)`, no Get. Don't wait for s.BatchSet().
</blockquote></details>

Done.

---

*[kv.go, line 395 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoK_Uxx6O36rUKNSxm4:-KoKdyrqPQY1OLOCJDOK:blrora6) ([raw file](https://github.com/dgraph-io/badger/blob/34e33a0ad176fcd1897eb45c377f10247a1eaa4a/kv.go#L395)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

s.Get(key) => item.Value() => nil, then do the touch.
</blockquote></details>

Its only touch now, so we dont have value using exists.

---

*[kv.go, line 408 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoKcth-ax40MlY1IoFO:-KoKe2ridmqfRhmrmyJS:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/34e33a0ad176fcd1897eb45c377f10247a1eaa4a/kv.go#L408)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't wait on it. You can put the goroutine here.
</blockquote></details>

Done.

---

*[kv.go, line 475 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoKaUEMeqvLrv9SCuH-:-KoKk41cdvMmV3FDbKit:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/34e33a0ad176fcd1897eb45c377f10247a1eaa4a/kv.go#L475)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make sure that we don't write to vlog.
</blockquote></details>

Done.

---

*[kv.go, line 476 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoKbKJIQ7DK3XEr0m1A:-KoKeOLX3bj-Jw-Q47iI:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/34e33a0ad176fcd1897eb45c377f10247a1eaa4a/kv.go#L476)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

use Exists here. Optimize Exists by removing errors.Wrapf
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/94)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[kv.go, line 409 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoKlec61uHMwG0jJYTE:-KoKlec61uHMwG0jJYTF:bza4zoz) ([raw file](https://github.com/dgraph-io/badger/blob/3705f837d700f208bd12b8796cfed276502499f1/kv.go#L409)):*
> ```Go
> 		Meta: BitTouch,
> 	}
> 	// Dont need to worry about key being written to disk.
> ```

Don't wait for the key being written to disk.

---

*[kv.go, line 420 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoKlurmKVxLrDTs46KB:-KoKlurmKVxLrDTs46KC:bw2gmb7) ([raw file](https://github.com/dgraph-io/badger/blob/3705f837d700f208bd12b8796cfed276502499f1/kv.go#L420)):*
> ```Go
> 	vs, err := s.get(key)
> 	if err != nil {
> 		return false, fmt.Errorf("KV::Get key: %q, err: %+v", key, err)
> ```

false, err

---

*[kv.go, line 480 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/94#-KoKly132iY6E_bebocl:-KoKly132iY6E_bebocm:b-5eqkzf) ([raw file](https://github.com/dgraph-io/badger/blob/3705f837d700f208bd12b8796cfed276502499f1/kv.go#L480)):*
> ```Go
> 		if entry.Meta == BitTouch {
> 			// Someone else might have written a value, so lets check again if
> 			// key exists.
> ```

same line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/94#-:-KoKmKGA8EdvoSj45NhJ:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
