### PR TITLE
Add a BatchSetAsync method

### LINKED ISSUE #98: Introduce Async writes in Badger
We should be able to break away the waiting of requests in BatchSet, into a separate goroutine, which can wait and then run a callback function. This can be used in Dgraph for getting rid of `syncCh`.

### PR DESCRIPTION
**Pull request by pawanrawal**
Add a BatchSetAsync method which can accept a callback function and call it when all writes are done. This should resolve #98.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/101)

### CODE REVIEW

**Comment by manishrjain** [comment]
This PR needs a lot more thought than was put into it.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kv.go, line 667 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KorfBewmZfI1FMhEEIi:-KorfBewmZfI1FMhEEIj:br0htk2) ([raw file](https://github.com/dgraph-io/badger/blob/9416984e519014305445c404cc5ca1e03801fa4b/kv.go#L667)):*
> ```Go
> }
> 
> func (s *KV) BatchSetAsync(entries []*Entry, f func()) {
> ```

f should provide the error message returned by BatchSet.

Code duplication between this and the other BatchSet. Try to do some refactoring here so the blocking version can use this.

Also, think about Godocs. You need to tell people how to use this. Also, consider how they would handle errors.

We also need the corresponding `SetAsync(..)`, and `CompareAndSetAsync` methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/101#-:-KorftCaxVdBprRqj7c9:bu89m96)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[value.go, line 591 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/101#-Korfzf9PBj6O2zbL98p:-Korfzf9PBj6O2zbL98q:b-fm2243) ([raw file](https://github.com/dgraph-io/badger/blob/9416984e519014305445c404cc5ca1e03801fa4b/value.go#L591)):*
> ```Go
> 	Wg      sync.WaitGroup
> 	Err     error
> 	Idx     int
> ```

What's this for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/101)*

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[kv.go, line 667 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KorfBewmZfI1FMhEEIi:-KotsT3G9lm6M75w6z7i:b-7wr9ya) ([raw file](https://github.com/dgraph-io/badger/blob/9416984e519014305445c404cc5ca1e03801fa4b/kv.go#L667)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

f should provide the error message returned by BatchSet.

Code duplication between this and the other BatchSet. Try to do some refactoring here so the blocking version can use this.

Also, think about Godocs. You need to tell people how to use this. Also, consider how they would handle errors.

We also need the corresponding `SetAsync(..)`, and `CompareAndSetAsync` methods.
</blockquote></details>

We send the error through f to the user.

Made the code DRY.

Added an example on Godocs for how to use BatchSetAsync.

Added `SetAsync` and `CompareAndSetAsync`. Also added `DeleteAsync`. 

Should we also add `CompareAndDeleteAsync`?

---

*[value.go, line 591 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/101#-Korfzf9PBj6O2zbL98p:-KosrBrbJa7NHcDU844g:btgmbtd) ([raw file](https://github.com/dgraph-io/badger/blob/9416984e519014305445c404cc5ca1e03801fa4b/value.go#L591)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What's this for?
</blockquote></details>

removed, not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/101)*

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[doc_test.go, line 99 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KotuesFTHAKv5JkYPG0:-KotuesGeXYF18Ba87Br:bqcjgnk) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/doc_test.go#L99)):*
> ```Go
> 	// In Dgraph we keep on flushing posting lists periodically to badger. We do it an async
> 	// manner and provide a callback to it which can do the cleanup when the writes are done.
> 	f := func(err error) {
> ```

The right way to do it is to have a waitgroup.Done here.

---

*[doc_test.go, line 119 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KotunMZYSs2Sgkt9m0U:-KotunMZYSs2Sgkt9m0V:b-5882fv) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/doc_test.go#L119)):*
> ```Go
> 	kv.BatchSetAsync(wb, f)
> 	fmt.Println("Finished writing keys to badger.")
> 	time.Sleep(time.Second)
> ```

Don't just sleep, do a wg.Wait() here. So, you'll know when it's done. It might seem counterintuitive to do so, but this is just a contrived example.

---

*[kv.go, line 667 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KorfBewmZfI1FMhEEIi:-KotvH3IEG_sUPV0adre:b-59h5r5) ([raw file](https://github.com/dgraph-io/badger/blob/9416984e519014305445c404cc5ca1e03801fa4b/kv.go#L667)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We send the error through f to the user.

Made the code DRY.

Added an example on Godocs for how to use BatchSetAsync.

Added `SetAsync` and `CompareAndSetAsync`. Also added `DeleteAsync`. 

Should we also add `CompareAndDeleteAsync`?
</blockquote></details>

Yea, CompareAndDeleteAsync would make sense (given DeleteAsync).

---

*[kv.go, line 688 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KotvXHlzmn1Jf81rUc9:-KotvXHlzmn1Jf81rUcA:b-6wizad) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/kv.go#L688)):*
> ```Go
> 		}
> 
> 		for _, e := range entries {
> ```

No need to check these. These should be checked by the user. Add that in the example.

---

*[kv.go, line 709 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KotvqjyWMCnPDwguO2f:-KotvqjyWMCnPDwguO2g:b-obq76s) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/kv.go#L709)):*
> ```Go
> }
> 
> // SetAsync sets the provided value for a given key in an async manner. It accepts a callback
> ```

Start with "SetAsync is the asynchronous version of Set. It accepts a ..."

---

*[kv.go, line 712 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-Kotvnuec5mCfwOi4iBK:-Kotvnuec5mCfwOi4iBL:b4i91rg) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/kv.go#L712)):*
> ```Go
> // function which is called when the set is complete. Any errors encountered during execution
> // are passed as an argument to the callback function.
> // If key is not present, it is created. If it is present, the existing value is overwritten
> ```

No need for the repeated "If Key is not present .."

---

*[kv.go, line 746 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KotwAYuCO9keRGG2_op:-KotwAYuCO9keRGG2_oq:b-3o45ch) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/kv.go#L746)):*
> ```Go
> }
> 
> // CompareAndSetAsync sets the given value, ensuring that the no other Set operation has happened,
> ```

"CompareAndSetAsync is the async version of ... It accepts a ..." Then no need to repeat about the actual functionality, because that's already explained in the original CompareAndSet.

---

*[kv.go, line 757 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-Kotwa_5hwIPA8BoPqcq:-Kotwa_5hwIPA8BoPqcr:be6pgkk) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/kv.go#L757)):*
> ```Go
> 	}
> 
> 	b := requestPool.Get().(*request)
> ```

No BatchSetAsync for this?

---

*[value.go, line 774 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-Kotwxj22dSd7AFdmcX9:-Kotwxj22dSd7AFdmcXA:bqzasn) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/value.go#L774)):*
> ```Go
> }
> 
> func (vlog *valueLog) doRunGC() error {
> ```

Revert this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/101)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

*[doc_test.go, line 99 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KotuesFTHAKv5JkYPG0:-Kou8tZDElFKo8QYGWrF:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/doc_test.go#L99)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

The right way to do it is to have a waitgroup.Done here.
</blockquote></details>

Done.

---

*[doc_test.go, line 119 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KotunMZYSs2Sgkt9m0U:-Kou8uQCYF_FQSEDOSJf:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/doc_test.go#L119)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't just sleep, do a wg.Wait() here. So, you'll know when it's done. It might seem counterintuitive to do so, but this is just a contrived example.
</blockquote></details>

Done.

---

*[kv.go, line 667 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KorfBewmZfI1FMhEEIi:-KouCxcnd64V5Vpue6Zq:b-8b11j9) ([raw file](https://github.com/dgraph-io/badger/blob/9416984e519014305445c404cc5ca1e03801fa4b/kv.go#L667)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Yea, CompareAndDeleteAsync would make sense (given DeleteAsync).
</blockquote></details>

Added

---

*[kv.go, line 688 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KotvXHlzmn1Jf81rUc9:-Kou98h32EAZugy8JjDg:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/kv.go#L688)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to check these. These should be checked by the user. Add that in the example.
</blockquote></details>

Done.

---

*[kv.go, line 709 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KotvqjyWMCnPDwguO2f:-Kou9WT7fxOXNJhPm208:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/kv.go#L709)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Start with "SetAsync is the asynchronous version of Set. It accepts a ..."
</blockquote></details>

Done.

---

*[kv.go, line 712 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-Kotvnuec5mCfwOi4iBK:-Kou9WAz3moasHw-dvMg:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/kv.go#L712)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for the repeated "If Key is not present .."
</blockquote></details>

Done.

---

*[kv.go, line 746 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KotwAYuCO9keRGG2_op:-Kou9uMCJZeBvthfV38c:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/kv.go#L746)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

"CompareAndSetAsync is the async version of ... It accepts a ..." Then no need to repeat about the actual functionality, because that's already explained in the original CompareAndSet.
</blockquote></details>

Done.

---

*[kv.go, line 757 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-Kotwa_5hwIPA8BoPqcq:-KouARFoAtsrRMxyPWi7:bdeiutq) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/kv.go#L757)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No BatchSetAsync for this?
</blockquote></details>

We need to check error on Entry and pass it to user in `f` if any. That's what we do for CompareAndSet too.  We don't check for Entry errors in `BatchSetAsync`.

---

*[value.go, line 774 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/101#-Kotwxj22dSd7AFdmcX9:-KouFLLT4jOv966cNeNG:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/2c955b7088e59bfbb1f9214add4a6b1aeba5bdb7/value.go#L774)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Revert this file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/101)*

**Comment by manishrjain** [comment]
:lgtm: Address comments, then submit.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[doc_test.go, line 103 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KoyvG6nuZJXh_HSqGod:-KoyvG6nuZJXh_HSqGoe:b-eprnkr) ([raw file](https://github.com/dgraph-io/badger/blob/d2dd1093a9196a43615fd035393f157987f2f00b/doc_test.go#L103)):*
> ```Go
> 	// manner and provide a callback to it which can do the cleanup when the writes are done.
> 	f := func(err error) {
> 		wg.Done()
> ```

defer wg.Done(). Otherwise, your fmt.Printfs won't have time to print before main returns.

You actually overwrite the err which was passed. Check that first.

---

*[doc_test.go, line 108 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KoyvgwKYHRDAMokNwk7:-KoyvgwKYHRDAMokNwk8:bsshod5) ([raw file](https://github.com/dgraph-io/badger/blob/d2dd1093a9196a43615fd035393f157987f2f00b/doc_test.go#L108)):*
> ```Go
> 		for _, e := range wb {
> 			if e.Error != nil {
> 				err = e.Error
> ```

Just say fmt.Printf("Got error...")

---

*[doc_test.go, line 118 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/101#-Koyvk4lII_Wy7np6Yvg:-Koyvk4mrGD3-rH-WB7f:b-njufre) ([raw file](https://github.com/dgraph-io/badger/blob/d2dd1093a9196a43615fd035393f157987f2f00b/doc_test.go#L118)):*
> ```Go
> 
> 		// No error. You can do cleanup now. Like deleting keys from cache.
> 		fmt.Println("All async sets complete. Got no error.")
> ```

fmt.Println("All async sets complete.") // No need to mention errors. They were handled above.

---

*[kv.go, line 811 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KoywyR6qlPFZKdnb4g2:-KoywyR7Zzlz1CtuTjPm:b-1ex4r) ([raw file](https://github.com/dgraph-io/badger/blob/d2dd1093a9196a43615fd035393f157987f2f00b/kv.go#L811)):*
> ```Go
> 
> // CompareAndDeleteAsync is the asynchronous version of CompareAndDelete. It accepts a callback
> // function which is called when the CompareAndDelete completes. Any error encountered during execution
> ```

100 chars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/101#-:-KoyxFMFlSwN3nzaDrBH:b-z2s0p6)*

**Comment by manishrjain** [comment]
Once you do, have a look at the produced godocs and just ensure they're of good quality. If not, good idea to make improvements in small PRs.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/101#-:-KoyxIH7n-MOKxqU2EbH:bc5mae6)*

**Comment by pawanrawal** [comment]
Merged. Docs look good I think. Could come up with a better example for demonstrating the use of Async function. Will think more about it.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[doc_test.go, line 103 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KoyvG6nuZJXh_HSqGod:-KozPoE_AyBk7ikADgvL:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/d2dd1093a9196a43615fd035393f157987f2f00b/doc_test.go#L103)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

defer wg.Done(). Otherwise, your fmt.Printfs won't have time to print before main returns.

You actually overwrite the err which was passed. Check that first.
</blockquote></details>

Done.

---

*[doc_test.go, line 108 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KoyvgwKYHRDAMokNwk7:-KozPog_2agyjDUFUVX0:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/d2dd1093a9196a43615fd035393f157987f2f00b/doc_test.go#L108)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just say fmt.Printf("Got error...")
</blockquote></details>

Done.

---

*[doc_test.go, line 118 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/101#-Koyvk4lII_Wy7np6Yvg:-KozQcRWEgeJPNPbxNw7:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/d2dd1093a9196a43615fd035393f157987f2f00b/doc_test.go#L118)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

fmt.Println("All async sets complete.") // No need to mention errors. They were handled above.
</blockquote></details>

Done.

---

*[kv.go, line 811 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/101#-KoywyR6qlPFZKdnb4g2:-KozQ-iIArqvqimMY4do:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/d2dd1093a9196a43615fd035393f157987f2f00b/kv.go#L811)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/101#-:-KozRrD6sBcwOGN5vnWt:bkxl02m)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
