### PR TITLE
Add an option to open Badger with a managed option, where all txn API…

### PR DESCRIPTION
**Pull request by manishrjain**
…s would act accordingly.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/280)

### CODE REVIEW

**Comment by deepakjois** [comment]
Can this be tested in some way?

This also seems to have broken the build.  Some tests seem to be failing.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/280#-:-Kwj9vK3QX9kvV5sHpLu:bp12iti)*

**Comment by manishrjain** [comment]
Please have another look.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/280#-:-Kx6T7ORTtwb-1CHouou:b-z4iq0l)*

**Comment by deepakjois** [comment]
The change itself looks good to me, except the one question I posted.

But I still don’t understand the motivation for this change. Also, if this is applicable more broadly, we should add something to the README. Maybe add it now, or create an issue for it so we don’t forget?

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[transaction.go, line 84 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/280#-Kx6WLU3HXlr3Z3r7F2_:-Kx6WLU3HXlr3Z3r7F2a:b-7uakag) ([raw file](https://github.com/dgraph-io/badger/blob/71cc076ec67944cb22a48ade9a7b30474838c1fa/transaction.go#L84)):*
> ```Go
> func (o *oracle) readTs() uint64 {
> 	if o.isManaged {
> 		return math.MaxUint64
> ```

So managed transactions get commited into the db with a version `math.MaxUint64`?

Does that mean once we use a db with managed transactions, we cannot use it with regular transaction?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/280#-:-Kx6Wftc77mxLgryqAUU:b1keep)*

**Comment by deepakjois** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/280#-:-Kx6X1AG4qSLUE7UbSgl:bnfp4nl)*

**Comment by manishrjain** [comment]
We need to control the read and commit timestamps in Dgraph. Therefore, we need this change. Yeah, we could mention that if there's a desire to use NewTransactionAt and CommitAt, then the DB should be opened with this flag.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[transaction.go, line 84 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/280#-Kx6WLU3HXlr3Z3r7F2_:-Kx6eZSMAx3meinL6Q3h:b-ra7t2y) ([raw file](https://github.com/dgraph-io/badger/blob/71cc076ec67944cb22a48ade9a7b30474838c1fa/transaction.go#L84)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

So managed transactions get commited into the db with a version `math.MaxUint64`?

Does that mean once we use a db with managed transactions, we cannot use it with regular transaction?
</blockquote></details>

No, that's the read timestamp, not the commit timestamp. Also, if the caller uses NewTransactionAt, they would use the provided read timestamp, and not the default maxuint64.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/280#-:-Kx6f7RcRAbN6S6x8GHI:b-2sldv0)*

**Comment by deepakjois** [comment]
I don’t see a corresponding change for `NewTransactionAt`, to error if the flag isn‘t set.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[transaction.go, line 381 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/280#-Kx6xhwn6LE6lz94Jqxt:-Kx6xhwn6LE6lz94Jqxu:bhqqvff) ([raw file](https://github.com/dgraph-io/badger/blob/71cc076ec67944cb22a48ade9a7b30474838c1fa/transaction.go#L381)):*
> ```Go
> // can be ignored by most users.
> func (txn *Txn) CommitAt(commitTs uint64, callback func(error)) error {
> 	if !txn.db.opt.ManagedTxns {
> ```

Shouldn’t we make a similar change in TransactionAt, based on your comments?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/280#-:-Kx6xK7Tc8lX0koyPwC_:b-q5g6bs)*

**Comment by manishrjain** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[transaction.go, line 381 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/280#-Kx6xhwn6LE6lz94Jqxt:-Kx73JgEpH456ixVnVW2:b-j9nhxt) ([raw file](https://github.com/dgraph-io/badger/blob/71cc076ec67944cb22a48ade9a7b30474838c1fa/transaction.go#L381)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

Shouldn’t we make a similar change in TransactionAt, based on your comments?
</blockquote></details>

NewTransactionAt and NewTransaction don't return errors. This didn't seem like a good enough reason to start returning errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/280)*

**Comment by deepakjois** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[transaction.go, line 381 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/280#-Kx6xhwn6LE6lz94Jqxt:-Kx74LmkORW8CUo-4zXX:b-vc5ecf) ([raw file](https://github.com/dgraph-io/badger/blob/71cc076ec67944cb22a48ade9a7b30474838c1fa/transaction.go#L381)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

NewTransactionAt and NewTransaction don't return errors. This didn't seem like a good enough reason to start returning errors.
</blockquote></details>

So it is possible to do a "managed" transaction with NewTransactionAt without setting the ManagedTxns option? That doesnt sound very consistent, esp if CommitAt is performing that check

NewTransactionAt could return an error, which we could document clearly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/280)*

**Comment by deepakjois** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[transaction.go, line 378 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/280#-Kx75ZTkmVnznaOaiEeZ:-Kx75ZTkmVnznaOaiEe_:b-uz6zsg) ([raw file](https://github.com/dgraph-io/badger/blob/71cc076ec67944cb22a48ade9a7b30474838c1fa/transaction.go#L378)):*
> ```Go
> 
> // CommitAt commits the transaction, following the same logic as Commit(), but at the given
> // commit timestamp. This API is only useful for databases built on top of Badger (like Dgraph), and
> ```

Also update docs here to indicate that ManagedTxns need to be set to call this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/280)*

**Comment by deepakjois** [comment]
Closing this pull request, since the code was committed separately. Also see followup PR #283

**Pull request closed without merging**
