### PR TITLE
Fix race in decRef

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/328)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[transaction.go, line 395 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/328#-KzgUEsAe0KCygQlJCCB:-KzgUEsBNJmCV3rAfYe-:bbnhevw) ([raw file](https://github.com/dgraph-io/badger/blob/136388a78a01afb9253d5e4567ae66c8b6ee4756/transaction.go#L395)):*
> ```Go
> 		return ErrConflict
> 	}
> 	defer state.doneCommit(commitTs)
> ```

If user specifies callback we will advance the readTs before the data is written to memtable. 
We call batchsetasync and then doneCommit would be called.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/328)*

**Comment by janardhan1993** [comment]
Fixes #327 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/328#-:-KzgV7N0ovZR2Sx1-Eno:b-i21cwd)*

**Comment by manishrjain** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transaction.go, line 395 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/328#-KzgUEsAe0KCygQlJCCB:-KzgxPGD6xWsEA0f0zw1:bxbqmxb) ([raw file](https://github.com/dgraph-io/badger/blob/136388a78a01afb9253d5e4567ae66c8b6ee4756/transaction.go#L395)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

If user specifies callback we will advance the readTs before the data is written to memtable. 
We call batchsetasync and then doneCommit would be called.
</blockquote></details>

Hmm... good point. Maybe this should be called only once the data is written, otherwise there maybe a race cond between data getting written and it getting read. Though, would be ideal if we could create a test case to ensure that's a bug before fixing, not sure how hard that might be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/328#-:-Kzgyw_4jBIuyFQ7J_gm:bg7igkv)*

**Comment by janardhan1993** [comment]
I added bank test, and the total balance invariant was failing if we call donecommit before the callback. The test passes after the fix.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[transaction.go, line 395 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/328#-KzgUEsAe0KCygQlJCCB:-Kzuh_l_wmLIv-h3vVSj:b-833rdr) ([raw file](https://github.com/dgraph-io/badger/blob/136388a78a01afb9253d5e4567ae66c8b6ee4756/transaction.go#L395)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Hmm... good point. Maybe this should be called only once the data is written, otherwise there maybe a race cond between data getting written and it getting read. Though, would be ideal if we could create a test case to ensure that's a bug before fixing, not sure how hard that might be.
</blockquote></details>

I was able to reproduce with bank test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/328#-:-KzuhOxe6IyTig5l7dra:b-fkh9rs)*

**Comment by manishrjain** [comment]
:lgtm: Also add this in the changelog.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[transaction_test.go, line 117 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/328#-KzzmbrHWBY3VSJ-KHFS:-KzzmbrHWBY3VSJ-KHFT:bx7lav6) ([raw file](https://github.com/dgraph-io/badger/blob/33ad2743090d87cb7e0a14467675fcc1b83a1401/transaction_test.go#L117)):*
> ```Go
> 			}
> 			require.NoError(t, txn.Commit(func(err error) {
> 			}))
> ```

Put this in the same line.

Also add a comment about why no conflict.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/328#-:-KzzmuBkhet4JLbsrRv1:b-ipk49h)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[transaction.go, line 80 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/328#-Kzzn42Xm6vUcto9icJ1:-Kzzn42Xm6vUcto9icJ2:b-4wv9d) ([raw file](https://github.com/dgraph-io/badger/blob/33ad2743090d87cb7e0a14467675fcc1b83a1401/transaction.go#L80)):*
> ```Go
> 			return
> 		}
> 		y.AssertTrue(len(o.commitMark) == 0)
> ```

No need for this line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/328)*

**Comment by janardhan1993** [comment]
Merged to master

**Pull request closed without merging**
