### PR TITLE
Update the max value pointer correctly.

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/133)

### CODE REVIEW

**Comment by srh** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[kv.go, line 514 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/133#-Kq1lyVYi6HD4EOEBpae:-Kq1lyVYi6HD4EOEBpaf:by9x2py) ([raw file](https://github.com/dgraph-io/badger/blob/94e1dcb1bc81e1b14033ccd445a09651d970e894/kv.go#L514)):*
> ```Go
> func (s *KV) updateOffset(ptrs []valuePointer) {
> 	var ptr valuePointer
> 	for _, p := range ptrs {
> ```

What we could do here is iterate backwards and stop when we get the last non-zero ptr, instead of iterating through all of them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/133)*

**Comment by srh** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/133)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[kv.go, line 514 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/133#-Kq1lyVYi6HD4EOEBpae:-Kq2-rXGA6UncbK0SWNo:b35wj2g) ([raw file](https://github.com/dgraph-io/badger/blob/94e1dcb1bc81e1b14033ccd445a09651d970e894/kv.go#L514)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

What we could do here is iterate backwards and stop when we get the last non-zero ptr, instead of iterating through all of them.
</blockquote></details>

Done. Good point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/133)*

**Comment by srh** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[value.go, line 440 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/133#-Kq4y1_WYmIs71FW4RM8:-Kq4y1_WYmIs71FW4RM9:b-iu9etd) ([raw file](https://github.com/dgraph-io/badger/blob/204fc119c8a4313b9aa6804ddf77f4ec24c070cb/value.go#L440)):*
> ```Go
> }
> 
> func (p valuePointer) IsZero() bool {
> ```

You could do `return p.Fid == 0 && p.Offset == 0 && p.Len == 0`.  Anyway you can do that or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/133#-:-Kq4yADJNrLk8Ob7xtkw:bnfp4nl)*

**Comment by srh** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/133)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 440 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/133#-Kq4y1_WYmIs71FW4RM8:-Kq5nMKV3HEUGJL9eoIH:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/204fc119c8a4313b9aa6804ddf77f4ec24c070cb/value.go#L440)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

You could do `return p.Fid == 0 && p.Offset == 0 && p.Len == 0`.  Anyway you can do that or not.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/133)*

**Pull request closed without merging**
