### PR TITLE
Account for value size when restoring key/values from a backup.

### PR DESCRIPTION
**Pull request by gonzojive**
The previous behavior only accounted for key size. For databases where keys are
small (e.g., URLs) and values are much larger (megabytes), OOM errors were easy
to trigger during restore operations.

This change does not set the threshold used for flushing elegantly - a const is
used instead of a configurable option.

Related to https://github.com/dgraph-io/badger/issues/1268, but not a full fix.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1278)

### CODE REVIEW

**Comment by jarifibrahim** [comment]
Thank you for the PR @gonzojive. Please let me know once it is ready for review.

**Comment by gonzojive** [comment]
I have a request in with my company for signing the CLA, but if it possible to skip signing the CLA, then we can proceed right away.

**Comment by jarifibrahim** [comment]
@gonzojive Unfortunately, due to repository settings, I cannot merge any PRs without the CLA signed.

**Comment by jarifibrahim** [comment]
@gonzojive ping! Are you still working on this PR? I can take it from here if you aren't working on it :)

**Comment by gonzojive** [comment]
I am not, please feel free to take over.

**Comment by jarifibrahim** [comment]
Closing this PR in favor of https://github.com/dgraph-io/badger/pull/1358 . Thank you for the PR @gonzojive

**Pull request closed without merging**
