### PR TITLE
Propagating disk errors

### PR DESCRIPTION
**Pull request by szymonm**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/44)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[badger/kv.go, line 153 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-KkijkabkqFYeDwCIacO:-KkijkabkqFYeDwCIacP:bjeu5xn) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/badger/kv.go#L153)):*
> ```Go
> 	go out.flushMemtable(lc) // Need levels controller to be up.
> 
> 	err = out.vlog.Open(out, opt)
> ```

Move these to 1 line. `if err = out.vlog... { retuirn nil, err}`

---

*[badger/kv.go, line 554 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-KkilPxjAWJL34CExPOV:-KkilPxjAWJL34CExPOW:b9h3f9d) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/badger/kv.go#L554)):*
> ```Go
> 
> // hasRoomForWrite is always called serially.
> func (s *KV) hasRoomForWrite() (bool, error) {
> ```

You can refactor it, so it returns an `ErrNoRoom`. That way, you only need one return variable, not two.

---

*[badger/value.go, line 98 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-Kkilahc_y9T5jtYpfx9:-Kkilahc_y9T5jtYpfxA:b-trogf7) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/badger/value.go#L98)):*
> ```Go
> }
> 
> type logEntry func(e Entry, vp valuePointer) (bool, error)
> ```

Same as above here. You can return `errStop`, so it can iterate can return cleanly. For continue, just return nil. Any other error would also stop, but return the error back.

---

*[badger/value.go, line 830 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-Kkilv16WmWeT0uuBM_e:-Kkilv17XbgYnhNv3U4V:b-s7covz) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/badger/value.go#L830)):*
> ```Go
> 			// Value is present in a later offset, but in the same log.
> 			r.discard += esz
> 			return true, nil
> ```

Returning 2 values isn't required. They are complementing each other. If true, then nil. If false, then err.

---

*[table/table.go, line 89 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-Kkikv2CLjxs7OgJLLQo:-Kkikv2CLjxs7OgJLLQp:bfabckh) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/table/table.go#L89)):*
> ```Go
> 		filename := s.fd.Name()
> 		err = s.fd.Close()
> 		if err != nil {
> ```

All of these can be done in one line. GoMetaLinter should be able to tell you that.

---

*[table/table.go, line 180 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-KkikdmPLg4G8E_UqQ6E:-KkikdmPLg4G8E_UqQ6F:b3tcjbf) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/table/table.go#L180)):*
> ```Go
> 	written, err := t.fd.WriteAt(meta, int64(pos))
> 	y.AssertTrue(written == len(meta))
> 	if err != nil {
> ```

This error handling here defies the AssertTrue above! Also, wrap it.

---

*[table/table.go, line 346 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-KkikUe3KG55VcWEth-y:-KkikUe4aGlITWwB7wRm:blszx70) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/table/table.go#L346)):*
> ```Go
> 	read, err := t.fd.ReadAt(t.mmap, 0)
> 	if err != nil || read != t.tableSize {
> 		return y.Wrapf(err, "Unable to load file in memory. Read: %v", read)
> ```

Put file name in the error. `read` isn't valid anyway, because of error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/44)*

**Comment by szymonm** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[badger/kv.go, line 153 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-KkijkabkqFYeDwCIacO:-KkjWRjde6d_5UvmgqXl:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/badger/kv.go#L153)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move these to 1 line. `if err = out.vlog... { retuirn nil, err}`
</blockquote></details>

Done.

---

*[badger/kv.go, line 554 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-KkilPxjAWJL34CExPOV:-KkjYCr4JEPR_QDgo3eZ:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/badger/kv.go#L554)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You can refactor it, so it returns an `ErrNoRoom`. That way, you only need one return variable, not two.
</blockquote></details>

Done.

---

*[badger/value.go, line 98 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-Kkilahc_y9T5jtYpfx9:-KkjaQhyWpNKncNQ46sT:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/badger/value.go#L98)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Same as above here. You can return `errStop`, so it can iterate can return cleanly. For continue, just return nil. Any other error would also stop, but return the error back.
</blockquote></details>

Done.

---

*[badger/value.go, line 830 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-Kkilv16WmWeT0uuBM_e:-KkjajdkQoNcwh1rvLDE:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/badger/value.go#L830)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Returning 2 values isn't required. They are complementing each other. If true, then nil. If false, then err.
</blockquote></details>

Done.

---

*[table/table.go, line 89 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-Kkikv2CLjxs7OgJLLQo:-KkjcnCXnEOo2AkgJUIv:b-ttfhlt) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/table/table.go#L89)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

All of these can be done in one line. GoMetaLinter should be able to tell you that.
</blockquote></details>

Will change. 

Do we have a policy for gometalinter issues? We have actually lots of them, because of inconsistent naming and lack of comments.

---

*[table/table.go, line 180 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-KkikdmPLg4G8E_UqQ6E:-KkjeB1A3Wot1aklgM8e:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/table/table.go#L180)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This error handling here defies the AssertTrue above! Also, wrap it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/44)*

**Comment by szymonm** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[table/table.go, line 346 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-KkikUe3KG55VcWEth-y:-KkjjRf5YsNMs7njoI45:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/table/table.go#L346)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Put file name in the error. `read` isn't valid anyway, because of error.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/44)*

**Comment by manishrjain** [comment]
:lgtm: One small comment.

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[table/table.go, line 89 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/44#-Kkikv2CLjxs7OgJLLQo:-KlGxAsqdijSayg_G8H7:b-titeqv) ([raw file](https://github.com/dgraph-io/badger/blob/afc8560c40d88a9c26cd7a32faacf09b76719b61/table/table.go#L89)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

Will change. 

Do we have a policy for gometalinter issues? We have actually lots of them, because of inconsistent naming and lack of comments.
</blockquote></details>

We don't have any policy as such for now.

---

*[table/table.go, line 328 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/44#-KlGxOwOVAFNC2dOBvwx:-KlGxOwOVAFNC2dOBvwy:b-a9v11c) ([raw file](https://github.com/dgraph-io/badger/blob/2b457c8894e61b3e4945eeba67e62375a284667c/table/table.go#L328)):*
> ```Go
> 	var id int
> 	var err error
> 	if id, err = strconv.Atoi(name); err != nil {
> ```

In this situation, where you need to explicitly define the variables, its better to keep the assign statement and if statement separate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/44#-:-KlGxcFa6OJuaIdtjHL5:bgeo7sh)*

**Comment by szymonm** [comment]
Merged.

**Pull request closed without merging**
