### PR TITLE
Ensure `bitValuePointer` flag is cleared for LSM entry values written to LSM

### PR DESCRIPTION
**Pull request by ou05020**
When restoring a backup that was written with a lower `ValueThreshold` to a DB instance with a higher `ValueThreshold`, some entry values originally written to the value log in the backup DB will be written to the LSM along with the key when restored to the new DB.

The `meta` field for those entries is not updated to reflect the correct value storage state. Those entries still have the `bitValuePointer` flag set.

That causes `iterator.prefetch` to fail while looking up the value for those entries.

This fix ensures the `meta` `bitValuePointer` is cleared when entry values are stored in the LSM.

The original error can be reproduced by running the included `TestLSMVPClear` test after reverting the line 687 `db.go` change to clear the `bitValuePointer` flag.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1313)

### CODE REVIEW

**Comment by cedricfung** [comment]
Will this fix #1139, without RunValueLogGC our data are increasing so fast.

**Comment by jarifibrahim** [comment]
@cedricfung, the issue with #1139 was that you had some entries with invalid `bitPointerValue` set. This PR fixes the bits on invalid entries.

Did you take a backup and restore it with different `ValueThreshold` value?

**Comment by jarifibrahim** [comment]
Thank you for fixing this @ou05020 :tada:

**Comment by cedricfung** [comment]
@jarifibrahim sorry I don't understand this, what could I do to fix this?

**Comment by jarifibrahim** [comment]
@cedricfung Take a backup of your badger directory and restore it. (Keep the original one around). Do you run badger with default options?

**Pull request merged**
