### PR TITLE
Evaluate using mmap for value logs.

### PR DESCRIPTION
**Pull request by deepakjois**
This addresses #167.

Currently WIP. It is far from done. (see comments for more info)

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/182)

### CODE REVIEW

**Comment by deepakjois** [comment]
Just a few things to note:

* Currently, only read methods have been converted to use mmap()
* I have added FIXME notes in places where I am not sure what the right thing to do is.
* The `iterate` method is going to be the most tricky one, because it wraps a reader around the file handle, and may be a bit tricky to work around when using mmap.
* Tests are TBD

**Comment by manishrjain** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[value.go, line 54 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg3BzVRm8cxRLzCIH8:-Ksg3BzVRm8cxRLzCIH9:b-q0yyln) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L54)):*
> ```Go
> const (
> 	Nothing   = iota
> 	MemoryMap // use mmap to read value log
> ```

This can be shared by table.go. So, maybe move this to kv.go.

---

*[value.go, line 96 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg3bUu_ulNMj4fGSwt:-Ksg3bUu_ulNMj4fGSwu:ba3dfmt) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L96)):*
> ```Go
> 			return y.Wrapf(err, "Unable to map file")
> 		}
> 		// FIXME should I close the lf.fd file handle if mmap is true
> ```

Remove.

---

*[value.go, line 112 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg4RAjubR6HLxBMu-A:-Ksg4RAjubR6HLxBMu-B:big87uy) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L112)):*
> ```Go
> 	if len(lf.mmap) > 0 {
> 		size := int64(len(lf.mmap))
> 		if offset >= size {
> ```

No need for this. Below can tackle.

---

*[value.go, line 120 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg4RsmU3-5xxbJ85Zc:-Ksg4RsmU3-5xxbJ85Zd:b-kpgegi) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L120)):*
> ```Go
> 		// FIXME what if there is less data available than len(buf)?
> 		if bufsz < avail {
> 			nbr = int(bufsz)
> ```

No need for this either.

---

*[value.go, line 124 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg4_CAIoaEE6tUAu-K:-Ksg4_CAIoaEE6tUAu-L:b6rjq9v) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L124)):*
> ```Go
> 			nbr = int(avail)
> 		}
> 		copy(buf[0:nbr], lf.mmap[offset:offset+int64(nbr)])
> ```

```
nbr, sz := copy(buf, lf.mmap[offset:])
if sz < len(buf) { return error }
```

---

*[value.go, line 143 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg5cGlDK5qQ0q7A7HE:-Ksg5cGlDK5qQ0q7A7HF:b-iztduu) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L143)):*
> ```Go
> 	}
> 
> 	return lf.openReadOnly(len(lf.mmap) != 0) // FIXME this looks flaky
> ```

lf.mmap != nil can be used as well. Not flaky unless you're initiating lf.mmap always.

---

*[y/mmap_unix.go, line 30 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg59eSFwaQKWwiNSC3:-Ksg59eSFwaQKWwiNSC4:b-jbytvs) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/y/mmap_unix.go#L30)):*
> ```Go
> 	mtype := unix.PROT_READ
> 	if write {
> 		mtype |= unix.PROT_WRITE
> ```

Have a look at https://github.com/boltdb/bolt/blob/e9cf4fae01b5a8ff89d0ec6b32f0d9c9f79aefdd/bolt_unix.go#L50 as well for mmap options.

---

*[y/mmap_unix.go, line 33 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg5Ej_u67R-WnTezBl:-Ksg5Ej_u67R-WnTezBm:bqrwuxq) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/y/mmap_unix.go#L33)):*
> ```Go
> 	}
> 	return unix.Mmap(int(fd.Fd()), 0, int(size), mtype, unix.MAP_SHARED)
> }
> ```

Maybe another function for madvise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/182)*

**Comment by deepakjois** [comment]
@manishrjain Please take a look again. I believe I have addressed your comments.

The plan is to benchmark before moving forward with this. So I do not plan to commit it to master just yet.

Things to note:
* I ran the test suite by hardcoding the option to mmap value log. It is a FIXME in the code right now. One option is to add a flag.
* The transition from a writable log to a read-only log in `logFile.doneWriting` method is a bit tricky. The mmap does not exist while writing, so we cannot check for that. I chose to just pass on the flags from the `valueLog` struct into the function itself to control whether we mmap the files when we reopen them as read-only.
* Haven’t refactored the file mapping options in table, because moving it to the parent package creates a circular dependency. Alternatively, moving it to package `y` is a bit awkward for the caller, they will have to import an additional API. Another possible solution is to bring the table package back into root.

**Comment by deepakjois** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[value.go, line 54 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg3BzVRm8cxRLzCIH8:-KshFWW1nQTz-jdNt8E0:b-3t9j2a) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L54)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This can be shared by table.go. So, maybe move this to kv.go.
</blockquote></details>

Moving it to parent creates a circular dependency. We could organize the options in a separate package instead. Will add a FIXME

---

*[value.go, line 96 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg3bUu_ulNMj4fGSwt:-KshGB4811R1ThwSziIn:b-eq4c2l) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L96)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Reorganised the whole code

---

*[value.go, line 112 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg4RAjubR6HLxBMu-A:-KshGEUF51k0Iw7rw1H5:b-kk520s) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L112)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this. Below can tackle.
</blockquote></details>

True. See comment above.

---

*[value.go, line 120 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg4RsmU3-5xxbJ85Zc:-KshGHXfX820oMdPOz58:b-dn4o5w) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L120)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this either.
</blockquote></details>

True See comment above.

---

*[value.go, line 143 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg5cGlDK5qQ0q7A7HE:-KshGOQCjfuz82mjqndB:buwxczm) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L143)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

lf.mmap != nil can be used as well. Not flaky unless you're initiating lf.mmap always.
</blockquote></details>

So here, there is a transition from a writable log file to read-only. lf.mmap is always nil. So I decided to check the option for mmap in valueLog struct and pass it through.

---

*[y/mmap_unix.go, line 30 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg59eSFwaQKWwiNSC3:-KshGdMMcidD1snsgJeG:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/y/mmap_unix.go#L30)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Have a look at https://github.com/boltdb/bolt/blob/e9cf4fae01b5a8ff89d0ec6b32f0d9c9f79aefdd/bolt_unix.go#L50 as well for mmap options.
</blockquote></details>

Done.

---

*[y/mmap_unix.go, line 33 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg5Ej_u67R-WnTezBl:-KshGf3n0rrkhKCUoACw:bb6un1j) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/y/mmap_unix.go#L33)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Maybe another function for madvise.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/182)*

**Comment by deepakjois** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[value.go, line 124 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg4_CAIoaEE6tUAu-K:-KshGjbjhKEciWO-8QhG:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L124)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

```
nbr, sz := copy(buf, lf.mmap[offset:])
if sz < len(buf) { return error }
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/182)*

**Comment by peterstace** [comment]
Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[kv.go, line 44 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KskN23-PAAugTS7ZgIC:-KskN23-PAAugTS7ZgID:b-7drvvt) ([raw file](https://github.com/dgraph-io/badger/blob/5c85ae2fe8d32105e035fdcd6ebc0338be72116b/kv.go#L44)):*
> ```Go
> const (
> 	// read the files normally
> 	Nothing = iota
> ```

Suggest to name `StandardIO` instead of `Nothing`. Also might be good to give these their own type e.g. `type LSMMemoryMode int` so it's clearer to users what their options are when they're setting up their `Options`.

---

*[table/table.go, line 40 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KskNzs74_u8zjNqIHPe:-KskNzs74_u8zjNqIHPf:bayn8bf) ([raw file](https://github.com/dgraph-io/badger/blob/5c85ae2fe8d32105e035fdcd6ebc0338be72116b/table/table.go#L40)):*
> ```Go
> 
> // Setting to control how LSM tables are read.
> const (
> ```

Same enum as in `kv.go`. Possible to deduplicate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/182)*

**Comment by deepakjois** [comment]
It probably wasn’t clear earlier, but this code compiles, and passes the full test suite with the value log mmap-ing turned on. So the code works as far as I can see.

I do intend to address all comments before committing this. But I am thinking it would be good idea to do some benchmarking to validate the performance of this, before I go about beating this code into shape.

Thoughts, @manishrjain?

**Comment by deepakjois** [comment]
Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[kv.go, line 44 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KskN23-PAAugTS7ZgIC:-Ksl0-qM1Q3trtkKsznY:bhy9ot6) ([raw file](https://github.com/dgraph-io/badger/blob/5c85ae2fe8d32105e035fdcd6ebc0338be72116b/kv.go#L44)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Suggest to name `StandardIO` instead of `Nothing`. Also might be good to give these their own type e.g. `type LSMMemoryMode int` so it's clearer to users what their options are when they're setting up their `Options`.
</blockquote></details>

Will do.

---

*[table/table.go, line 40 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KskNzs74_u8zjNqIHPe:-Ksl0M2_NUsXdYBSZUFn:bbo7dg1) ([raw file](https://github.com/dgraph-io/badger/blob/5c85ae2fe8d32105e035fdcd6ebc0338be72116b/table/table.go#L40)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Same enum as in `kv.go`. Possible to deduplicate?
</blockquote></details>

Yes, we will need to duplicate. We could move all options to a separate `options` package, and import it in `badger` as well as `table` packages. That is the current plan.

I am still not entirely convinced that the `table` package needs to exist standalone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/182)*

**Comment by manishrjain** [comment]
Review status: 0 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[kv.go, line 41 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksr1_77vCEoFivf0viB:-Ksr1_77vCEoFivf0viC:bnavjhq) ([raw file](https://github.com/dgraph-io/badger/blob/7fb3bdb6d422d328959caf35d92b0a5325e1b0aa/kv.go#L41)):*
> ```Go
> )
> 
> func (opt *Options) estimateSize(entry *Entry) int {
> ```

Maybe move this to new file?

---

*[kv_test.go, line 42 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KshDepL8V9hw_WUlG2U:-KshDepL8V9hw_WUlG2V:bp8f4xc) ([raw file](https://github.com/dgraph-io/badger/blob/5c85ae2fe8d32105e035fdcd6ebc0338be72116b/kv_test.go#L42)):*
> ```Go
> 	opt.SyncWrites = true // Some tests seem to need this to pass.
> 	opt.ValueGCThreshold = 0.0
> 	opt.MapValueLogTo = MemoryMap // FIXME set this via a flag
> ```

via a flag in test?

---

*[value.go, line 113 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksr2H18mVw9Y7xpXDmR:-Ksr2H18mVw9Y7xpXDmS:b-upl0yb) ([raw file](https://github.com/dgraph-io/badger/blob/7fb3bdb6d422d328959caf35d92b0a5325e1b0aa/value.go#L113)):*
> ```Go
> 	defer lf.RUnlock()
> 
> 	var nbr int
> ```

var nbr int64

---

*[value.go, line 120 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksr22HsUDvttrlwLTRO:-Ksr22Ht8YBW7XYQf-e6:b-v92s0x) ([raw file](https://github.com/dgraph-io/badger/blob/7fb3bdb6d422d328959caf35d92b0a5325e1b0aa/value.go#L120)):*
> ```Go
> 		if offset >= size {
> 			err = y.ErrEOF
> 		} else if offset+valsz > size {
> ```

No need for if above. Just this should be sufficient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/182)*

**Comment by deepakjois** [comment]
Review status: 0 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[kv.go, line 41 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksr1_77vCEoFivf0viB:-KsraEvu02r32MHiUmJ5:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/7fb3bdb6d422d328959caf35d92b0a5325e1b0aa/kv.go#L41)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Maybe move this to new file?
</blockquote></details>

Done.

---

*[kv_test.go, line 42 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KshDepL8V9hw_WUlG2U:-KsraFkh3hPxYjv80KIJ:b5buhe5) ([raw file](https://github.com/dgraph-io/badger/blob/5c85ae2fe8d32105e035fdcd6ebc0338be72116b/kv_test.go#L42)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

via a flag in test?
</blockquote></details>

If we move to mmap-only by default, we will not need any flags. So keeping this in the interim.

---

*[value.go, line 54 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksg3BzVRm8cxRLzCIH8:-KsraOFTq2nRQrGunUbD:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/47b15d9faf2c7ca4a23cf6fbd9e152de3f535f81/value.go#L54)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

Moving it to parent creates a circular dependency. We could organize the options in a separate package instead. Will add a FIXME
</blockquote></details>

Done.

---

*[value.go, line 113 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksr2H18mVw9Y7xpXDmR:-KsraPITI-LPc48sfmuc:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/7fb3bdb6d422d328959caf35d92b0a5325e1b0aa/value.go#L113)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

var nbr int64
</blockquote></details>

Done.

---

*[value.go, line 120 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/182#-Ksr22HsUDvttrlwLTRO:-KsraR4eoXbx1m2zAi1S:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/7fb3bdb6d422d328959caf35d92b0a5325e1b0aa/value.go#L120)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for if above. Just this should be sufficient.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/182)*

**Comment by deepakjois** [comment]
Addressed all comments. Also rebased with the latest master.

Now moving onto changes in the `item.Value()` API and related stuff.

**Comment by deepakjois** [comment]
Review status: 0 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[table/table.go, line 40 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KskNzs74_u8zjNqIHPe:-KsrcVXu-N7uXf9PZWp1:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/5c85ae2fe8d32105e035fdcd6ebc0338be72116b/table/table.go#L40)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

Yes, we will need to duplicate. We could move all options to a separate `options` package, and import it in `badger` as well as `table` packages. That is the current plan.

I am still not entirely convinced that the `table` package needs to exist standalone.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/182)*

**Comment by deepakjois** [comment]
This is ready for another review. The change to make the `KVItem.Value()` method async is in the last diff. There are a couple of (new FIXMEs) for which comments would be useful.

I would like to run some basic benchmarks (16kb, 5mil dataset) to validate whether this leads to better read latency.

After this, I plan to work on the final set of changes to integrate mmap with read-write log file, and also any other changes required to handle file modifications when doing GC etc.

**Comment by deepakjois** [comment]
I am going to dump the benchmark numbers here in this comment. Please let me know if you think that’s a bit too noisy.

**Comment by deepakjois** [comment]
@manishrjain This is ready for another review.

I have retained the ValueLogLoadingMode option, so mmap-ing is still optional. It is a trivial change to remove the option and turn on mmap-ing by default.

I am not sure if this will work under value log GC. I did some reading which led me to believe that it shouldn’t be affected, but I am not sure. Trying to look at the code more deeply, now that this change is done.

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 3 of 7 files at r4, 2 of 9 files at r5, 2 of 5 files at r6, 2 of 6 files at r7, 6 of 6 files at r8.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[iterator.go, line 80 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPdYZ_PpN9A5HZMDLI:-KtPdYZ_PpN9A5HZMDLJ:b-nh5i8y) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/iterator.go#L80)):*
> ```Go
> 
> func (item *KVItem) prefetchValue() error {
> 	return item.kv.yieldItemValue(item, func(val []byte) {
> ```

item.Err = yieldItemValue(...)

---

*[iterator.go, line 154 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPfC_BMobQQ8OTjRvx:-KtPfC_BMobQQ8OTjRvy:b-1ex4r) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/iterator.go#L154)):*
> ```Go
> // IteratorOptions is used to set options when iterating over Badger key-value stores.
> type IteratorOptions struct {
> 	// Indicates whether we should prefetch values during iteration and store them. Note that this involves an additional
> ```

100 chars.

---

*[iterator.go, line 155 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPfK3lqI5XXaxISoIh:-KtPfK3lqI5XXaxISoIi:bc18jw9) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/iterator.go#L155)):*
> ```Go
> type IteratorOptions struct {
> 	// Indicates whether we should prefetch values during iteration and store them. Note that this involves an additional
> 	// copy because values have to be made available ahead of time.
> ```

this involves an additional copy, but still faster than fetching values synchronously.

---

*[options.go, line 52 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPhYpOtXpYPOr4XTGy:-KtPhYpOtXpYPOr4XTGz:b74n3ic) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/options.go#L52)):*
> ```Go
> 
> 	//  How to load value logs
> 	ValueLogLoadingMode options.FileLoadingMode
> ```

Probably don't need an option here.

---

*[value.go, line 575 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPgd4AagkDmDgEjVtM:-KtPgd4AagkDmDgEjVtN:b-1ex4r) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/value.go#L575)):*
> ```Go
> 			}
> 		} else {
> 			if err := lf.openReadOnly(vlog.opt.ValueLogLoadingMode == options.MemoryMap); err != nil {
> ```

100 chars.

---

*[value.go, line 738 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPgeBlJMb2NIyUaW9N:-KtPgeBlJMb2NIyUaW9O:b-1ex4r) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/value.go#L738)):*
> ```Go
> 		if curlf.offset > uint32(vlog.opt.ValueLogFileSize) {
> 			var err error
> 			if err = curlf.doneWriting(vlog.opt.ValueLogLoadingMode == options.MemoryMap); err != nil {
> ```

100 chars.

---

*[value.go, line 815 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPgoIsNCiy8MOyT5cE:-KtPgoIsNCiy8MOyT5cF:b-o7pu6u) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/value.go#L815)):*
> ```Go
> 	var h header
> 	h.Decode(buf)
> 	if (h.meta & BitDelete) != 0 {
> ```

Add a comment, // Tombstone key.

---

*[value.go, line 826 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPhG26-CnbydfQftrG:-KtPhG26-CnbydfQftrH:bvo0wdx) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/value.go#L826)):*
> ```Go
> }
> 
> func (vlog *valueLog) readRawValueBytes(vp valuePointer, slice *y.Slice) ([]byte, error) {
> ```

readValueBytes

---

*[value.go, line 834 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPhJTe4FJQgqrAZWHx:-KtPhJTe4FJQgqrAZWHy:bqqoclf) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/value.go#L834)):*
> ```Go
> 
> 	var buf []byte
> ```

Remove extra vertical space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/182#-:-KtPhc-TjDLSVab07KrJ:bnfp4nl)*

**Comment by deepakjois** [comment]
Review status: 6 of 15 files reviewed at latest revision, 11 unresolved discussions.

---

*[iterator.go, line 80 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPdYZ_PpN9A5HZMDLI:-KtQ3DBtX0DJKPhA1Jts:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/iterator.go#L80)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

item.Err = yieldItemValue(...)
</blockquote></details>

Done.

---

*[iterator.go, line 154 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPfC_BMobQQ8OTjRvx:-KtQ1qRQ3iyAVwGVSBip:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/iterator.go#L154)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[iterator.go, line 155 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPfK3lqI5XXaxISoIh:-KtQ1sKgxTJnvmOmCp9V:b-ebhsct) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/iterator.go#L155)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

this involves an additional copy, but still faster than fetching values synchronously.
</blockquote></details>

Removed this entirely.

---

*[kv.go, line 44 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KskN23-PAAugTS7ZgIC:-KtQ1xjESRpOMUClsUh9:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/5c85ae2fe8d32105e035fdcd6ebc0338be72116b/kv.go#L44)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.

---

*[options.go, line 52 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPhYpOtXpYPOr4XTGy:-KtQ2-bAJeh_0Kc2wfTA:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/options.go#L52)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Probably don't need an option here.
</blockquote></details>

Done.

---

*[value.go, line 575 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPgd4AagkDmDgEjVtM:-KtQ16crtf1wNBll0mno:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/value.go#L575)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[value.go, line 738 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPgeBlJMb2NIyUaW9N:-KtQ16G2PIaCbRairQ7H:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/value.go#L738)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[value.go, line 815 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPgoIsNCiy8MOyT5cE:-KtQ3QybYUuDBGm1PVJp:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/value.go#L815)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment, // Tombstone key.
</blockquote></details>

Done.

---

*[value.go, line 826 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPhG26-CnbydfQftrG:-KtQ3XAYw0TbKngMtKPk:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/value.go#L826)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

readValueBytes
</blockquote></details>

Done.

---

*[value.go, line 834 at r8](https://reviewable.io:443/reviews/dgraph-io/badger/182#-KtPhJTe4FJQgqrAZWHx:-KtQ15Dm7mUDUc1GUvU7:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/73e3fc9a928c64c2d22c91a555ae10120b126cc4/value.go#L834)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove extra vertical space
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/182)*

**Pull request merged**
