### PR TITLE
Add magic and version to front of manifest

### PR DESCRIPTION
**Pull request by srh**
Adds magic value and version number to the front of the manifest file.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/165)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[manifest.go, line 116 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/165#-KrZKC45Jdsn6cOhg_H4:-KrZKC45Jdsn6cOhg_H5:b-hfpv1m) ([raw file](https://github.com/dgraph-io/badger/blob/0587bc87d6fc34dbcbaa1ec1138055a3a57fc9d4/manifest.go#L116)):*
> ```Go
> 	if err != nil {
> 		if !os.IsNotExist(err) {
> 			fmt.Println(err)
> ```

remove?

---

*[manifest.go, line 203 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/165#-KrZKk7o9JGWOkwfIlzt:-KrZKk7o9JGWOkwfIlzu:bevvvk5) ([raw file](https://github.com/dgraph-io/badger/blob/0587bc87d6fc34dbcbaa1ec1138055a3a57fc9d4/manifest.go#L203)):*
> ```Go
> 
> const (
> 	magicText    = "Bdgr"
> ```

Mention in comments that this must be 4 bytes. In fact, use `magicText = [4]byte("Bdgr")`, so you don't need to convert it later (just a suggestion).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/165#-:-KrZLnQUC6UETvzpYwTh:bnfp4nl)*

**Comment by srh** [comment]
In master as of ad23a425b3c87b8223780cb882bed568ca14b9f0.

**Comment by srh** [comment]
*[manifest.go, line 116 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/165#-KrZKC45Jdsn6cOhg_H4:-KrZNjl9zi90YSsP7NrX:b-ydgl6o) ([raw file](https://github.com/dgraph-io/badger/blob/0587bc87d6fc34dbcbaa1ec1138055a3a57fc9d4/manifest.go#L116)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Definitely.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/165)*

**Comment by srh** [comment]
*[manifest.go, line 203 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/165#-KrZKk7o9JGWOkwfIlzt:-KrZRcg_qrWGAZ6eabx-:baruzyp) ([raw file](https://github.com/dgraph-io/badger/blob/0587bc87d6fc34dbcbaa1ec1138055a3a57fc9d4/manifest.go#L203)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Mention in comments that this must be 4 bytes. In fact, use `magicText = [4]byte("Bdgr")`, so you don't need to convert it later (just a suggestion).
</blockquote></details>

Went with the suggestion, and added a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/165)*

**Pull request closed without merging**
