### PR TITLE
Support multiple iterators in read-write transactions.

### PR DESCRIPTION
**Pull request by elliotcourant**
This adds support for multiple iterators during a read-write transaction. But iterators created in a read-write transaction will only be able to see writes that were performed before the iterator was created. Any writes that occur after the iterator is created will be invisible to the iterator.

This references an issue I opened previously: #981

I had closed this issue as I was able to work with a single iterator but I'm not trying to read multiple sequences of keys and values from different areas in the database at the same time, and the most efficient way to do this seems to be with multiple iterators.

Fixes https://github.com/dgraph-io/badger/issues/981

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1286)

### CODE REVIEW

**Comment by jarifibrahim** [comment]
Hey @elliotcourant, Thank you so much for the PR. The change looks like a simple change. I wonder why were multiple iterators disabled in Read-Write transactions. Maybe @manishrjain would know.

**Comment by elliotcourant** [comment]
Thank you very much for the feedback, I will make those changes!

**Comment by elliotcourant** [comment]
I think change it so that all transactions would be RW would be a bit of a large change in this MR. I will add tests for creating and using multiple iterators in a RW transaction though.

**Comment by jarifibrahim** [comment]
@elliotcourant I think there will be a race condition if we have multiple iterators here

**Comment by elliotcourant** [comment]
@jarifibrahim If you are iterating in multiple go routines then you are absolutely right. I don't think adding a mutex to appending that array would be very bad. I would think that most iterators are in a single thread to begin with, or (at least as of right now) are using read only transactions for multiple iterators. So adding a mutex would not impact any existing behavior. 
As for the performance implications I'm not sure. If the performance of a mutex is a concern then I could try to find another solution?

**Comment by elliotcourant** [comment]
Just pushed the updates from the code review and squashed my commits. 

@jarifibrahim I added a mutex around the addKey method, which should make concurrent reads safe. However it is still currently _possible_ that if one were to try to perform a read on thread A and try to commit on thread B at the same time that a race condition could occur? As thread B would be accessing the read array without a lock while thread A might try to append the read array.

I don't see that happening very often, and it's certainly possible that it could happen now? Since there is nothing stopping a user from having a single iterator on a different thread and trying to commit at the same time. 

I added a sub test to make sure that multiple concurrent iterators are working with a read-write transaction.

Another option to support more "lockless" reads with multiple iterators could be to store the keys read on the iterator itself, and then only when the iterator is closed will it try to push them to the read array on the transaction? This way we could have the commit action close all the active iterators before checking the read array, pushing the work to be done at the commit time, rather than as the reads are being performed?

**Comment by elliotcourant** [comment]
@jarifibrahim @manishrjain Is there any more feedback you have on this PR? Or are there any further changes that you think need to be made?

**Comment by jarifibrahim** [comment]
Hey @elliotcourant, I'll get this merged today. Thanks for your contribution :+1: 
>@jarifibrahim I added a mutex around the addKey method, which should make concurrent reads safe. However, it is still currently possible that if one were to try to perform a read on thread A and try to commit on thread B at the same time that a race condition could occur? As thread B would be accessing the read array without a lock while thread A might try to append the read array.

That won't happen because we acquire lock on oracle before checking for conflicts https://github.com/dgraph-io/badger/blob/9459a240bdf3cf1bf59a172558b37455c742d3bf/txn.go#L167-L174

**Comment by jarifibrahim** [comment]
Thank you for your contribution @elliotcourant . I've merged your PR :tada:

**Pull request merged**
