### PR TITLE
Add the NextSequence feature.

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/346)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[db.go, line 1104 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/346#-L01xKOjfs8Gwl4vbt1O:-L01wfiHiK4Kk5xDExD_:b-nfiskc) ([raw file](https://github.com/dgraph-io/badger/blob/6aef3809f1b56e6e40c7e35359eef675615c706e/db.go#L1104)):*
> ```Go
> // integers. Multiple sequences can be created by providing different keys. Bandwidth sets the
> // size of the lease, determining how many Next() requests can be served from memory.
> func (db *DB) GetSequence(key []byte, bandwidth uint64) (*Sequence, error) {
> ```

Add comment that it doesn't work in managed DB.

---

*[db.go, line 1111 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/346#-L01xzEHZyYTe8lU71mR:-L01xzEHZyYTe8lU71mS:bnegszv) ([raw file](https://github.com/dgraph-io/badger/blob/6aef3809f1b56e6e40c7e35359eef675615c706e/db.go#L1111)):*
> ```Go
> 		leased:    0,
> 		bandwidth: bandwidth,
> 	}
> ```

Throw error if bandwidth == 0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/346#-:-L01y3TPfMhsnYqXlg7T:bnfp4nl)*

**Comment by deepakjois** [comment]
* What happens when more than one goroutine request a sequence with the same key?

* It would nice to update the README to explain this feature. Maybe create an issue for it?

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[db.go, line 1108 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/346#-L02ny7Vfa-bCJxMxZ2y:-L02ny7Vfa-bCJxMxZ2z:b-134oac) ([raw file](https://github.com/dgraph-io/badger/blob/6aef3809f1b56e6e40c7e35359eef675615c706e/db.go#L1108)):*
> ```Go
> 		db:        db,
> 		key:       key,
> 		next:      0,
> ```

(Disclaimer: I don’t fully understand the use of this)

So, the `next` always starts at 0? There is no use case for values other than 0?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/346#-:-L02ookt2kT8Zzqfh2ua:bqn0r4r)*

**Comment by manishrjain** [comment]
1. Same key: Adding that check would come at more complexity (tracking all the sequences in the system), something that a user can easily avoid.
2. Added.

---

Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[db.go, line 1104 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/346#-L01xKOjfs8Gwl4vbt1O:-L02q13QGEjkF0WwzZWX:b-w28o92) ([raw file](https://github.com/dgraph-io/badger/blob/6aef3809f1b56e6e40c7e35359eef675615c706e/db.go#L1104)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Add comment that it doesn't work in managed DB.
</blockquote></details>

DONE. Good point. I've added a panic for mdb. And added a comment.

---

*[db.go, line 1108 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/346#-L02ny7Vfa-bCJxMxZ2y:-L02rUkVe7WY10nH6Y9G:b-o54q83) ([raw file](https://github.com/dgraph-io/badger/blob/6aef3809f1b56e6e40c7e35359eef675615c706e/db.go#L1108)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

(Disclaimer: I don’t fully understand the use of this)

So, the `next` always starts at 0? There is no use case for values other than 0?
</blockquote></details>

Yes. It's convenience v/s flexibility, I chose convenience. One can always iterate and pick values from some number N, if they want to start from N.

---

*[db.go, line 1111 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/346#-L01xzEHZyYTe8lU71mR:-L02rgryM79ef7xoNeFM:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/6aef3809f1b56e6e40c7e35359eef675615c706e/db.go#L1111)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Throw error if bandwidth == 0
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/346#-:-L02rlGXbFcfKrkiIrwX:b-q8ba8w)*

**Comment by deepakjois** [comment]
Cool!

:lgtm_strong: 

---

Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/346#-:-L02w8cJGQUPXnXA_ljn:b-c68ofr)*

**Pull request closed without merging**
