### PR TITLE
Skip the head key in iterator so that its not returned to the user

### LINKED ISSUE #37: Slice bounds out of range error
Steps to reproduce

1. Compile and run dgraph on branch `badger`.
`./dgraph`

2. Load goldendata using dgraphloader.
`./dgraphloader -r ~/go/src/github.com/dgraph-io/benchmarks/data/goldendata.rdf.gz`

3. As soon as dgraphloader finishes, issue a shutdown command to server.
`curl localhost:8080/admin/shutdown`

4. Start Dgraph again.
`./dgraph`

5. Now try taking a backup.
`curl localhost:8080/admin/backup`

Dgraph panics with error
```
panic: runtime error: slice bounds out of range

goroutine 19899 [running]:
github.com/dgraph-io/dgraph/x.Parse(0xc43331498a, 0x6, 0x6, 0x2)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/x/keys.go:195 +0x236
github.com/dgraph-io/dgraph/worker.backup(0x1, 0xcd16da, 0x6, 0x0, 0x0)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/worker/backup.go:254 +0x85e
github.com/dgraph-io/dgraph/worker.handleBackupForGroup(0x7f6d936a4970, 0xc4200105b0, 0x627d3dd58c69d20, 0xc400000001, 0x0)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/worker/backup.go:330 +0xa83
github.com/dgraph-io/dgraph/worker.BackupOverNetwork.func1(0xc42b4f6d20, 0x7f6d936a4970, 0xc4200105b0, 0x1)
	/home/pawan/go/src/github.com/dgraph-io/dgraph/worker/backup.go:445 +0x4b
created by github.com/dgraph-io/dgraph/worker.BackupOverNetwork
	/home/pawan/go/src/github.com/dgraph-io/dgraph/worker/backup.go:446 +0x138
```

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes #37

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/42)

### CODE REVIEW

**Comment by manishrjain** [comment]
Let me know when this is ready for review.

**Comment by manishrjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[badger/iterator.go, line 208 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/42#-Kki5Jdx5Z2NJmPwNUOh:-Kki5Jdx5Z2NJmPwNUOi:b-nml42q) ([raw file](https://github.com/dgraph-io/badger/blob/0e11f61b4b6945ce977efaed26a795798366ce89/badger/iterator.go#L208)):*
> ```Go
> 	}
> 	it.iitr.Seek(key)
> 	if !it.pastHead && bytes.Equal(it.iitr.Key(), head) {
> ```

We should probably do this for an entire prefix, that is specific to badger. So, we should change the name of this to `!badger!head`; and then skip all keys who start with `!badger!`. `!` occurs earlier than `/`, and is also much less commonly used.

I think to avoid complexity, and to avoid doing micro optimizations (which I suggested), let's just use `bytes.HasPrefix(..)` to determine if they key has this `!badger!` prefix, and if so, skip the keys until you find the first non-such key. Then we can just get rid of this `pastHead` logic and just compare every key. `bytes.HasPrefix` should be able to determine the outcome pretty fast anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/42)*

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[badger/iterator.go, line 208 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/42#-Kki5Jdx5Z2NJmPwNUOh:-KkiKYRWOwhDFbSzYkCA:b-oh178x) ([raw file](https://github.com/dgraph-io/badger/blob/0e11f61b4b6945ce977efaed26a795798366ce89/badger/iterator.go#L208)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We should probably do this for an entire prefix, that is specific to badger. So, we should change the name of this to `!badger!head`; and then skip all keys who start with `!badger!`. `!` occurs earlier than `/`, and is also much less commonly used.

I think to avoid complexity, and to avoid doing micro optimizations (which I suggested), let's just use `bytes.HasPrefix(..)` to determine if they key has this `!badger!` prefix, and if so, skip the keys until you find the first non-such key. Then we can just get rid of this `pastHead` logic and just compare every key. `bytes.HasPrefix` should be able to determine the outcome pretty fast anyway.
</blockquote></details>

Done. That's cleaner and leaves scope for adding new keys later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/42)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[badger/iterator.go, line 176 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/42#-KlHPOZEURji7FYa4Oyt:-KlHPOZEURji7FYa4Oyu:b-dwogs5) ([raw file](https://github.com/dgraph-io/badger/blob/7a9e9ff97f2a0528ed96c1526bce73df88c3c0af/badger/iterator.go#L176)):*
> ```Go
> 	it.item = nil
> 	for ; i.Valid(); i.Next() {
> 		if bytes.HasPrefix(it.iitr.Key(), badgerPrefix) {
> ```

Use i instead of it.iitr

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/42#-:-KlHSb1t1djAT3a95dL0:bnfp4nl)*

**Pull request closed without merging**
