### PR TITLE
Limit key/value sizes to 1G

### PR DESCRIPTION
**Pull request by peterstace**
* Key/values can now only be 1G.
* Checked when the user sets kv pairs.
* Checked during value log replay, truncating if the keys are too big (since it must be from a garbage file append crash scenario).

Wasn't too sure the best way to integrate checking into the BatchSet operation. I also considered looping over the `entries` at the start of `BatchSet`, but then you have to either make multiple calls to `sendToWriteCh` (for each contiguous chunk of good entries), or rebuild a slice of validated entries and pass to `sendToWriteCh`. Neither of those options seem too nice.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/158)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[kv.go, line 756 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEvqnMEAavCcREGHbN:-KrEvqnMEAavCcREGHbO:b4aw3ld) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L756)):*
> ```Go
> 	var bad []*Entry
> 	for _, entry := range entries {
> 		if len(entry.Key) > maxKeyValueSize || len(entry.Value) > maxKeyValueSize {
> ```

maxKeySize, maxValueSize.

1MB, 1GB.

---

*[kv.go, line 788 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEx-IhBDZobOwXoqVD:-KrEx-IhBDZobOwXoqVE:b-db1b77) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L788)):*
> ```Go
> 		b.Entries = bad
> 		b.Wg = sync.WaitGroup{}
> 		b.Err = ErrExceedsMaxKeyValueSize
> ```

No need to do this at request level. This should be at entry level.

---

*[kv.go, line 790 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEwzGp-NnfrcYfhiPs:-KrEwzGp-NnfrcYfhiPt:b-g6pfuu) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L790)):*
> ```Go
> 		b.Err = ErrExceedsMaxKeyValueSize
> 		b.Ptrs = nil
> 		reqs = append(reqs, b)
> ```

A counter here as well.

---

*[kv.go, line 793 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEyuHQMp-pE3wWILB1:-KrEyuHQMp-pE3wWILB2:b-voa52g) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L793)):*
> ```Go
> 	}
> 
> 	return reqs
> ```

Change the way we do Set and SetAsync, and return entry level error as well.

---

*[kv.go, line 816 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEz3aLZggAnRH0_z8p:-KrEz3aLZggAnRH0_z8q:b4wlfk9) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L816)):*
> ```Go
> 
> // BatchSetAsync is the asynchronous version of BatchSet. It accepts a callback function
> // which is called when all the sets are complete. Any error during execution is passed as an
> ```

Not any error. Any request level error is passed as an arg. User is expected to still check errors at the Entry level.

---

*[kv.go, line 818 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrF-OpJf5mWC9WJaHTs:-KrF-OpJf5mWC9WJaHTt:b-6albs) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L818)):*
> ```Go
> // which is called when all the sets are complete. Any error during execution is passed as an
> // argument to the callback function.
> func (s *KV) BatchSetAsync(entries []*Entry, f func(error)) {
> ```

  18 // SetAsync is the asynchronous version of Set. It accepts a callback function which is called            
    17 // when the set is complete. Any error encountered during execution is passed as an argument              
    16 // to the callback function.                                                                              
    15 func (s *KV) SetAsync(key, val []byte, userMeta byte, f func(error)) {                                    
    14     e := &Entry{                                                                                          
    13         Key:      key,                                                                                    
    12         Value:    val,                                                                                    
    11         UserMeta: userMeta,                                                                               
    10     }                                                                                                     
~    9     s.BatchSetAsync([]*Entry{e}, func(es entries, err error) {                                            
+    8         if err != nil {                                                                                   
+    7             f(err)                                                                                        
+    6         }                                                                                                 
+    5         for _, e := range es {                                                                            
+    4             if e.Error != nil {                                                                           
+    3                 f(e.Error)                                                                                
+    2             }                                                                                             
+    1         }                                                                                                 
+ 858          f(nil)                                                                                            
+    1     })                                                                                                    
     2 }       

---

*[kv.go, line 820 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEvBqd6gWMwpg-q-Pw:-KrEvBqd6gWMwpg-q-Px:bew2ieb) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L820)):*
> ```Go
> func (s *KV) BatchSetAsync(entries []*Entry, f func(error)) {
> 	go func() {
> 		err := s.BatchSet(entries)
> ```

Can't do this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/158)*

**Comment by peterstace** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[kv.go, line 756 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEvqnMEAavCcREGHbN:-KrF121K4Ordf47KHW-E:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L756)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

maxKeySize, maxValueSize.

1MB, 1GB.
</blockquote></details>

Done.

---

*[kv.go, line 788 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEx-IhBDZobOwXoqVD:-KrFAB0Vt81XrvrxNobU:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L788)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to do this at request level. This should be at entry level.
</blockquote></details>

Done.

---

*[kv.go, line 790 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEwzGp-NnfrcYfhiPs:-KrFAbiaTBeVBaRdo0Ps:b-vyrtuu) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L790)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

A counter here as well.
</blockquote></details>

I'm not sure what you mean. Can you clarify?

---

*[kv.go, line 793 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEyuHQMp-pE3wWILB1:-KrF9uksovmsdDg3sBnQ:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L793)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Change the way we do Set and SetAsync, and return entry level error as well.
</blockquote></details>

Done.

---

*[kv.go, line 816 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEz3aLZggAnRH0_z8p:-KrF9IzUZAgK6C07n5xV:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L816)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Not any error. Any request level error is passed as an arg. User is expected to still check errors at the Entry level.
</blockquote></details>

Done.

---

*[kv.go, line 818 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrF-OpJf5mWC9WJaHTs:-KrF6U1ljBvHIWqnheJ5:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L818)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

  18 // SetAsync is the asynchronous version of Set. It accepts a callback function which is called            
    17 // when the set is complete. Any error encountered during execution is passed as an argument              
    16 // to the callback function.                                                                              
    15 func (s *KV) SetAsync(key, val []byte, userMeta byte, f func(error)) {                                    
    14     e := &Entry{                                                                                          
    13         Key:      key,                                                                                    
    12         Value:    val,                                                                                    
    11         UserMeta: userMeta,                                                                               
    10     }                                                                                                     
~    9     s.BatchSetAsync([]*Entry{e}, func(es entries, err error) {                                            
+    8         if err != nil {                                                                                   
+    7             f(err)                                                                                        
+    6         }                                                                                                 
+    5         for _, e := range es {                                                                            
+    4             if e.Error != nil {                                                                           
+    3                 f(e.Error)                                                                                
+    2             }                                                                                             
+    1         }                                                                                                 
+ 858          f(nil)                                                                                            
+    1     })                                                                                                    
     2 }       
</blockquote></details>

Done.

---

*[kv.go, line 820 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEvBqd6gWMwpg-q-Pw:-KrF1QtwsBO4KjL2i1Fr:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L820)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can't do this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/158)*

**Comment by peterstace** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[kv.go, line 790 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrEwzGp-NnfrcYfhiPs:-KrFHLaE9lhIJxGlhOlc:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8cd6844456f02299baa5db54cff57ed05c8ee68a/kv.go#L790)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

I'm not sure what you mean. Can you clarify?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/158)*

**Comment by manishrjain** [comment]
:lgtm: One comment.

---

Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[y/metrics.go, line 48 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrUHrF6oOQ3youY5Os-:-KrUHrF6oOQ3youY5Os0:bgb9mqv) ([raw file](https://github.com/dgraph-io/badger/blob/5ed616998172af524b585ab1306b6b55d58fec84/y/metrics.go#L48)):*
> ```Go
> 	NumGets = expvar.NewInt("badger_gets_total")
> 	NumPuts = expvar.NewInt("badger_puts_total")
> 	NumBlockedLargePuts = expvar.NewInt("badger_blocked_large_puts")
> ```

badger_blocked_puts_total

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/158#-:-KrUHueeoQjKtpxVumtv:bpjwta0)*

**Comment by peterstace** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[y/metrics.go, line 48 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/158#-KrUHrF6oOQ3youY5Os-:-KrUSG60mW5hGHBrUe2O:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/5ed616998172af524b585ab1306b6b55d58fec84/y/metrics.go#L48)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

badger_blocked_puts_total
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/158)*

**Pull request merged**
