### PR TITLE
chore(tests): unbreak tests on Windows

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
Currently [appveyor tests](https://ci.appveyor.com/project/manishrjain/badger/builds/42502297) are failing in multiple places on Windows.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1775)

### CODE REVIEW

**Comment by akon-dey** [comment]
@SaveTheRbtz Thank you for looking into this. I think that we should fix the underlying problem with the Windows build instead of making the tests pass. I would like to get the opinion of the community on this issue before we merge. Please express your opinion.

**Review by jarifibrahim — APPROVED** [review]
The change looks good to me! @SaveTheRbtz we cannot merge the PR without the CLA signed. Can you please sign it?

@akon-dey This PR is fixing issues with windows build. The two tests that are skipped would fail on windows because they're testing a behaviour that's only supported on linux.

It might've taken a lot of effort to fix these tests. Thank you @SaveTheRbtz 🎉

**Comment by SaveTheRbtz** [comment]
Signed CLA, merged with `main`.

**Review by akon-dey — APPROVED** [review]

**Comment by akon-dey** [comment]
Thank you for your contribution @SaveTheRbtz !

**Pull request merged**
