### PR TITLE
test: Fix TestDropReadOnly failed on windows

### PR DESCRIPTION
**Pull request by Xuanwo**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/661)

### CODE REVIEW

**Comment by manishrjain** [comment]
The bigger question is, why does this fail on Windows? `vlog.deleteLogFile` does call `unmap` before closing the file and deleting it.

@martinmr : Can you figure out the cause of this failure, and fix it?

**Comment by Xuanwo** [comment]
Well, it makes sense. I force pushed a commit to do the change, PLTA @martinmr

**Comment by Xuanwo** [comment]
OK, it's better if no os-specific code needed.

**Comment by martinmr** [comment]
I checked and this looks like a limitation of the file system so it should be fine to have the OS-specific check since there's no way around it.

@manishrjain,  what do you say?

**Comment by martinmr** [comment]
Thanks for the PR. We discussed this issue internally and since there's no easy way to get around this limitation, we'll merge your PR.

**Pull request merged**
