### PR TITLE
Make fileID be uint32 instead of uint16

### PR DESCRIPTION
**Pull request by srh**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/193)

### CODE REVIEW

**Comment by srh** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[kv.go, line 301 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/193#-Kt8uAa6Ivre3QG4wBh2:-Kt8uAa7vBlSkeF4eOOq:b-pyohxr) ([raw file](https://github.com/dgraph-io/badger/blob/2a6fc673dc60d17d7bcb75c95f5d4b661658b7a8/kv.go#L301)):*
> ```Go
> 			copy(nv, e.Value)
> 		} else {
> 			nv = make([]byte, 16)
> ```

One disturbing thing was this constant being 16.  It should have been 10, as far as I can tell.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/193)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/193#-:-Kt9Ej13tStn4FxIzd43:bnfp4nl)*

**Comment by srh** [comment]
In master as of 1bb582e7c22b614f534391d19e9b8c6a8077fa9c.

**Comment by manishrjain** [comment]
Forgot to mention, the manifest version number would need to be changed here -- given this is a breaking change, right?

**Comment by srh** [comment]
We haven't released a version of Badger.  So it depends on how we want to manage version numbers.

**Pull request closed without merging**
