### PR TITLE
Allow a way to quickly estimate the size of a range.

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/190)

### CODE REVIEW

**Comment by manishrjain** [comment]
I need this to figure out the size consumed by a predicate in Dgraph.

**Comment by srh** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[iterator.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/190#-KsvH_xZOh4DunovvQgR:-KsvH_xZOh4DunovvQgS:b-nefk9t) ([raw file](https://github.com/dgraph-io/badger/blob/98d7d7aff4da78745af79bba0cf9048d8430c3ea/iterator.go#L65)):*
> ```Go
> }
> 
> // EstimatedSize returns approximate size of the key-value pair.  This can be called with
> ```

I would guess all uses of this function will need to cast the result to int64 or uint64.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/190)*

**Comment by srh** [comment]
Basically :lgtm:, I have some paranoid comments though.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[iterator.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/190#-KsvH_xZOh4DunovvQgR:-KsvHqYsDTgKO8xZl6Xe:b-6achxb) ([raw file](https://github.com/dgraph-io/badger/blob/98d7d7aff4da78745af79bba0cf9048d8430c3ea/iterator.go#L65)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

I would guess all uses of this function will need to cast the result to int64 or uint64.
</blockquote></details>

My main complaint here is I'd want a comment saying more specifically what this is estimating.  Is it len(key)+len(value) or disk usage?  If we have a value pointer, we don't account for the duplicate cost of index entry + value log entry.  I wouldn't know whether that's appropriate or not.

---

*[kv_test.go, line 657 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/190#-KsvISm1mvq5Fb7CTbY3:-KsvISm2vhY4aDb4-RgR:b43l7ws) ([raw file](https://github.com/dgraph-io/badger/blob/98d7d7aff4da78745af79bba0cf9048d8430c3ea/kv_test.go#L657)):*
> ```Go
> 			idxIt = ps.NewIterator(iterOpt)
> 
> 			var estSize int
> ```

It's _ok_ to use int because this is a test.  If I had to justify wanting int64 here, I guess the best reason would be that somebody in the future might base their code off these examples.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/190#-:-KsvIOLA-it0hx5fKw4h:bpszao1)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/190#-:-KsvQRzfgqtAj7KYs3cd:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[iterator.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/190#-KsvH_xZOh4DunovvQgR:-KsvclJXu9H9QOxFMlWl:b-q1s4gv) ([raw file](https://github.com/dgraph-io/badger/blob/98d7d7aff4da78745af79bba0cf9048d8430c3ea/iterator.go#L65)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

My main complaint here is I'd want a comment saying more specifically what this is estimating.  Is it len(key)+len(value) or disk usage?  If we have a value pointer, we don't account for the duplicate cost of index entry + value log entry.  I wouldn't know whether that's appropriate or not.
</blockquote></details>

The estimate is really about the key-value. There's overhead to storing it, which I just deliberately ignored.

I was thinking about the int64 thing as well -- I assumed that the user would do the conversion from int to int64. But, if it's cleaner, can make it part of the API itself.

---

*[kv_test.go, line 657 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/190#-KsvISm1mvq5Fb7CTbY3:-Ksvd58XPKq2JWu-tchD:b-e6lryk) ([raw file](https://github.com/dgraph-io/badger/blob/98d7d7aff4da78745af79bba0cf9048d8430c3ea/kv_test.go#L657)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

It's _ok_ to use int because this is a test.  If I had to justify wanting int64 here, I guess the best reason would be that somebody in the future might base their code off these examples.
</blockquote></details>

True. Would make it int64.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/190)*

**Comment by srh** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/190#-:-KsvhcdFRfOT82XeQjlL:bnfp4nl)*

**Comment by manishrjain** [comment]
Submitted.

**Pull request closed without merging**
