### PR TITLE
Fixing compile failure for 32-bit systems

### PR DESCRIPTION
**Pull request by maxpert**
This PR fixes issue reported on [32-bit compile Issue](https://github.com/dgraph-io/badger/issues/89)

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/90)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[iterator.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/90#-Ko9zcvDvNHqrnxUDMS3:-Ko9zcvDvNHqrnxUDMS4:bqoaqfj) ([raw file](https://github.com/dgraph-io/badger/blob/b192d6191ae7b67fc9cfaa1a55d600b3fd875b9f/iterator.go#L46)):*
> ```Go
> // Value returns the value, generally fetched from the value log. This call can block while
> // the value is populated asynchronously via a disk read. Remember to parse or copy it if you
> // need to reuse it. DO NOT append to this slice, it would result in internal data overwrite.
> ```

Can you remove this file from your changes. This is causing a revert of a new change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/90)*

**Comment by maxpert** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[iterator.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/90#-Ko9zcvDvNHqrnxUDMS3:-KoA1GZ8L9IK7dEfBR24:btctc38) ([raw file](https://github.com/dgraph-io/badger/blob/b192d6191ae7b67fc9cfaa1a55d600b3fd875b9f/iterator.go#L46)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can you remove this file from your changes. This is causing a revert of a new change.
</blockquote></details>

Done. I don't how this change made it's way in probably gofmt

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/90)*

**Comment by maxpert** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[iterator.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/90#-Ko9zcvDvNHqrnxUDMS3:-KoAA4ApIigcDR2hFvL1:b32w0x) ([raw file](https://github.com/dgraph-io/badger/blob/b192d6191ae7b67fc9cfaa1a55d600b3fd875b9f/iterator.go#L46)):*
<details><summary><i>Previously, maxpert (Zohaib Sibte Hassan) wrote…</i></summary><blockquote>

Done. I don't how this change made it's way in probably gofmt
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/90)*

**Comment by maxpert** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[iterator.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/90#-Ko9zcvDvNHqrnxUDMS3:-KoAAQPpqop6ONutmDQr:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/b192d6191ae7b67fc9cfaa1a55d600b3fd875b9f/iterator.go#L46)):*
<details><summary><i>Previously, maxpert (Zohaib Sibte Hassan) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/90)*

**Comment by maxpert** [comment]
Can't mark the comment resolve. Have fixed the issue though :smile:

**Comment by manishrjain** [comment]
:lgtm: Thanks for the fix.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/90#-:-KoAPc0u2cE8816KRM_J:b-72sm7t)*

**Pull request merged**
