### PR TITLE
defrag tool and related changes.

### PR DESCRIPTION
**Pull request by deepakjois**
* Code for defrag command

* Method to do offline GC on all files w/ discard ratio
  set to 0.0.

* Refactoring to keep code DRY.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/400)

### CODE REVIEW

**Comment by deepakjois** [comment]
Still working on the LSM tree compaction part, but would appreciate a review for the offline GC which runs on all value log files w/ discard ratio set to 0.0.

**Comment by deepakjois** [comment]
Now added code to do offline compaction as well.

**Comment by janardhan1993** [comment]
For offline we need to remove tombstones, i don't see any code for that. 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/400#-:-L31m16Xaho-HOC_zrN6:b-8eeckf)*

**Comment by deepakjois** [comment]
Hmm…yes. I forgot about that case. I haven’t really dug too deep into the code for the LSM stuff. The compaction part was easy to infer, but actually removing entries from the tables sounds a bit more involved. Any pointers for that?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/400#-:-L32RMFcmJbSk51DF1vn:b-kyu7wo)*

**Comment by janardhan1993** [comment]
While compacting if the final table belongs to last level, we can skip adding all the entries to table builder for which bitDelete or expired(there should be a function for checking that) is set in the meta

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/400#-:-L35CuhWsxnBGZhXbj6a:b-w0kcrf)*

**Pull request closed without merging**
