### PR TITLE
Add CRC to manifest

### PR DESCRIPTION
**Pull request by srh**
Connected to #155.

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/159)

### CODE REVIEW

**Comment by peterstace** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 111 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/159#-KrTBHb9klAc-4ytWpFy:-KrTBHb9klAc-4ytWpFz:b-gxcljt) ([raw file](https://github.com/dgraph-io/badger/blob/ab8ee6801c9eabe8d47a9a3ded8c30c8d644f426/value.go#L111)):*
> ```Go
> var errStop = errors.New("Stop iteration")
> 
> const entryHashSize = 4
> ```

The hash table and hash size should be placed together.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/159)*

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[manifest.go, line 284 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/159#-KrTF7gdMmCIPIoV2tjD:-KrTF7gdMmCIPIoV2tjE:bm5ht7v) ([raw file](https://github.com/dgraph-io/badger/blob/ab8ee6801c9eabe8d47a9a3ded8c30c8d644f426/manifest.go#L284)):*
> ```Go
> 		if crc32.Checksum(buf, y.CastagnoliCrcTable) != binary.BigEndian.Uint32(lenCrcBuf[4:8]) {
> 			fmt.Println("CRC mismatch")
> 			break
> ```

Just a break? Don't you need to send an error back? If so, add a comment about why there's no need to send an error back. Also, remove the fmt.Println() line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/159)*

**Comment by srh** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[manifest.go, line 284 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/159#-KrTF7gdMmCIPIoV2tjD:-KrTa-e6PuAjgotyTola:b-8h7md0) ([raw file](https://github.com/dgraph-io/badger/blob/ab8ee6801c9eabe8d47a9a3ded8c30c8d644f426/manifest.go#L284)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just a break? Don't you need to send an error back? If so, add a comment about why there's no need to send an error back. Also, remove the fmt.Println() line.
</blockquote></details>

There's no error to return.  The println was mistakenly left behind.

---

*[value.go, line 111 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/159#-KrTBHb9klAc-4ytWpFy:-KrTaQNkAAmEK3MEpxf0:b6fxtp5) ([raw file](https://github.com/dgraph-io/badger/blob/ab8ee6801c9eabe8d47a9a3ded8c30c8d644f426/value.go#L111)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

The hash table and hash size should be placed together.
</blockquote></details>

The size is associated with crc32 in general, which is used in the code below.  So I got rid of this variable (we don't have the equivalent in the manifest CRCing code) and used len(crcBuf) and such where appropriate.

---

*[value.go, line 366 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/159#-KrTezcD13AHgvUrvVJk:-KrTezcD13AHgvUrvVJl:b-9lc70s) ([raw file](https://github.com/dgraph-io/badger/blob/bb5b903f1d152917291d527393bd9898cd20204e/value.go#L366)):*
> ```Go
> 	var crcBuf [4]byte
> 	binary.BigEndian.PutUint32(crcBuf[:], hash.Sum32())
> 	buf.Write(crcBuf[:])
> ```

This is changed to use len(crcBuf) instead of entryHashSize.  But while doing that I looked at that io.MultiWriter, which adds another allocation and indirect function dispatches on what might be a hot path, and removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/159)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[value.go, line 366 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/159#-KrTezcD13AHgvUrvVJk:-KrTuEpEyaIae0X4Wowe:bb6ywmx) ([raw file](https://github.com/dgraph-io/badger/blob/bb5b903f1d152917291d527393bd9898cd20204e/value.go#L366)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

This is changed to use len(crcBuf) instead of entryHashSize.  But while doing that I looked at that io.MultiWriter, which adds another allocation and indirect function dispatches on what might be a hot path, and removed it.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/159#-:-KrTuHanMWqZ4LBHOXm9:bnfp4nl)*

**Pull request closed without merging**
