### PR TITLE
Add read/write metrics

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/120)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[compact_log.go, line 81 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnNk-DfdIYDR_FhKvI:-KpnNk-DfdIYDR_FhKvJ:by0znws) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/compact_log.go#L81)):*
> ```Go
> 	b := buf.Bytes()
> 	nbw, err := s.fd.Write(b) // Write in one sync.
> 	y.NumCompactLogBytesWritten.Add(int64(nbw))
> ```

skip this file.

---

*[kv.go, line 451 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnOAJGA99f6uHayhig:-KpnOAJGA99f6uHayhih:b-jzgzib) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/kv.go#L451)):*
> ```Go
> 	y.NumGets.Add(1)
> 	for i := 0; i < len(tables); i++ {
> 		vs := tables[i].Get(key)
> ```

// memtable-get

---

*[kv.go, line 456 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnOCPRyTpz5CrmTGGf:-KpnOCPRyTpz5CrmTGGg:b-qdrtho) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/kv.go#L456)):*
> ```Go
> 		}
> 	}
> 	return s.lc.get(key)
> ```

Go inside this, and do get per loop.

---

*[kv.go, line 720 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnPbeK6Mk_kJgZ6yGs:-KpnPbeK6Mk_kJgZ6yGt:b-8eqt8q) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/kv.go#L720)):*
> ```Go
> 		y.NumPuts.Add(1)
> 		if size >= s.opt.maxBatchSize {
> 			s.writeCh <- b
> ```

Just do the number of puts just before pushing to channel.

---

*[kv.go, line 728 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnPhGlpwVLjAy4v0y5:-KpnPhGmc826G-g2x9Zx:b-qg24et) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/kv.go#L728)):*
> ```Go
> 
> 	if size > 0 {
> 		s.writeCh <- b
> ```

Do it before every push to channel.

---

*[levels.go, line 302 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnPn25mxUCjOrNYFWC:-KpnPn25mxUCjOrNYFWD:bq2u9mc) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/levels.go#L302)):*
> ```Go
> 				return
> 			}
> 			y.NumWrites.Add(1)
> ```

skip this.

---

*[table/table.go, line 194 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnQO6hepMMXZFyFUwU:-KpnQO6hepMMXZFyFUwV:b-9dttjb) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/table/table.go#L194)):*
> ```Go
> 	pos := t.tableSize - 4 - len(t.metadata)
> 	nbw, err := t.fd.WriteAt(meta, int64(pos))
> 	y.NumWrites.Add(1)
> ```

remove this.

---

*[y/metrics.go, line 24 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnSIoYpSkQC7asyeVF:-KpnSIoYpSkQC7asyeVG:b-guk2zz) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/y/metrics.go#L24)):*
> ```Go
> 
> var (
> 	// These are cummulative
> ```

spelling mistake.

---

*[y/metrics.go, line 38 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnQZiEEmyQb5lS30c-:-KpnQZiEEmyQb5lS30c0:b-sajqd1) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/y/metrics.go#L38)):*
> ```Go
> 
> func init() {
> 	NumReads = expvar.NewInt("NumBadgerDiskReads")
> ```

`badger_disk_reads_total`

---

*[y/metrics.go, line 39 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnQfTsaYNakwdRlruI:-KpnQfTsaYNakwdRlruJ:b-pu7b3k) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/y/metrics.go#L39)):*
> ```Go
> func init() {
> 	NumReads = expvar.NewInt("NumBadgerDiskReads")
> 	NumWrites = expvar.NewInt("NumBadgerDiskWrites")
> ```

badger_disk_writes_total

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/120)*

**Comment by ashwin95r** [comment]
Review status: 1 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[compact_log.go, line 81 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnNk-DfdIYDR_FhKvI:-KpnUFUJwA4ypUaZ-ie4:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/compact_log.go#L81)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

skip this file.
</blockquote></details>

Done.

---

*[kv.go, line 451 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnOAJGA99f6uHayhig:-KpnbF1ZADBBCvZ2Binh:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/kv.go#L451)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

// memtable-get
</blockquote></details>

Done.

---

*[kv.go, line 456 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnOCPRyTpz5CrmTGGf:-KpnaC7P8mB1Yvfbgki2:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/kv.go#L456)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Go inside this, and do get per loop.
</blockquote></details>

Done.

---

*[kv.go, line 720 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnPbeK6Mk_kJgZ6yGs:-KpnUcd9y9O8Q-LMQ0xW:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/kv.go#L720)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just do the number of puts just before pushing to channel.
</blockquote></details>

Done.

---

*[kv.go, line 728 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnPhGlpwVLjAy4v0y5:-KpnUdbLmjMADYhYz_3O:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/kv.go#L728)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do it before every push to channel.
</blockquote></details>

Done.

---

*[levels.go, line 302 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnPn25mxUCjOrNYFWC:-KpnUj9qOTz0DFChAbhG:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/levels.go#L302)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

skip this.
</blockquote></details>

Done.

---

*[table/table.go, line 194 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnQO6hepMMXZFyFUwU:-KpnUmg9sLIxRRCqjo7M:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/table/table.go#L194)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove this.
</blockquote></details>

Done.

---

*[y/metrics.go, line 24 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnSIoYpSkQC7asyeVF:-KpnUs5EP1FaI28mS_dW:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/y/metrics.go#L24)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

spelling mistake.
</blockquote></details>

Done.

---

*[y/metrics.go, line 38 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnQZiEEmyQb5lS30c-:-KpnbFjyEnDgwmoml_5f:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/y/metrics.go#L38)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`badger_disk_reads_total`
</blockquote></details>

Done.

---

*[y/metrics.go, line 39 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpnQfTsaYNakwdRlruI:-KpnbGyo1inkYEjwgjdH:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/66d7a40474863c8f8617bc3c395f2d6e486fc1f8/y/metrics.go#L39)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

badger_disk_writes_total
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/120)*

**Comment by manishrjain** [comment]
:lgtm: Small comment.

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[level_handler.go, line 144 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpsTJKoxEhl8rAe349R:-KpsTJKoxEhl8rAe349S:b1aws3i) ([raw file](https://github.com/dgraph-io/badger/blob/72cf93e15784621f92271a196a78b452fbb4499d/level_handler.go#L144)):*
> ```Go
> 	return &levelHandler{
> 		level:    level,
> 		strLevel: fmt.Sprintf("L%d", level),
> ```

small case 'l'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/120#-:-KpsTggYclcFzl5QPcO3:b-pooq2x)*

**Comment by ashwin95r** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[level_handler.go, line 144 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/120#-KpsTJKoxEhl8rAe349R:-KpsfHOe4WSlCznJaqL3:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/72cf93e15784621f92271a196a78b452fbb4499d/level_handler.go#L144)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

small case 'l'.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/120)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
