### PR TITLE
Fixes for windows

### LINKED ISSUE #128: windows: panic > runtime error: invalid memory address or nil pointer dereference
```
 $ go run /tmp/badger.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x60 pc=0x6d2509]

goroutine 1 [running]:
github.com/dgraph-io/badger.(*KV).sendToWriteCh(0x0, 0xc042079d90, 0x1, 0x1, 0x0, 0x0, 0xc042079d50)
        C:/GoProjects/src/github.com/dgraph-io/badger/kv.go:699 +0xa9
github.com/dgraph-io/badger.(*KV).BatchSet(0x0, 0xc042079d90, 0x1, 0x1, 0x8, 0x5)
        C:/GoProjects/src/github.com/dgraph-io/badger/kv.go:723 +0x5d
github.com/dgraph-io/badger.(*KV).Set(0x0, 0xc042034fe0, 0x5, 0x8, 0xc042034fe8, 0x5, 0x8, 0x0, 0xc042079e88)
        C:/GoProjects/src/github.com/dgraph-io/badger/kv.go:763 +0xce
main.main()
        C:/tmp/badger.go:40 +0x1d1
exit status 2
```

```
package main

import (
	"fmt"
	"io/ioutil"

	"github.com/dgraph-io/badger"
)

var d string = "doc"

func main() {
	opt := badger.DefaultOptions
	dir, _ := ioutil.TempDir("/tmp", "badger")
	opt.Dir = dir
	opt.ValueDir = dir
	opt.LevelOneSize = 64 << 10
	opt.MaxTableSize = 32 << 10
	opt.ValueLogFileSize = 1 << 10
	kv, _ := badger.NewKV(&opt)

	key := []byte("hello")

	kv.Set(key, []byte("world"))
	fmt.Printf("SET %s world\n", key)

	var item badger.KVItem
	if err := kv.Get(key, &item); err != nil {
		fmt.Printf("Error while getting key: %q", key)
	}
	fmt.Printf("GET %s %s\n", key, item.Value())

	if err := kv.CompareAndSet(key, []byte("venus"), 100); err != nil {
		fmt.Println("CAS counter mismatch")
	} else {
		if err = kv.Get(key, &item); err != nil {
			fmt.Printf("Error while getting key: %q", key)
		}
		fmt.Printf("Set to %s\n", item.Value())
	}
	if err := kv.CompareAndSet(key, []byte("mars"), item.Counter()); err == nil {
		fmt.Println("Set to mars")
	} else {
		fmt.Printf("Unsuccessful write. Got error: %v\n", err)
	}
}
```

### PR DESCRIPTION
**Pull request by pawanrawal**
This PR fixes #128. Directory on windows need to be opened differently else `fsync` gives invalid file error. This is inspired from https://github.com/coreos/etcd/blob/master/pkg/fileutil/dir_windows.go.

Still, one test is failing `TestManifestRewrite`, looking into it.

Once all tests are fixed, it would be nice to setup https://www.appveyor.com/. It's like Travis but for Windows.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/149)

### CODE REVIEW

**Comment by manishrjain** [comment]
My comments here.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[dir_linux.go, line 17 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-aGmrC4RJldnys8mb:-Kr-aGmrC4RJldnys8mc:b-85egzt) ([raw file](https://github.com/dgraph-io/badger/blob/02c10317936de6f788ff727d91be4453f060abb3/dir_linux.go#L17)):*
> ```Go
>  */
> 
> // +build !windows
> ```

Can we be consistent about the builds? Other files list down a bunch of them; like directorylock_unix.go. That should also say `!windows`?

---

*[dir_windows.go, line 19 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-_ZXlPEXLNgQgeE2Y:-Kr-_ZXmAomW_FcUIlRd:b-5ct982) ([raw file](https://github.com/dgraph-io/badger/blob/02c10317936de6f788ff727d91be4453f060abb3/dir_windows.go#L19)):*
> ```Go
> // +build windows
> 
> package badger
> ```

Move directorylock_windows logic here.

---

*[kv.go, line 424 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-_jmJp-yv769y9Ik5:-Kr-_jmJp-yv769y9Ik6:b-sszv7v) ([raw file](https://github.com/dgraph-io/badger/blob/02c10317936de6f788ff727d91be4453f060abb3/kv.go#L424)):*
> ```Go
> 		return err
> 	}
> 	err = f.Sync()
> ```

Don't change this.

---

*[kv_test.go, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-_rhMzk5GuLthG9By:-Kr-_rhMzk5GuLthG9Bz:bjtowl) ([raw file](https://github.com/dgraph-io/badger/blob/02c10317936de6f788ff727d91be4453f060abb3/kv_test.go#L47)):*
> ```Go
> 
> func TestWrite(t *testing.T) {
> 	dir, err := ioutil.TempDir(os.TempDir(), "badger")
> ```

os.TempDir() isn't required.

---

*[manifest_test.go, line 118 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-_wthXKyAhEw895qu:-Kr-_wthXKyAhEw895qv:bq4jkty) ([raw file](https://github.com/dgraph-io/badger/blob/766bf27ef356e635744fa45ae8c0f7044c312367/manifest_test.go#L118)):*
> ```Go
> 
> func TestOverlappingKeyRangeError(t *testing.T) {
> 	dir, err := ioutil.TempDir("/tmp", "badger")
> ```

Make this empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/149#-:-Kr-aOjFOeEf8vRIt5UY:b-yqh1mn)*

**Comment by pawanrawal** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[dir_linux.go, line 17 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-aGmrC4RJldnys8mb:-Kr-hGAhEJNPCzm7-9mV:bq14qk9) ([raw file](https://github.com/dgraph-io/badger/blob/02c10317936de6f788ff727d91be4453f060abb3/dir_linux.go#L17)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can we be consistent about the builds? Other files list down a bunch of them; like directorylock_unix.go. That should also say `!windows`?
</blockquote></details>

Moved code from `directorylock_unix.go` to this file.

---

*[dir_windows.go, line 19 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-_ZXlPEXLNgQgeE2Y:-Kr-hL_Gaz74pLFxuHlr:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/02c10317936de6f788ff727d91be4453f060abb3/dir_windows.go#L19)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move directorylock_windows logic here.
</blockquote></details>

Done.

---

*[kv.go, line 424 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-_jmJp-yv769y9Ik5:-Kr-hUlGWaJN8gVcOA6s:b32w1t) ([raw file](https://github.com/dgraph-io/badger/blob/02c10317936de6f788ff727d91be4453f060abb3/kv.go#L424)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't change this.
</blockquote></details>

Ok

---

*[kv_test.go, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-_rhMzk5GuLthG9By:-Kr-hYAoaA01sATzb8oF:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/02c10317936de6f788ff727d91be4453f060abb3/kv_test.go#L47)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

os.TempDir() isn't required.
</blockquote></details>

Done.

---

*[manifest.go, line 223 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-higUavPoky-yuh8h:-Kr-higVc1z09cww9Act:b-4kv7li) ([raw file](https://github.com/dgraph-io/badger/blob/1e33c5f7c8f976c0e54b9dd5ce926a4b01acc626/manifest.go#L223)):*
> ```Go
> 	if err != nil {
> 		return err
> 	}
> ```

The test `TestManifestRewrite` still fails at line 197 while replaying manifest file with error
```
MANIFEST removes non-existing table 22
```

Earlier rename itself was failing.

---

*[manifest_test.go, line 118 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-_wthXKyAhEw895qu:-Kr-ha3jAc7UwK19-XYt:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/766bf27ef356e635744fa45ae8c0f7044c312367/manifest_test.go#L118)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make this empty.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/149)*

**Comment by srh** [comment]
Reviewed 1 of 10 files at r2.
Review status: 1 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[kv_test.go, line 51 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-mSl0-MdkUz0cVVFk:-Kr-mSl1XXhzbuaZxG_C:b-vuu851) ([raw file](https://github.com/dgraph-io/badger/blob/5f55091d5ee38a8bfd9782d961d29c30085e4411/kv_test.go#L51)):*
> ```Go
> 	defer os.RemoveAll(dir)
> 	kv, err := NewKV(getTestOptions(dir))
> 	y.Check(err)
> ```

This could be require.NoError, right

---

*[manifest.go, line 223 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-higUavPoky-yuh8h:-Kr-tXfi_2hIOOlS-apd:bh6lglz) ([raw file](https://github.com/dgraph-io/badger/blob/1e33c5f7c8f976c0e54b9dd5ce926a4b01acc626/manifest.go#L223)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

The test `TestManifestRewrite` still fails at line 197 while replaying manifest file with error
```
MANIFEST removes non-existing table 22
```

Earlier rename itself was failing.
</blockquote></details>

I've bisected the bug down and split apart a commit to find that it is the result of the changes in this file.  But everything looks correct.  

---

*[manifest.go, line 210 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-o-szbnaJT39OXQwk:-Kr-o-szbnaJT39OXQwl:bfaigqs) ([raw file](https://github.com/dgraph-io/badger/blob/5f55091d5ee38a8bfd9782d961d29c30085e4411/manifest.go#L210)):*
> ```Go
> 		return err
> 	}
> 	if err = mf.fp.Sync(); err != nil {
> ```

I think there is no reason to call Sync() here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/149)*

**Comment by srh** [comment]
Review status: 1 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[manifest.go, line 223 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-higUavPoky-yuh8h:-Kr-uwOZnzheZ6RFzTzz:bop927t) ([raw file](https://github.com/dgraph-io/badger/blob/1e33c5f7c8f976c0e54b9dd5ce926a4b01acc626/manifest.go#L223)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

I've bisected the bug down and split apart a commit to find that it is the result of the changes in this file.  But everything looks correct.  
</blockquote></details>

None of the errors here are non-nil.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/149)*

**Comment by pawanrawal** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[kv_test.go, line 51 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-mSl0-MdkUz0cVVFk:-Kr-xjagdtep1tH0jeLP:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/5f55091d5ee38a8bfd9782d961d29c30085e4411/kv_test.go#L51)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

This could be require.NoError, right
</blockquote></details>

Done.

---

*[manifest.go, line 223 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-higUavPoky-yuh8h:-Kr-xutFUkPSb5CWYNor:blrbsw) ([raw file](https://github.com/dgraph-io/badger/blob/1e33c5f7c8f976c0e54b9dd5ce926a4b01acc626/manifest.go#L223)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

None of the errors here are non-nil.
</blockquote></details>

Yeah, it's happening while trying to replay the manifest file not sure why though.

---

*[manifest.go, line 210 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-o-szbnaJT39OXQwk:-Kr-xd4pKUoUmmItg4GH:btfxb5v) ([raw file](https://github.com/dgraph-io/badger/blob/5f55091d5ee38a8bfd9782d961d29c30085e4411/manifest.go#L210)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

I think there is no reason to call Sync() here.
</blockquote></details>

Ok, removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/149)*

**Comment by srh** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[manifest.go, line 223 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-higUavPoky-yuh8h:-Kr3FjbipMPH-3sar7_c:by2lzff) ([raw file](https://github.com/dgraph-io/badger/blob/1e33c5f7c8f976c0e54b9dd5ce926a4b01acc626/manifest.go#L223)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Yeah, it's happening while trying to replay the manifest file not sure why though.
</blockquote></details>

I pushed a fix.  We needed a Seek.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/149)*

**Comment by pawanrawal** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[manifest.go, line 223 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/149#-Kr-higUavPoky-yuh8h:-Kr3JUU8xYOh1CbVsKDn:b-dqw04) ([raw file](https://github.com/dgraph-io/badger/blob/1e33c5f7c8f976c0e54b9dd5ce926a4b01acc626/manifest.go#L223)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

I pushed a fix.  We needed a Seek.
</blockquote></details>

Ah right, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/149)*

**Comment by manishrjain** [comment]
OK to submit from my side. I'd like @srh and you to have a deeper look into build flags, and make them consistent. In this PR, we're using `!windows` for all others; but previously we're using a list of names for various other platforms. We should pick one and stick to it.

Submit once @srh approves.

---

Reviewed 6 of 10 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/149#-:-Kr3Kqios7_46YbpbLGu:b-kpcz76)*

**Comment by srh** [comment]
I like the idea of using !platform to rule out specific platforms better than listing all the desirable platforms.  The reason is, that way, we don't have to maintain a list of compatible platforms.

So where we have mmap_unix.go and mmap_windows.go -- the file mmap_unix.go could just say `// +build !windows`

Where we have file_dragonfly.go, file_freebsd.go, file_unix.go, file_windows.go -- the file file_unix.go could just say `// +build !dragonfly !freebsd !windows`

I assume we should rename dir_linux.go to dir_unix.go.  Right now it won't build on non-Linux unixes, because of the filename suffix.  (Right?)

---

Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/149#-:-Kr3bIhVIYZ_Vv7dQ4HH:bw0kvao)*

**Comment by srh** [comment]
As far as the Windows code goes, it looks good to me.

---

Review status: 9 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/149#-:-Kr3iNUP9JhdKQv0VLF2:b-u5gmhk)*

**Comment by pawanrawal** [comment]
Done @srh. We have CI now which runs on Linux, OSX and Windows so should be easier to know if something breaks.

---

Review status: 7 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/149#-:-Kr8YsHktahFrXLqJPb4:b98azma)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
