### PR TITLE
Truncate partially written transaction entries from vlog

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/412)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[value.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/412#-L4da9oe05GEoDQurbi8:-L4da9oe05GEoDQurbi9:b-aulask) ([raw file](https://github.com/dgraph-io/badger/blob/05e4f1b554d4a6fe24fa6f9282c366bad88641ed/value.go#L289)):*
> ```Go
> 			validEndOffset = recordOffset
> 		} else {
> 			txnTs := y.ParseTs(e.Key)
> ```

This should no longer happen because we are no longer moving entries within the value logs. Everything should be either txn or txnfin.

---

*[value.go, line 799 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/412#-L4d_3S8BUtzE2K0Kh2H:-L4d_3S9sqIzQwadkALd:bcgjvre) ([raw file](https://github.com/dgraph-io/badger/blob/05e4f1b554d4a6fe24fa6f9282c366bad88641ed/value.go#L799)):*
> ```Go
> 		// Don't call this inside above for loop or entries from same transaction might get
> 		// split across multiple vlog files.
> 		if vlog.writableOffset()+uint32(vlog.buf.Len()) > uint32(vlog.opt.ValueLogFileSize) {
> ```

Why this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/412)*

**Comment by janardhan1993** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[value.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/412#-L4da9oe05GEoDQurbi8:-L6Qbc916wDtIn-EQVzd:b50ovkq) ([raw file](https://github.com/dgraph-io/badger/blob/05e4f1b554d4a6fe24fa6f9282c366bad88641ed/value.go#L289)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This should no longer happen because we are no longer moving entries within the value logs. Everything should be either txn or txnfin.
</blockquote></details>

Will remove this change once we merge v2.0-candidate branch, on master we still move the entries around.

---

*[value.go, line 799 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/412#-L4d_3S8BUtzE2K0Kh2H:-L6QbVpnrmsGV5gjlf-B:b-g4mi9k) ([raw file](https://github.com/dgraph-io/badger/blob/05e4f1b554d4a6fe24fa6f9282c366bad88641ed/value.go#L799)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

To ensure entries for a signle transaction are not split across vlog, this change pawan already merged in master in another PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/412)*

**Comment by manishrjain** [comment]
:lgtm: One comment.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[value.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/412#-L4da9oe05GEoDQurbi8:-L6URo8xKjfmQn1kCK4J:belk18l) ([raw file](https://github.com/dgraph-io/badger/blob/05e4f1b554d4a6fe24fa6f9282c366bad88641ed/value.go#L289)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Will remove this change once we merge v2.0-candidate branch, on master we still move the entries around.
</blockquote></details>

Add a comment here then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/412#-:-L6URs43zgfj03dA9aFD:bpjwta0)*

**Comment by janardhan1993** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/412#-L4da9oe05GEoDQurbi8:-L6UhzHb-7OBmzp6DHWM:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/05e4f1b554d4a6fe24fa6f9282c366bad88641ed/value.go#L289)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment here then.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/412)*

**Pull request merged**
