### PR TITLE
Fix an uint16 overflow when resizing key slice.

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/309)

### CODE REVIEW

**Comment by manishrjain** [comment]
This PR fixes #308

**Comment by manishrjain** [comment]
I did a self-review. Will go ahead and submit this fix, and release a bug fix.

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[iterator.go, line 115 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/309#-KyEkFDUlLgRHT0jr9sY:-KyEkFDUlLgRHT0jr9sZ:b-370161) ([raw file](https://github.com/dgraph-io/badger/blob/67c1a53da2f6e2bd21b8dad728c896cbeb0fcfb9/iterator.go#L115)):*
> ```Go
> 	vp.Decode(item.vptr)
> 	if vp.Len == 0 {
> 		return nil, nil, nil
> ```

This shouldn't happen.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/309#-:-KyEkCq4iy1MBgV466GZ:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[iterator.go, line 115 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/309#-KyEkFDUlLgRHT0jr9sY:-KyEl6x4Exe4NfwKNdfM:b-wnfmk9) ([raw file](https://github.com/dgraph-io/badger/blob/67c1a53da2f6e2bd21b8dad728c896cbeb0fcfb9/iterator.go#L115)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

This shouldn't happen.
</blockquote></details>

Done. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/309)*

**Comment by manishrjain** [comment]
Submitted.

**Pull request closed without merging**
