### PR TITLE
Transaction implementation

### PR DESCRIPTION
**Pull request by manishrjain**
- Enable versioning in Badger.
- Implement SSI (serializable snapshot isolation) based transactions, which can be run concurrently, based on Yabandeh's paper: A critique of snapshot isolation (with modifications).
- Using a map of committed rows -> timestamp to detect conflicts.

What works:
- Transactions: Concurrency, Conflict detection, Read snapshots, Versioning, etc.
- Get, Set, Commit
- Iteration within transactions.
- All the transaction logic works. The effect on other components needs to be done.

[WIP]
- The replay logic needs to be updated to understand txn boundaries and init readTs at start.
- Existing APIs need to be removed.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/247)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[transaction.go, line 79 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0UAyxDPQhnYVjz4-a:-Kv0UAyxDPQhnYVjz4-b:bpjgrv0) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L79)):*
> ```Go
> }
> 
> func (gs *globalTxnState) newCommitTs(txn *Txn) uint64 {
> ```

This being called a Ts is a bit confusing as it's not a timestamp but a counter.

---

*[transaction.go, line 140 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0Qfa-yziQEosz-Q9m:-Kv0Qfa-yziQEosz-Q9n:b6vc0gs) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L140)):*
> ```Go
> }
> 
> func (txn *Txn) Set(key, val []byte, userMeta byte) {
> ```

Should Set return error if update is false?

---

*[transaction.go, line 142 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0QHfB3mXVrczVWXYf:-Kv0QHfB3mXVrczVWXYg:b8eulb6) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L142)):*
> ```Go
> func (txn *Txn) Set(key, val []byte, userMeta byte) {
> 	fp := farm.Fingerprint64(key) // Avoid dealing with byte arrays.
> 	txn.writes = append(txn.writes, fp)
> ```

What if same key is set twice in the same transaction. Then writes would have duplicate keys, is that ok?

---

*[transaction.go, line 164 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0OnzSircvTltksiqn:-Kv0OnzSircvTltksiqo:b5jh1e8) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L164)):*
> ```Go
> 
> func (txn *Txn) Get(key []byte) (item KVItem, rerr error) {
> 	if txn.update {
> ```

Why do we check cache only when update is true?

---

*[transaction.go, line 205 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0Und8gwvv1Lyk-LaJ:-Kv0Und9dDBEJ75nxg66:b-7oxz45) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L205)):*
> ```Go
> 	defer txn.gs.doneCommit(commitTs)
> 
> 	var entries []*Entry
> ```

```
entries := make([]*Entry, 0, len(txn.cache) + 1)
```

---

*[y/y.go, line 90 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0PCEmQzj4sWYQEnRb:-Kv0PCEmQzj4sWYQEnRc:b25tvwd) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/y/y.go#L90)):*
> ```Go
> }
> 
> // KeyWithTs generates a new key by appending ts to key.
> ```

by appending MaxUint64 - ts to key.

Also a comment about why would be nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/247)*

**Comment by pawanrawal** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[transaction.go, line 83 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0YyCaxO8wQIwLCgVi:-Kv0YyCaxO8wQIwLCgVj:bcav1q8) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L83)):*
> ```Go
> 		return 0
> 	}
> ```

If two transactions are updating the same keys and both call `newCommitTs` at the same time, hasConflict can be false for both but then one of them would go through and then the second one could have conflict against this new version?

---

*[transaction.go, line 112 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0YaN_BjFtPwk0lKCH:-Kv0YaN_BjFtPwk0lKCI:bjlw3py) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L112)):*
> ```Go
> 	var min uint64
> 	for len(gs.commitMark) > 0 {
> 		ts := gs.commitMark[0]
> ```

There is some variable shadowing going on here. ts is passed to function and we declare another ts. We should rename this `ts` to `doneTs` maybe?

---

*[transaction.go, line 115 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0axBH0-qeQG02O7k5:-Kv0axBH0-qeQG02O7k6:b-q0gq28) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L115)):*
> ```Go
> 		if _, has := gs.pendingCommits[ts]; has {
> 			// Still waiting for a txn to commit.
> 			break
> ```

If this happens (say some earlier commit is pending) then the curRead won't be updated until another write comes through (that is when we call doneCommit) although BatchSet would already have completed. Would this lead to reading older values?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/247)*

**Comment by janardhan1993** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---

*[transaction.go, line 121 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4iq24NN-tloKqh-Qc:-Kv4iq24NN-tloKqh-Qd:b-3vru0s) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/transaction.go#L121)):*
> ```Go
> 	}
> 	atomic.StoreUint64(&gs.curRead, min)
> 	gs.nextCommit = min + 1
> ```

we shouldn't be updating nextCommit here

---

*[transaction.go, line 131 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4jTBO1Y32UYrypeqN:-Kv4jTBO1Y32UYrypeqO:bioky0j) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/transaction.go#L131)):*
> ```Go
> 	writes []uint64 // contains fingerprints of keys written.
> 
> 	pendingWrites map[uint64]*Entry // cache stores any writes done by txn.
> ```

We might loose writes if keys collide. 

---

*[transaction.go, line 137 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4mQgs3wwnSv0V3Jlb:-Kv4mQgs3wwnSv0V3Jlc:b-3gtjy0) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/transaction.go#L137)):*
> ```Go
> }
> 
> func (txn *Txn) Set(key, val []byte, userMeta byte) {
> ```

Throw error if txn.update is not set by the user ?

---

*[transaction.go, line 168 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4kPUMSKIgjzAsS4zz:-Kv4kPUMSKIgjzAsS5--:b-aoweo2) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/transaction.go#L168)):*
> ```Go
> 			item.userMeta = e.UserMeta
> 			item.key = key
> 			item.status = prefetched
> ```

item.kv is not set ?
we don't set meta, so we wouldn't know about deleted key.

---

*[transaction.go, line 240 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4l62aKS73EyluXTP-:-Kv4l62aKS73EyluXTP0:b-13yrln) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/transaction.go#L240)):*
> ```Go
> //   itr.Close()
> // TODO: Move this usage to README.
> func (txn *Txn) NewIterator(opt IteratorOptions) *Iterator {
> ```

what is this for ?

---

*[skl/skl.go, line 377 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4lIwv0haEdJ5JrCVv:-Kv4lIwv0haEdJ5JrCVw:bd3kfh7) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/skl/skl.go#L377)):*
> ```Go
> // version of the same key.
> func (s *Skiplist) Get(key []byte) y.ValueStruct {
> 	n, _ := s.findNear(key, false, true) // findGreaterOrEqual.
> ```

No need to check second argument ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/247)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---

*[transaction.go, line 79 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0UAyxDPQhnYVjz4-a:-Kv0fPGTyutEX0kUKUlf:b-oep7vs) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L79)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This being called a Ts is a bit confusing as it's not a timestamp but a counter.
</blockquote></details>

Because of the terminology around txns.

---

*[transaction.go, line 83 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0YyCaxO8wQIwLCgVi:-Kv0hEyHE8cAn-jz68D3:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L83)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

If two transactions are updating the same keys and both call `newCommitTs` at the same time, hasConflict can be false for both but then one of them would go through and then the second one could have conflict against this new version?
</blockquote></details>

Done.

---

*[transaction.go, line 112 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0YaN_BjFtPwk0lKCH:-Kv0hRMVKZsE84-IIzLO:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L112)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

There is some variable shadowing going on here. ts is passed to function and we declare another ts. We should rename this `ts` to `doneTs` maybe?
</blockquote></details>

Done.

---

*[transaction.go, line 115 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0axBH0-qeQG02O7k5:-Kv0hScuTD-f_l5_hSvC:b-eowr3y) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L115)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

If this happens (say some earlier commit is pending) then the curRead won't be updated until another write comes through (that is when we call doneCommit) although BatchSet would already have completed. Would this lead to reading older values?
</blockquote></details>

Clarified.

---

*[transaction.go, line 140 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0Qfa-yziQEosz-Q9m:-Kv0h_oH9yv02-SVP_eE:bpykp9w) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L140)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Should Set return error if update is false?
</blockquote></details>

Updating in the next PR.

---

*[transaction.go, line 142 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0QHfB3mXVrczVWXYf:-Kv0hiD97JBxzstMgV4V:b-3muwgw) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L142)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What if same key is set twice in the same transaction. Then writes would have duplicate keys, is that ok?
</blockquote></details>

Not a problem.

---

*[transaction.go, line 164 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0OnzSircvTltksiqn:-Kv0hvEDjzxGVfDUnf2i:bbh01xg) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L164)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Why do we check cache only when update is true?
</blockquote></details>

Changed it to pendingWrites.

---

*[transaction.go, line 205 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0Und8gwvv1Lyk-LaJ:-Kv0iQ7LZAKGr_Wiehgf:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/transaction.go#L205)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

```
entries := make([]*Entry, 0, len(txn.cache) + 1)
```
</blockquote></details>

Done.

---

*[transaction.go, line 121 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4iq24NN-tloKqh-Qc:-Kv4oNS-PSh8Gj3fSTSv:bwq2if7) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/transaction.go#L121)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

we shouldn't be updating nextCommit here
</blockquote></details>

Done. Part of the next PR.

---

*[transaction.go, line 131 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4jTBO1Y32UYrypeqN:-Kv4oaTkEKUl8Orv3KIK:b-a6gx7v) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/transaction.go#L131)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We might loose writes if keys collide. 
</blockquote></details>

Will change.

---

*[transaction.go, line 137 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4mQgs3wwnSv0V3Jlb:-Kv4ocGXjUrRhdetvnOh:b-mzyfc) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/transaction.go#L137)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Throw error if txn.update is not set by the user ?
</blockquote></details>

Done. Next PR.

---

*[transaction.go, line 168 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4kPUMSKIgjzAsS4zz:-Kv4opClAxxjUuIoS3Pt:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/transaction.go#L168)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

item.kv is not set ?
we don't set meta, so we wouldn't know about deleted key.
</blockquote></details>

Done.

---

*[transaction.go, line 240 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4l62aKS73EyluXTP-:-Kv4pRkc8bbFC5XMisuo:b3v4h68) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/transaction.go#L240)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

what is this for ?
</blockquote></details>

Iterator belongs to txn.

---

*[skl/skl.go, line 377 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv4lIwv0haEdJ5JrCVv:-Kv4sOl6S6Vzp3COCpXG:b7xxqit) ([raw file](https://github.com/dgraph-io/badger/blob/f6007c6828e2e7dce647166f220c4d6db7052aef/skl/skl.go#L377)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

No need to check second argument ?
</blockquote></details>

Yeah, no need.

---

*[y/y.go, line 90 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/247#-Kv0PCEmQzj4sWYQEnRb:-Kv0idLwhwXRN9wGq1dr:b4bokgg) ([raw file](https://github.com/dgraph-io/badger/blob/80bf92dea5783dfd167eabf4b5022623ac2df149/y/y.go#L90)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

by appending MaxUint64 - ts to key.

Also a comment about why would be nice.
</blockquote></details>

Explained this in parseItem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/247)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/247#-:-Kv4tjSjs5Zq9HGbvx-X:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/247#-:-Kv4ta3LDaiEKPrO3bkA:bnfp4nl)*

**Pull request closed without merging**
