### PR TITLE
Refactor and improve compaction logic

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/55)

### CODE REVIEW

**Comment by szymonm** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[badger/compaction.go, line 71 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-KlbnBVJpn7GUZ8hLVXW:-KlbnBVJpn7GUZ8hLVXX:b-odunx8) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/compaction.go#L71)):*
> ```Go
> 	var b bytes.Buffer
> 	for _, r := range lcs.ranges {
> 		b.WriteString(fmt.Sprintf("left=%q, right=%q inf=%v\n", r.left, r.right, r.inf))
> ```

you can use r.String() instead of Sprintf

---

*[badger/compaction.go, line 85 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-Klbp1U4Jzyq_RSF4sAI:-Klbp1U4Jzyq_RSF4sAJ:b-nhuc7b) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/compaction.go#L85)):*
> ```Go
> }
> 
> func (lcs *levelCompactStatus) remove(dst keyRange) bool {
> ```

According to: https://golang.org/doc/faq#methods_on_values_or_pointers
"If some of the methods of the type must have pointer receivers, the rest should too, so the method set is consistent regardless of how the type is used."
Do we follow it? I'm not convinced to this rule personally, like to have distinction between methods that change reciever and not.

---

*[badger/compaction.go, line 128 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-KlbqUY3N1C73pHmO7zd:-KlbqUY3N1C73pHmO7ze:bku317d) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/compaction.go#L128)):*
> ```Go
> }
> 
> func (cs *compactStatus) compareAndAdd(cd compactDef) bool {
> ```

Pls add doc what does the result mean

---

*[badger/compaction.go, line 154 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-Klbulboi-8EjuEFgT7k:-Klbulboi-8EjuEFgT7l:b-ium7dl) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/compaction.go#L154)):*
> ```Go
> 	thisLevel.delSize += cd.thisSize
> 
> 	fmt.Printf("======> compace and add. this level: %s next level: %s\n", thisLevel.debug(), nextLevel.debug())
> ```

s/compace/compact

---

*[badger/kv.go, line 706 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-KlbvkqKv7qzHnrp3eOO:-KlbvkqL2Diyk2ZWXwvv:bp3ga3q) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/kv.go#L706)):*
> ```Go
> 		err = writeLevel0Table(ft.mt, fd)
> 		if err != nil {
> 			fmt.Printf("ERROR while writing to level 0: %v", err)
> ```

shouldn't we use y.Wrapf?

---

*[badger/kv.go, line 714 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-KlbvnWBk41ecixCQL1G:-KlbvnWBk41ecixCQL1H:bji28bi) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/kv.go#L714)):*
> ```Go
> 
> 		if err != nil {
> 			fmt.Printf("ERROR while opening table: %v", err)
> ```

and here

---

*[badger/levels.go, line 36 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-Klc-56ksk73cPU8lm24:-Klc-56ksk73cPU8lm25:b-uurz88) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/levels.go#L36)):*
> ```Go
> type levelsController struct {
> 	// Guards beingCompacted.
> 	sync.Mutex
> ```

do we need this Mutex anymore then?

---

*[badger/levels.go, line 328 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-Klc_2fiPUh7AqtyVriX:-Klc_2fjFHXRRoScsasd:bwcu2kv) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/levels.go#L328)):*
> ```Go
> }
> 
> func (s *levelsController) fillTablesL0(cd *compactDef) bool {
> ```

can you explain what result is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/55)*

**Comment by szymonm** [comment]
Reviewed 6 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/55)*

**Comment by manishrjain** [comment]
Review status: 1 of 12 files reviewed at latest revision, 8 unresolved discussions.

---

*[badger/compaction.go, line 71 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-KlbnBVJpn7GUZ8hLVXW:-Klvsm2scI--EPhaLusm:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/compaction.go#L71)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

you can use r.String() instead of Sprintf
</blockquote></details>

Done.

---

*[badger/compaction.go, line 85 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-Klbp1U4Jzyq_RSF4sAI:-Klvt5XWWLVC8WiyKOKq:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/compaction.go#L85)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

According to: https://golang.org/doc/faq#methods_on_values_or_pointers
"If some of the methods of the type must have pointer receivers, the rest should too, so the method set is consistent regardless of how the type is used."
Do we follow it? I'm not convinced to this rule personally, like to have distinction between methods that change reciever and not.
</blockquote></details>

Done.

---

*[badger/compaction.go, line 128 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-KlbqUY3N1C73pHmO7zd:-KlvtX4-7IaE_SoWRObU:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/compaction.go#L128)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

Pls add doc what does the result mean
</blockquote></details>

Done.

---

*[badger/kv.go, line 706 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-KlbvkqKv7qzHnrp3eOO:-Klvtb1mcUj9BROum5bJ:bmtszuf) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/kv.go#L706)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

shouldn't we use y.Wrapf?
</blockquote></details>

No need, I think.

---

*[badger/levels.go, line 36 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/55#-Klc-56ksk73cPU8lm24:-KlvyAoQwz6Q9XoMtCfJ:b-83og3x) ([raw file](https://github.com/dgraph-io/badger/blob/e86865802929e6fc996fb04f3bb8a9995a6b85fe/badger/levels.go#L36)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

do we need this Mutex anymore then?
</blockquote></details>

Nope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/55)*

**Comment by manishrjain** [comment]
Submitted.

**Pull request closed without merging**
