### PR TITLE
Fix valuePointers in LSM after crash.

### LINKED ISSUE #21: Bug: not storing value pointer correctly in LSM tree after crash
After crash we're replaying entries from value log. We are handling only the case when value should be stored in the LSM and omit the case when value is stored as value pointer in the tree.

See: https://github.com/dgraph-io/badger/blob/master/badger/kv.go#L181

### PR DESCRIPTION
**Pull request by szymonm**
Resolves #21

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/25)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[badger/kv.go, line 177 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB1m5-Ldbxuns-uCBL:-KkB1m50ELH6Ps31dYRR:b-76nyah) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/kv.go#L177)):*
> ```Go
> 			nv = make([]byte, 16)
> 			vp.Encode(nv)
> 			meta = meta | BitValuePointer // BitValuePointer is 0 since valueLog does not know it.
> ```

This comment is confusing. No need for it.

---

*[badger/value.go, line 94 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB1stV_txelqP4oQG4:-KkB1stV_txelqP4oQG5:b-v7bqxd) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/value.go#L94)):*
> ```Go
> 
> // iterate iterates over log file.
> // valuePointer is the pointer returned when writting entry to disk. It may not
> ```

writing. And there are other grammar mistakes. Can you run them through Grammarly?

"It may not be the last vp for entry key that is ...": What is this comment for?

---

*[badger/value.go, line 156 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB3rzsgOnnA7LbV6mp:-KkB3rzsgOnnA7LbV6mq:b-xd8qom) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/value.go#L156)):*
> ```Go
> 
> 			recordOffset += int64(hlen + vl)
> 			vp.Len = uint32(len(hbuf)) + h.vlen
> ```

Mention that h.vlen is sufficient, because the value is compressed and contains the key.

---

*[badger/value.go, line 715 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB2ovurL_73mqOI5ms:-KkB2ovurL_73mqOI5mt:b-qxsqmg) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/value.go#L715)):*
> ```Go
> 	start := time.Now()
> 	y.AssertTrue(vlog.kv != nil)
> 	err := lf.iterate(0, func(e Entry, vpVL valuePointer) bool {
> ```

s/vpVL/vp

---

*[badger/value.go, line 735 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB2w4XqZqfOhqyKXGb:-KkB2w4XqZqfOhqyKXGc:b-e8ex2o) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/value.go#L735)):*
> ```Go
> 
> 		vs := vlog.kv.get(e.Key)
> 		// TODO: can vs be nil if GC is run before replay after crash?
> ```

GC shouldn't be run before replay. In fact, you could modify the NewKV function to ensure that.

---

*[table/table.go, line 254 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB3Gt6M7nz3vkQBtdS:-KkB3Gt6M7nz3vkQBtdT:b-1ex4r) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/table/table.go#L254)):*
> ```Go
> 
> 			h.Decode(buf)
> 			y.AssertTruef(h.plen == 0, "Block index: %d, Key offset: %+v, h.plen = %d", i, *ko, h.plen)
> ```

100 chars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/25)*

**Comment by szymonm** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[badger/kv.go, line 177 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB1m5-Ldbxuns-uCBL:-KkCNo2q9RW_P5pXQN5r:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/kv.go#L177)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This comment is confusing. No need for it.
</blockquote></details>

Done.

---

*[badger/value.go, line 94 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB1stV_txelqP4oQG4:-KkCNz0_qv6IkFwcDPE3:b21z61u) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/value.go#L94)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

writing. And there are other grammar mistakes. Can you run them through Grammarly?

"It may not be the last vp for entry key that is ...": What is this comment for?
</blockquote></details>

My point here was that: when iterating over entries and their valuePointers in valueLog, valuePointers are retrieved from the data written on disk (valueLog). ValueLog does not guarantee that they are consistent with the current valuePointers in the LSM tree.

---

*[badger/value.go, line 156 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB3rzsgOnnA7LbV6mp:-KkCQhTV-jjU73s7koij:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/value.go#L156)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Mention that h.vlen is sufficient, because the value is compressed and contains the key.
</blockquote></details>

Done.

---

*[badger/value.go, line 715 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB2ovurL_73mqOI5ms:-KkCQpTAhp6rZ_WrjKcK:b-23x0wi) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/value.go#L715)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

s/vpVL/vp
</blockquote></details>

In this function we have two valuePointers actually - one that is retrieved from valueLog (I called it vpVL) and the other retrieved from the LSM tree.

Shall I call both of them just vp?

---

*[badger/value.go, line 735 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB2w4XqZqfOhqyKXGb:-KkCSR3AKI0XfhvvTBZo:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/value.go#L735)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

GC shouldn't be run before replay. In fact, you could modify the NewKV function to ensure that.
</blockquote></details>

Done.

---

*[table/table.go, line 254 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB3Gt6M7nz3vkQBtdS:-KkCVtAXm1Xzc3WK4Lxe:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/table/table.go#L254)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/25)*

**Comment by manishrjain** [comment]
:lgtm: Please address comments.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[badger/value.go, line 94 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB1stV_txelqP4oQG4:-KkESFC2jI32Vew2fbfw:bp1p79d) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/value.go#L94)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

My point here was that: when iterating over entries and their valuePointers in valueLog, valuePointers are retrieved from the data written on disk (valueLog). ValueLog does not guarantee that they are consistent with the current valuePointers in the LSM tree.
</blockquote></details>

Why is there no guarantee?

---

*[badger/value.go, line 715 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkB2ovurL_73mqOI5ms:-KkESLDVvwxypiBqCRuk:b-eeq140) ([raw file](https://github.com/dgraph-io/badger/blob/0b8fe7184c19db06257ed34b7847bbe7d32171a5/badger/value.go#L715)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

In this function we have two valuePointers actually - one that is retrieved from valueLog (I called it vpVL) and the other retrieved from the LSM tree.

Shall I call both of them just vp?
</blockquote></details>

I think the VL upper case suffix isn't good naming.

---

*[badger/value.go, line 716 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/25#-KkESgRUmrx16G0-Kl6u:-KkESgRUmrx16G0-Kl6v:bb7qla5) ([raw file](https://github.com/dgraph-io/badger/blob/d11eb5ea63203a73af2bab16ecc34b7fbd198915/badger/value.go#L716)):*
> ```Go
> 	start := time.Now()
> 	y.AssertTrue(vlog.kv != nil)
> 	err := lf.iterate(0, func(e Entry, vp valuePointer) bool {
> ```

vptr

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/25#-:-KkEU4PYKGS_s7bv-vlX:br54bc7)*

**Comment by szymonm** [comment]
Merged manually.

**Pull request closed without merging**
