### PR TITLE
enlarge maxValueThreshold

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs520 <crazycs520@gmail.com>

Related question: https://discuss.dgraph.io/t/question-about-maxvaluethreshold-and-the-compression/15631/2

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1754)

### CODE REVIEW

**Comment by crazycs520** [comment]
@NamanJain8 PTAL

**Comment by faddat** [comment]
aw

This one doesn't look bad at all.  Why not make it a variable instead of a constant?  I assume there is a reason?

**Review by faddat — COMMENTED** [review]
I really do like this one.  Any reason it was not merged?

**Comment by faddat** [comment]
PTAL

**Pull request closed without merging**
