### PR TITLE
Make value log garbage collection more intelligent.

### PR DESCRIPTION
**Pull request by deepakjois**
We now keep track of the number of deletions happening in every
log file, and use that to pick a good candidate for garbage collection.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/285)

### CODE REVIEW

**Comment by deepakjois** [comment]
There are some pending TODO items, but I wanted to get some feedback on this approach before addressing them.

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[db.go, line 870 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxBmKrUwuNRa-QgAfVA:-KxBmKrUwuNRa-QgAfVB:by8by2t) ([raw file](https://github.com/dgraph-io/badger/blob/4a3c2e926fab0440f6aba3348f8cc8bf24caed34/db.go#L870)):*
> ```Go
> 
> // TODO make this threadsafe
> var gcStats = make(map[uint32]int)
> ```

This can be part of the DB itself, instead of a global thing.

---

*[db.go, line 877 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxBmeP7fmh6ttHkfYJK:-KxBmeP7fmh6ttHkfYJL:ba3wmp2) ([raw file](https://github.com/dgraph-io/badger/blob/4a3c2e926fab0440f6aba3348f8cc8bf24caed34/db.go#L877)):*
> ```Go
> 	if len(ptr) > 0 {
> 		vptr.Decode(ptr)
> 		gcStats[vptr.Fid]++
> ```

You also need the estimated size of the key-value pair. Better to pass in the item itself.

---

*[value.go, line 826 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxBn0EIyAS8XeMX44LX:-KxBn0EIyAS8XeMX44LY:b-p4fe95) ([raw file](https://github.com/dgraph-io/badger/blob/4a3c2e926fab0440f6aba3348f8cc8bf24caed34/value.go#L826)):*
> ```Go
> 	for j := 0; j < i; j++ {
> 		// TODO acquire mutex before accessing map
> 		if stats[fids[j]] > candidate.count {
> ```

stats[fids[j]] looks weird. Instead iterate over the stats map, and just ignore the fids >= i.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/285)*

**Comment by deepakjois** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[db.go, line 870 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxBmKrUwuNRa-QgAfVA:-KxC6_43QXgFKya_G2E7:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/4a3c2e926fab0440f6aba3348f8cc8bf24caed34/db.go#L870)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This can be part of the DB itself, instead of a global thing.
</blockquote></details>

Done.

---

*[db.go, line 877 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxBmeP7fmh6ttHkfYJK:-KxC6_lWU0lEWEVdx5OS:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/4a3c2e926fab0440f6aba3348f8cc8bf24caed34/db.go#L877)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You also need the estimated size of the key-value pair. Better to pass in the item itself.
</blockquote></details>

Done.

---

*[value.go, line 826 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxBn0EIyAS8XeMX44LX:-KxC6ao4v5A1CQ32U86P:b-of0rif) ([raw file](https://github.com/dgraph-io/badger/blob/4a3c2e926fab0440f6aba3348f8cc8bf24caed34/value.go#L826)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

stats[fids[j]] looks weird. Instead iterate over the stats map, and just ignore the fids >= i.
</blockquote></details>

The problem with iterating over stats is that it may contain fids that may have been deleted. I will clean up the code by assigning the inner filed to another variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/285)*

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[db.go, line 85 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCLvIE4lzUbyworPLm:-KxCLvIE4lzUbyworPLn:b-ewm9q8) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/db.go#L85)):*
> ```Go
> 	orc *oracle
> 
> 	gcStats *gcStats
> ```

Shouldn't this belong to value log? And then it can use it internally.

---

*[db.go, line 877 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCM16EfuLAJcDTJo2l:-KxCM16EfuLAJcDTJo2m:b1akbw2) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/db.go#L877)):*
> ```Go
> }
> 
> func (db *DB) updateGCStats(item *Item) {
> ```

This func should probably belong to value log. It should track GC stats.

---

*[db.go, line 882 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCJu07XkmSawPN4l_z:-KxCJu07XkmSawPN4la-:bg6em3b) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/db.go#L882)):*
> ```Go
> 		vp.Decode(item.vptr)
> 		db.gcStats.Lock()
> 		db.gcStats.m[vp.Fid] += item.EstimatedSize()
> ```

No need to call EstimatedSize, now that you're parsing vp anyway. Just call int64(vp.Len), which is what EstimatedSize does internally in this particular case.

---

*[db.go, line 1035 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCM6BgC9pZc97Ash5D:-KxCM6BgC9pZc97Ash5E:b-i4xyqx) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/db.go#L1035)):*
> ```Go
> 
> 	// Pick a log file for GC
> 	lf := db.vlog.pickLog(head, db.gcStats)
> ```

If value log tracks gc stats, we won't need to pass it in.

---

*[value.go, line 822 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCMLwFeTNOcwRboNbq:-KxCMLwFeTNOcwRboNbr:b-qp51iy) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/value.go#L822)):*
> ```Go
> 	candidate := struct {
> 		fid   uint32
> 		count int64
> ```

discard int64

---

*[value.go, line 834 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCMSa6YQsjVBiiK3lm:-KxCMSa6YQsjVBiiK3ln:bmrh26k) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/value.go#L834)):*
> ```Go
> 	}
> 
> 	if candidate.count != math.MaxUint32 { // Found a candidate
> ```

if candidate.Fid != math.MaxUint32. In fact, this should fail compilation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/285)*

**Comment by deepakjois** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[db.go, line 85 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCLvIE4lzUbyworPLm:-KxCPjNIp-flY1Jky6cD:b-hxtt7e) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/db.go#L85)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Shouldn't this belong to value log? And then it can use it internally.
</blockquote></details>

Done. But we will still need to use it in this file as `db.vlog` when recording discards

---

*[db.go, line 877 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCM16EfuLAJcDTJo2l:-KxCPi5rXwxVSONUGGlg:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/db.go#L877)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This func should probably belong to value log. It should track GC stats.
</blockquote></details>

Done.

---

*[db.go, line 882 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCJu07XkmSawPN4l_z:-KxCQCVGL1ExWOQx9Ucp:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/db.go#L882)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to call EstimatedSize, now that you're parsing vp anyway. Just call int64(vp.Len), which is what EstimatedSize does internally in this particular case.
</blockquote></details>

Done.

---

*[db.go, line 1035 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCM6BgC9pZc97Ash5D:-KxCQE-aOboqKQMk3ajD:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/db.go#L1035)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If value log tracks gc stats, we won't need to pass it in.
</blockquote></details>

Done.

---

*[value.go, line 822 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCMLwFeTNOcwRboNbq:-KxCQRSdemfueG-yp3X5:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/value.go#L822)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

discard int64
</blockquote></details>

Done.

---

*[value.go, line 834 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCMSa6YQsjVBiiK3lm:-KxCQRwt2x9QS0WiBOUh:b-qighbv) ([raw file](https://github.com/dgraph-io/badger/blob/32617f29dbfb0ae6817a50929e0574dddd55233c/value.go#L834)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if candidate.Fid != math.MaxUint32. In fact, this should fail compilation.
</blockquote></details>

For some reason it did not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/285)*

**Comment by manishrjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[value.go, line 832 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCsX8GAXSMM5izL61r:-KxCsX8GAXSMM5izL61s:b-ie6qiy) ([raw file](https://github.com/dgraph-io/badger/blob/d2710c809f7fde037937bd0521ea8b681380623f/value.go#L832)):*
> ```Go
> 	for j := 0; j < i; j++ {
> 		fid := fids[j]
> 		vlog.gcStats.Lock()
> ```

Instead of locking and unlocking inside the loop repeatedly, you can do this outside once.

---

*[value.go, line 988 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCsr2eJS0wmwobu83P:-KxCsr2eJS0wmwobu83Q:bxbb7j9) ([raw file](https://github.com/dgraph-io/badger/blob/d2710c809f7fde037937bd0521ea8b681380623f/value.go#L988)):*
> ```Go
> 		lf := vlog.pickLog(head)
> 		if lf == nil {
> 			return ErrNoRewrite
> ```

can't return here. In fact, this logic could just be pushed down to doRunGC.

---

*[value.go, line 994 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCt6lz-9MuJgCu9ESe:-KxCt6lz-9MuJgCu9ESf:b-3xcai3) ([raw file](https://github.com/dgraph-io/badger/blob/d2710c809f7fde037937bd0521ea8b681380623f/value.go#L994)):*
> ```Go
> 		err := vlog.doRunGC(gcThreshold, lf)
> 		<-vlog.garbageCh
> 		if err != nil {
> ```

if err == nil?

---

*[value.go, line 996 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCt83Sj9qsgcfdYtV4:-KxCt83Sj9qsgcfdYtV5:bhzlfyp) ([raw file](https://github.com/dgraph-io/badger/blob/d2710c809f7fde037937bd0521ea8b681380623f/value.go#L996)):*
> ```Go
> 		if err != nil {
> 			vlog.gcStats.Lock()
> 			vlog.gcStats.m[lf.fid] = 0
> ```

delete lf.fid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/285)*

**Comment by manishrjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[value.go, line 433 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCtRkg5-wR9SWQKOsC:-KxCtRkg5-wR9SWQKOsD:b-mst29p) ([raw file](https://github.com/dgraph-io/badger/blob/d2710c809f7fde037937bd0521ea8b681380623f/value.go#L433)):*
> ```Go
> type gcStats struct {
> 	sync.Mutex
> 	m map[uint32]int64
> ```

gcStats.m doesn't tell anything about what this holds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/285)*

**Comment by deepakjois** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[value.go, line 433 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCtRkg5-wR9SWQKOsC:-KxD-EXKHWG_Za50OS6L:b-6o4jgw) ([raw file](https://github.com/dgraph-io/badger/blob/d2710c809f7fde037937bd0521ea8b681380623f/value.go#L433)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

gcStats.m doesn't tell anything about what this holds.
</blockquote></details>

renamed the struct and the field to lfDiscardStats, and added a comment.

---

*[value.go, line 832 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCsX8GAXSMM5izL61r:-KxCvXA2sCRiZg-z1v5U:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/d2710c809f7fde037937bd0521ea8b681380623f/value.go#L832)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Instead of locking and unlocking inside the loop repeatedly, you can do this outside once.
</blockquote></details>

Done.

---

*[value.go, line 988 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCsr2eJS0wmwobu83P:-KxCxD5XTda3aKIIe8Yh:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/d2710c809f7fde037937bd0521ea8b681380623f/value.go#L988)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

can't return here. In fact, this logic could just be pushed down to doRunGC.
</blockquote></details>

Done.

---

*[value.go, line 994 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCt6lz-9MuJgCu9ESe:-KxCxDg9RqBFmG9oI0H9:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/d2710c809f7fde037937bd0521ea8b681380623f/value.go#L994)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if err == nil?
</blockquote></details>

Done.

---

*[value.go, line 996 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/285#-KxCt83Sj9qsgcfdYtV4:-KxCxE9jgOt0scQ782bs:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/d2710c809f7fde037937bd0521ea8b681380623f/value.go#L996)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

delete lf.fid.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/285)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/285#-:-KxF0VHzg9PhtouyzM7p:bnfp4nl)*

**Comment by deepakjois** [comment]
Merged, with a small addition to the test to check that the stats get recorded on purge.

**Pull request merged**
