### PR TITLE
Misc. doc updates

### PR DESCRIPTION
**Pull request by deepakjois**
* Overhauled the README, inspired by Bolt README.
* Clarifications to several godoc comments.
* Add a couple of examples

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/259)

### CODE REVIEW

**Comment by deepakjois** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[db_test.go, line 879 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-KvzbW7Sr1F6t799bc9x:-KvzbW7Sr1F6t799bc9y:bn6dmv5) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/db_test.go#L879)):*
> ```Go
> 	}
> 
> 	txn := db.NewTransaction(true) // Read-write txn
> ```

This part could be changed to use the newly added `DB.Update()` method

---

*[db_test.go, line 932 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-KvzbbEFWyl38TGt4QyX:-KvzbbEFWyl38TGt4QyY:bn6dmv5) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/db_test.go#L932)):*
> ```Go
> 	}
> 
> 	txn := db.NewTransaction(true)
> ```

This part could be changed to use the newly added `DB.Update()` method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/259)*

**Comment by manishrjain** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 167 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1VBudHeuTGFFOClwW:-Kw1VBueJ0fP7Sdmzgty:bguha95) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L167)):*
> ```Markdown
> 
> ```go
> db.Update(func(txn *badger.Txn) error {
> ```

This also returns error which needs to be handled.

---

*[README.md, line 177 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1VKqm_jFB8kX3zcW3:-Kw1VKqm_jFB8kX3zcW4:b-qrq5oq) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L177)):*
> ```Markdown
> 
> ```go
> db.View(func(txn *badger.Txn) error {
> ```

Error returned here too.

---

*[README.md, line 226 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1W7lsW88DwtSq1XBD:-Kw1W7ltJUk3xlaF6mZz:b-whciiz) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L226)):*
> ```Markdown
> 
> By default, Badger prefetches the values of the next 100 items. You can adjust
> that with the `IteratorOptions.PrefetchSize` field. You can also turn off the
> ```

though setting it to a value higher than GOMAXPROCS (which we recommend to be 128 or higher) shouldn't give any more benefits in iteration speed.

---

*[README.md, line 258 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1WbORG4UdU-eJnpGK:-Kw1WbOSeeLtcZAxpJ1_:b-qd0s1b) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L258)):*
> ```Markdown
> 
> ```go
> db.View(func(txn *.Tx) error {
> ```

Error handling here?

---

*[README.md, line 271 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1Wfum1M0J5FKHoU68:-Kw1Wfum1M0J5FKHoU69:b-ftnxqi) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L271)):*
> ```Markdown
> ```
> 
> ### Database backups
> ```

Plural?

---

*[README.md, line 331 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1XFt7a2IRHPS-v-vj:-Kw1XFt7a2IRHPS-v-vk:b-z11egq) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L331)):*
> ```Markdown
> 
> ### Benchmarks
> ```

No more benchmark graphs?

---

*[transaction.go, line 315 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1XX3rK8rq8pRX2bi7:-Kw1XX3rK8rq8pRX2bi8:boa9ygf) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/transaction.go#L315)):*
> ```Go
> //
> // 5. If callback is provided, method will return as soon as Badger has checked
> // for conflicts. Writes to database will happen in the background, and the
> ```

for conflicts (which could error out, in which case callback isn't run).

Better to break this up into multiple sentences to explain the flow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/259)*

**Comment by deepakjois** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 167 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1VBudHeuTGFFOClwW:-Kw35TG-NXLdm70D06vP:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L167)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This also returns error which needs to be handled.
</blockquote></details>

Done.

---

*[README.md, line 177 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1VKqm_jFB8kX3zcW3:-Kw35Jii3JlDj8Pd9YXa:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L177)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Error returned here too.
</blockquote></details>

Done.

---

*[README.md, line 226 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1W7lsW88DwtSq1XBD:-Kw36BkrEfCiO_O2_Nsq:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L226)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

though setting it to a value higher than GOMAXPROCS (which we recommend to be 128 or higher) shouldn't give any more benefits in iteration speed.
</blockquote></details>

Done.

---

*[README.md, line 258 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1WbORG4UdU-eJnpGK:-Kw35IClB89WiRvKJRDE:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L258)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Error handling here?
</blockquote></details>

Done.

---

*[README.md, line 271 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1Wfum1M0J5FKHoU68:-Kw35HXGQFiymJbSJ1g0:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L271)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Plural?
</blockquote></details>

Done.

---

*[README.md, line 331 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1XFt7a2IRHPS-v-vj:-Kw36H5zDnOsxX0ZMf6J:buz9x4v) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/README.md#L331)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No more benchmark graphs?
</blockquote></details>

Looks like I missed this section altogether. I will add some details to this and link to the blog post(s), the badger-bench repo and the benchmarking logs.

However, I think adding benchmarks graphs is not a great idea. First of all, they don’t make a lot of sense w/o the full context. They also take up a lot of vertical space in an already long document. People who genuinely care about benchmarks will probably not mind an additional jump to the actual posts to look up the graphs.

---

*[transaction.go, line 315 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw1XX3rK8rq8pRX2bi7:-Kw39BfWAcKCWCMuupF6:b-rzoglm) ([raw file](https://github.com/dgraph-io/badger/blob/5b75d7fb0b09e98afff61915ef6b3b174191392a/transaction.go#L315)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

for conflicts (which could error out, in which case callback isn't run).

Better to break this up into multiple sentences to explain the flow.
</blockquote></details>

Tried to make the paragraph more clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/259)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[transaction.go, line 318 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/259#-Kw3lx5_po3BM9ZijTRS:-Kw3lx5aq50wk7J3tjeB:b-xcbe1i) ([raw file](https://github.com/dgraph-io/badger/blob/afb3e66537a7f3007f1382f3e668b6f776f2a569/transaction.go#L318)):*
> ```Go
> // If there is a conflict, an error will be returned and the callback will not
> // run. If there are no conflicts, the callback will be called upon successful
> // completion of writes or errors during write.
> ```

or any error during write.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/259#-:-Kw3lzBN-gNM7zP6o5KR:bnfp4nl)*

**Pull request merged**
