### PR TITLE
Fix unsafe usage in Decode

### PR DESCRIPTION
**Pull request by jarifibrahim**
We use unsafe pointers to convert slices to structs. It might be possible that the struct and byte slice are not aligned in the same way.  This PR fixes the alignment issues

The command
```
gotip test -gcflags=all=-d=checkptr
```
no longer complains about unsafe pointer conversion.

The changed implementation is as fast as the existing one.

Fixes https://github.com/dgraph-io/badger/issues/1096

```go                                                                                                                           
// Implicit copy
func (h *header) Decode(buf []byte) int {
	*h = *(*header)(unsafe.Pointer(&buf[0]))
	return h.Size()
}

// Explicit copy
func (h *header) DecodeWithCopy(buf []byte) int {
   copy((*[headerSize]byte)(unsafe.Pointer(h))[:], buf[:headerSize])
   return int(headerSize)    
}    
      
```

```go
var x header
 
func BenchmarkHeader(b *testing.B) {
 h := &header{
     diff:    100,
     overlap: 023,
 }
 
 buf := h.Encode()
 b.ResetTimer()
 b.Run("implicit copy", func(b *testing.B) {
     for i := 0; i < b.N; i++ {
         x.Decode(buf)
     }
 })
 b.Run("explicit copy", func(b *testing.B) {
     for i := 0; i < b.N; i++ {
         x.DecodeWithCopy(buf)
     }
 })
}
```
```
gtf -run ^$ -bench=Header -benchmem
goos: linux
goarch: amd64
pkg: github.com/dgraph-io/badger/v2/table
BenchmarkHeader/implicit_copy-16         	1000000000	         0.602 ns/op
BenchmarkHeader/explicit_copy-16         	1000000000	         0.712 ns/op
PASS
ok  	github.com/dgraph-io/badger/v2/table	1.467s
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1097)

### CODE REVIEW

**Comment by campoy** [comment]
I can confirm this fixes the issue for this test, unfortunately now it fails somewhere else.

```bash
--- FAIL: TestTruncateVlogWithClose (0.06s)
panic: runtime error: unsafe pointer conversion [recovered]
	panic: runtime error: unsafe pointer conversion

goroutine 53572 [running]:
testing.tRunner.func1(0xc0003a3e00)
	/home/francesc/src/github.com/golang/go/src/testing/testing.go:881 +0x3a3
panic(0xa43860, 0xc088c4b760)
	/home/francesc/src/github.com/golang/go/src/runtime/panic.go:679 +0x1b2
github.com/dgraph-io/badger.(*valuePointer).Decode(...)
	/home/francesc/src/github.com/dgraph-io/badger/structs.go:42
github.com/dgraph-io/badger.Open(0xc087f24f80, 0x19, 0xc087f24f80, 0x19, 0x1, 0x2, 0x2, 0x1, 0x100, 0xb5e4c0, ...)
	/home/francesc/src/github.com/dgraph-io/badger/db.go:350 +0x16c5
github.com/dgraph-io/badger.TestTruncateVlogWithClose(0xc0003a3e00)
	/home/francesc/src/github.com/dgraph-io/badger/db2_test.go:72 +0x416
testing.tRunner(0xc0003a3e00, 0xab3c18)
	/home/francesc/src/github.com/golang/go/src/testing/testing.go:916 +0xc9
created by testing.(*T).Run
```

**Comment by jarifibrahim** [comment]
@campoy Both the errors are related. I'm still trying to understand why this fix works. For instance, I expected the code below to complain but it doesn't
```go
type header struct {
	a uint16
	b uint16
}

func (h header) encode() []byte {
	var b [4]byte
	*(*header)(unsafe.Pointer(&b[0])) = h
	return b[:]
}

func (h *header) decode(buf []byte) {
	*h = *(*header)(unsafe.Pointer(&buf[0]))
}

func TestChkptr(t *testing.T) {

	h := header{1, 2}
	b := h.encode()
	var y header
	y.decode(b)

	fmt.Println(h, y)
}

```
The code is exactly similar to one in badger.

**Comment by jarifibrahim** [comment]
@campoy the errors are related. I've fixed them both in this PR.

Do you think we should add the `checkPtr` flag to all our builds?

**Comment by campoy** [comment]
I agree that @mangalaman93's solution seems more efficient (although quite ugly?)

If that one fixes the warnings let's use it and avoid the performance hit.

**Comment by mangalaman93** [comment]
@campoy Such conversions are pretty common in badger as far as I know. Let me know which part of the solution you thought could be improved/avoided.

**Comment by jarifibrahim** [comment]
@mangalaman93 Thank you so much. The patch seems to work :+1:

**Pull request merged**
