### PR TITLE
Handle setifmissing during value log rewrite(gc)

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/194)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/194#-KtEYCzbGBIXgkTTlPE0:-KtEYCzbGBIXgkTTlPE1:b-jxmwdb) ([raw file](https://github.com/dgraph-io/badger/blob/66a84e7b87ea70c48886058e75f6d07deb28935e/value.go#L289)):*
> ```Go
> 			if e.Meta == BitSetIfAbsent {
> 				e.Meta = 0
> 			}
> ```

If bitsetifabsent is set we won't be updating the lsm to point to the new file after gc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/194)*

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[value.go, line 287 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/194#-KtE_m-HfHrQxnjb6OlD:-KtE_m-HfHrQxnjb6OlE:b3g0phf) ([raw file](https://github.com/dgraph-io/badger/blob/66a84e7b87ea70c48886058e75f6d07deb28935e/value.go#L287)):*
> ```Go
> 			// This new entry only contains the key, and a pointer to the value.
> 			ne := new(Entry)
> 			if e.Meta == BitSetIfAbsent {
> ```

For any small change, spend more effort on explaining the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/194)*

**Comment by janardhan1993** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[value.go, line 287 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/194#-KtE_m-HfHrQxnjb6OlD:-KtEbv5rMNQdLg7Vk6gq:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/66a84e7b87ea70c48886058e75f6d07deb28935e/value.go#L287)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

For any small change, spend more effort on explaining the change.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/194)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[value.go, line 289 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/194#-KtEchik6V0nsvNwm-NA:-KtEchik6V0nsvNwm-NB:b-tx4bf4) ([raw file](https://github.com/dgraph-io/badger/blob/38e6deafb026563c06cade215fa01188ab3858f0/value.go#L289)):*
> ```Go
> 			if e.Meta == BitSetIfAbsent {
> 				// If we rewrite this entry without removing BitSetIfAbsent, lsm would see that
> 				// the key is already present and won't update the vptr to the new file.
> ```

is already present, which would be this same entry, and wont' update...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/194#-:-KtEcwIXJqrfi8AX3V8C:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[value.go, line 289 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/194#-KtEchik6V0nsvNwm-NA:-KtEdYJgdzztINfkvXsW:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/38e6deafb026563c06cade215fa01188ab3858f0/value.go#L289)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

is already present, which would be this same entry, and wont' update...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/194)*

**Pull request merged**
