### PR TITLE
Run gc until we encounter non-nil error.

### PR DESCRIPTION
**Pull request by deepakjois**
Earlier we ran the GC only once, relying on the user to call
DB.RunValueLogGC() multiple times.  We now record some discard
statistics to the vlog struct. We can use that information to improve
the GC.

This commit runs the GC multiple times, picking a different log file
each time, until we encounter an error. We expect to stop the GC the
moment we receive a ErrNoRewrite error.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/357)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 1036 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/357#-L0DYQmu-qAu566nQxz7:-L0DYQmu-qAu566nQxz8:blmpsx5) ([raw file](https://github.com/dgraph-io/badger/blob/9e27da577a8ee96497843c33537efcdaca182e0e/value.go#L1036)):*
> ```Go
> 		}
> 		<-vlog.garbageCh
> 		if err == ErrNoRewrite {
> ```

If we had at least one successful GC, we should not return this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/357)*

**Comment by deepakjois** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 1036 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/357#-L0DYQmu-qAu566nQxz7:-L0DbKle2ejqjL8aZ8-l:b-5ub9mp) ([raw file](https://github.com/dgraph-io/badger/blob/9e27da577a8ee96497843c33537efcdaca182e0e/value.go#L1036)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If we had at least one successful GC, we should not return this.
</blockquote></details>

I am not entirely sure what you mean. But I have tweaked this code. I am keeping track of the number of successful GCs. If this `count > 0` then we return nil. If the count is 0, then we return `ErrRewrite`. This does a better job of preserving the previous semantics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/357)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 1036 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/357#-L0DYQmu-qAu566nQxz7:-L0DfKk7YGmPIyxf4gTH:b-85i63v) ([raw file](https://github.com/dgraph-io/badger/blob/9e27da577a8ee96497843c33537efcdaca182e0e/value.go#L1036)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

I am not entirely sure what you mean. But I have tweaked this code. I am keeping track of the number of successful GCs. If this `count > 0` then we return nil. If the count is 0, then we return `ErrRewrite`. This does a better job of preserving the previous semantics.
</blockquote></details>

LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/357#-:-L0DfNr13lT3Lr3ZP3BE:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[value.go, line 1033 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/357#-L0Dg_P3e4e7noIgUH30:-L0Dg_P44JkCyvHl0p0a:b-vjf59o) ([raw file](https://github.com/dgraph-io/badger/blob/26e500f34f0105639ffa12a9ae6a1f816d272ae8/value.go#L1033)):*
> ```Go
> 		)
> 		for {
> 			err = vlog.doRunGC(gcThreshold, head)
> ```

Doing all files at once might increase the disk io depending on when GC is triggered by user. Shouldn't be an issue if user triggers GC periodically instead of waiting for long time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/357#-:-L0Dh3mCPdip01bl8LXv:bnfp4nl)*

**Comment by deepakjois** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 1033 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/357#-L0Dg_P3e4e7noIgUH30:-L0E3c1DciCYjU4urNkn:b-ffx4va) ([raw file](https://github.com/dgraph-io/badger/blob/26e500f34f0105639ffa12a9ae6a1f816d272ae8/value.go#L1033)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Doing all files at once might increase the disk io depending on when GC is triggered by user. Shouldn't be an issue if user triggers GC periodically instead of waiting for long time.
</blockquote></details>

Ok. I will make a note of that in the docs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/357)*

**Pull request merged**
