### PR TITLE
chore(head): Dump all heads keys on open

### PR DESCRIPTION
**Pull request by jarifibrahim**
There have been issues with badger replays and we should dump all the head keys present in badger when opening badger.

Fixes - DGRAPH-2343

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1474)

### CODE REVIEW

**Review by ashish-goswami — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1474)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ashish-goswami, @jarifibrahim, and @manishrjain)

___
*[db.go, line 388 at r1](https://reviewable.io/reviews/dgraph-io/badger/1474#-MFjxd_W-GioKas403Q_:-MFjxd_W-GioKas403Qa:b53ix9u) ([raw file](https://github.com/dgraph-io/badger/blob/29869bc3019cb3cce1f56c85f35003dbd306adc4/db.go#L388)):*
> ```Go
> 	db.showAllHeadKeys()
> 
> 	headKey := y.KeyWithTs(head, math.MaxUint64)
> ```

Can we use head from `db.showAllHeadKeys()` here?
___
*[db.go, line 439 at r1](https://reviewable.io/reviews/dgraph-io/badger/1474#-MFjwz-2DTcjPUoEvqfC:-MFjwz-2DTcjPUoEvqfD:b-yt8bhh) ([raw file](https://github.com/dgraph-io/badger/blob/29869bc3019cb3cce1f56c85f35003dbd306adc4/db.go#L439)):*
> ```Go
> 	txn := Txn{
> 		db:     db,
> 		readTs: math.MaxUint32, // Show all versions.
> ```

math.MaxUint64
___
*[db.go, line 455 at r1](https://reviewable.io/reviews/dgraph-io/badger/1474#-MFjxPfe1Bkb_XqmXQCR:-MFjxPfe1Bkb_XqmXQCS:b-cl2kos) ([raw file](https://github.com/dgraph-io/badger/blob/29869bc3019cb3cce1f56c85f35003dbd306adc4/db.go#L455)):*
> ```Go
> 	db.opt.Infof("Found the following head pointers")
> 	for ; it.Valid(); it.Next() {
> 		i := it.Item()
> ```

would be good to call it item
`item := it.Item()`

**Review by jarifibrahim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1474)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ashish-goswami and @manishrjain)

___
*[db.go, line 388 at r1](https://reviewable.io/reviews/dgraph-io/badger/1474#-MFjxd_W-GioKas403Q_:-MFjyclN8IByUcc0qtIh:bcjorl3) ([raw file](https://github.com/dgraph-io/badger/blob/29869bc3019cb3cce1f56c85f35003dbd306adc4/db.go#L388)):*
<details><summary><i>Previously, ashish-goswami (Ashish Goswami) wrote…</i></summary><blockquote>

Can we use head from `db.showAllHeadKeys()` here?
</blockquote></details>

We can. I've made the changes.
___
*[db.go, line 439 at r1](https://reviewable.io/reviews/dgraph-io/badger/1474#-MFjwz-2DTcjPUoEvqfC:-MFk13dSDCXUHqM25UGF:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/29869bc3019cb3cce1f56c85f35003dbd306adc4/db.go#L439)):*
<details><summary><i>Previously, ashish-goswami (Ashish Goswami) wrote…</i></summary><blockquote>

math.MaxUint64
</blockquote></details>

Done.
___
*[db.go, line 455 at r1](https://reviewable.io/reviews/dgraph-io/badger/1474#-MFjxPfe1Bkb_XqmXQCR:-MFk14Te1jsn1BMdmynN:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/29869bc3019cb3cce1f56c85f35003dbd306adc4/db.go#L455)):*
<details><summary><i>Previously, ashish-goswami (Ashish Goswami) wrote…</i></summary><blockquote>

would be good to call it item
`item := it.Item()`
</blockquote></details>

Done.

**Review by ashish-goswami — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1474#-:-MGhjHYK0McoNvMAeDA4:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @ashish-goswami, @jarifibrahim, and @manishrjain)

___
*[db.go, line 461 at r2](https://reviewable.io/reviews/dgraph-io/badger/1474#-MGhioBi6fDHwNt_0fs8:-MGhioBi6fDHwNt_0fs9:b-jiyywq) ([raw file](https://github.com/dgraph-io/badger/blob/239702bd81ca92c60a372a322f487d343a4ade7c/db.go#L461)):*
> ```Go
> 		// This shouldn't happen.
> 		y.Check(err)
> 		maxVersion = item.Version()
> ```

Comment would be nice saying version will always be in increasing order.

**Review by ashish-goswami — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1474#-:-MGhjMZOAEYdgB7QFCOk:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @ashish-goswami, @jarifibrahim, and @manishrjain)

**Review by ashish-goswami — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1474#-:-MHFpWfh4oxtWuS-VzlX:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @ashish-goswami, @jarifibrahim, and @manishrjain)

**Pull request merged**
