### PR TITLE
Expose size

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Expose size of `vlog` and `sst` files.

2. Make some metrics part of the KV instead of being global.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/137)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[kv.go, line 212 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_JRhbtJ-gHjzTO_4m:-Kq_JRhbtJ-gHjzTO_4n:b-qszi6b) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/kv.go#L212)):*
> ```Go
> 		valueDirGuard: valueDirLockGuard,
> 	}
> 	out.metrics = y.Init(out.elog, opt.Dir, opt.ValueDir)
> ```

y.NewMetrics

---

*[y/metrics.go, line 39 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_MFZs2YYCjNXVEGi_:-Kq_MFZs2YYCjNXVEGia:b-ilh76s) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L39)):*
> ```Go
> )
> 
> type Metrics struct {
> ```

Should lie in the main badger package.

---

*[y/metrics.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_MP40Czjln8lN9lSO:-Kq_MP40Czjln8lN9lSP:b4ib6py) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L58)):*
> ```Go
> 			return err
> 		}
> 		if filepath.Ext(path) == extension {
> ```

Just walk once and count both together.

---

*[y/metrics.go, line 72 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_MUVkpFovlRUFeInG:-Kq_MUVkpFovlRUFeInH:by60rsz) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L72)):*
> ```Go
> func (m *Metrics) updateSize() {
> 	for range m.Ticker.C {
> 		m.lsmSize.Set(m.totalSize(m.dir, ".sst"))
> ```

Do it just after the walk.

---

*[y/metrics.go, line 95 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_Jext3cjI4KfZB0yt:-Kq_JexuuXiow7Ilv-h5:b-1wikl) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L95)):*
> ```Go
> }
> 
> func Init(elog trace.EventLog, dir, valueDir string) Metrics {
> ```

return a pointer.

---

*[y/metrics.go, line 97 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_NSI9ch7BgNeGnL-q:-Kq_NSI9ch7BgNeGnL-r:b7jkb0s) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L97)):*
> ```Go
> func Init(elog trace.EventLog, dir, valueDir string) Metrics {
> 	var m Metrics
> 	m.NumGets = getInt(fmt.Sprintf("badger_%s_gets_total", dir))
> ```

This has to be a label, not part of the variable.

---

*[y/metrics.go, line 102 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_O4TJ8KU_fGIKwH_7:-Kq_O4TJ8KU_fGIKwH_8:b-d66ge0) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L102)):*
> ```Go
> 
> 	m.lsmSize = getInt(fmt.Sprintf("badger_%s_lsm_size", dir))
> 	m.valueLogSize = getInt(fmt.Sprintf("badger_%s_value_log_size", valueDir))
> ```

One identifier per KV.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/137)*

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[kv.go, line 212 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_JRhbtJ-gHjzTO_4m:-KqaiV5A5VQKI-ddCdaN:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/kv.go#L212)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

y.NewMetrics
</blockquote></details>

Done.

---

*[y/metrics.go, line 39 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_MFZs2YYCjNXVEGi_:-Kq_s1e8vYNJ3Sw5OMcv:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L39)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Should lie in the main badger package.
</blockquote></details>

Done.

---

*[y/metrics.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_MP40Czjln8lN9lSO:-Kq_rnSt2t7Ps06RTQjU:b-e67pnp) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L58)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just walk once and count both together.
</blockquote></details>

I can't do that if valueDir != dir. So I do a second walk if thats the case.

---

*[y/metrics.go, line 72 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_MUVkpFovlRUFeInG:-Kq_rv79m8vEmVy0yyin:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L72)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do it just after the walk.
</blockquote></details>

Done.

---

*[y/metrics.go, line 95 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_Jext3cjI4KfZB0yt:-Kq_s-nHXkp61zkvmsyX:bb6un1j) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L95)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

return a pointer.
</blockquote></details>

Done

---

*[y/metrics.go, line 97 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_NSI9ch7BgNeGnL-q:-KqaiyHxxcERCA_YPddz:brbq21y) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L97)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This has to be a label, not part of the variable.
</blockquote></details>

Done https://reviewable.io/reviews/dgraph-io/dgraph/1304#-

---

*[y/metrics.go, line 102 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kq_O4TJ8KU_fGIKwH_7:-Kqais-EMtsnWrmIUFLS:b-tl5cat) ([raw file](https://github.com/dgraph-io/badger/blob/e4fbac8ab026a895d211417e193ee696ba3cef72/y/metrics.go#L102)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

One identifier per KV.
</blockquote></details>

Changed it to a map with key = dir.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/137)*

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[kv.go, line 144 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/137#-KqatLqOajKAkJVJtjKQ:-KqatLqOajKAkJVJtjKR:b-syyt1f) ([raw file](https://github.com/dgraph-io/badger/blob/1368e232092a0ac77535dd42f04ce1a09919e3cf/kv.go#L144)):*
> ```Go
> 	// we use an atomic op.
> 	lastUsedCasCounter uint64
> 	metrics            *metrics
> ```

not required.

---

*[metrics.go, line 30 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kqas_QTKwrhWffSDJ8s:-Kqas_QTKwrhWffSDJ8t:b-l7r00s) ([raw file](https://github.com/dgraph-io/badger/blob/1368e232092a0ac77535dd42f04ce1a09919e3cf/metrics.go#L30)):*
> ```Go
> )
> 
> type metrics struct {
> ```

This struct isn't required. Just one func in kv.

---

*[y/metrics.go, line 45 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/137#-KqatEjnmaGRngbb5lne:-KqatEjnmaGRngbb5lnf:bc8gzii) ([raw file](https://github.com/dgraph-io/badger/blob/1368e232092a0ac77535dd42f04ce1a09919e3cf/y/metrics.go#L45)):*
> ```Go
> 	NumLSMGets = expvar.NewMap("badger_lsm_level_gets_total")
> 	NumLSMBloomHits = expvar.NewMap("badger_lsm_bloom_hits_total")
> 	NumGets = expvar.NewMap("badger_gets_total")
> ```

Just make these Ints.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/137)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[kv.go, line 144 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/137#-KqatLqOajKAkJVJtjKQ:-Kqb29aKDQpNKXE9WxAP:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/1368e232092a0ac77535dd42f04ce1a09919e3cf/kv.go#L144)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

not required.
</blockquote></details>

Done.

---

*[y/metrics.go, line 45 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/137#-KqatEjnmaGRngbb5lne:-Kqb2HZfeK-9sc5pQBhd:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/1368e232092a0ac77535dd42f04ce1a09919e3cf/y/metrics.go#L45)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just make these Ints.
</blockquote></details>

Done.

---

*[metrics.go, line 30 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/137#-Kqas_QTKwrhWffSDJ8s:-Kqb2IFNsk7GvGF-sfYY:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/1368e232092a0ac77535dd42f04ce1a09919e3cf/metrics.go#L30)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This struct isn't required. Just one func in kv.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/137)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/137#-:-KqfNftty78uowgYtpUT:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
