### PR TITLE
Chore/go package

### PR DESCRIPTION
**Pull request by mmeloni**
In order to properly include pb.proto in other .proto files

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1282)

### CODE REVIEW

**Comment by jarifibrahim** [comment]
Hey @mmeloni Thank you so much for the PR. Would this PR fix https://github.com/dgraph-io/badger/issues/1208 ?

**Comment by mmeloni** [comment]
@jarifibrahim I can try to test it. How I should do?

**Comment by jarifibrahim** [comment]
@mmeloni A simple test would be to import badger `v1.6` and  badger `v2.0` in a single go program and try to run it. 

It looks like the issue isn't fixed by your PR. I see the following error on master and your PR
```
panic: proto: duplicate enum registered: pb.ManifestChange_Operation

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(...)
	/home/ibrahim/Projects/go/pkg/mod/github.com/golang/protobuf@v1.3.1/proto/properties.go:459
github.com/dgraph-io/badger/v2/pb.init.0()
	/home/ibrahim/Projects/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.2/pb/pb.pb.go:638 +0x459
exit status 2

```

**Comment by jarifibrahim** [comment]
@mmeloni can you please add some information to the PR description about why this change is necessary? My understanding of protobufs is very limited. Thank you :)

**Comment by mmeloni** [comment]
Sure,
please take a look at https://developers.google.com/protocol-buffers/docs/reference/go-generated#package first.
In my case go_package was needed to correct import badger .proto types in another .proto file.

**Pull request merged**
