### PR TITLE
Proto: Rename dgraph.badger.v2.pb to badgerpb2

### PR DESCRIPTION
**Pull request by jarifibrahim**
This PR renames badger protobuf package from `dgraph.badger.v2.pb` to `badgerpb2`. 
The `pb.pb.go` file has been regenerated using the `pb/gen.sh` script.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1314)

### CODE REVIEW

**Comment by jarifibrahim** [comment]
Build failed with 
```
[11:13:17]build github.com/dgraph-io/badger/v2/badger: cannot load github.com/dgraph-io/badger/v2/pb: module github.com/dgraph-io/badger@latest found (v1.6.1), but does not contain package github.com/dgraph-io/badger/v2/pb
[11:13:17]Process exited with code 1
```
Looking into it.

**Comment by mvdan** [comment]
I'm not sure I agree with this change. Protobuf package names are global and namespaced, so just `badgerdb2` feels wrong. Your Go module is called `github.com/dgraph-io/badger/v2` after all, not `badgerv2`.

**Comment by jarifibrahim** [comment]
Hey @mvdan, We decided to rename the package to a shorter name after discussing it in https://github.com/dgraph-io/dgraph/pull/5216#pullrequestreview-395576281

**Comment by mvdan** [comment]
:shrug: I disagree with all three suggestions for a global namespace. I think you shoud read https://developers.google.com/protocol-buffers/docs/proto3#packages and https://developers.google.com/protocol-buffers/docs/style#packages before making a decision.

**Comment by mvdan** [comment]
I see that dgraph uses an equally non-unique package name, too: `package pb;`

**Comment by jarifibrahim** [comment]
Hey @gja, according to the naming convention mentioned here https://developers.google.com/protocol-buffers/docs/style#packages , the badger protobuf package name should be `dgraph.badger.v2.pb`. What do you think?

**Pull request merged**
