### PR TITLE
Add options to transform backup data back and forth to a different format

### PR DESCRIPTION
**Pull request by martinmr**
In order to support backwards-compatible backups in Dgraph, the data
needs to be stored in some other format than just the raw key and
values. This change introduces the option to set methods to transform
the data to and forth a separate format.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/895)

### CODE REVIEW

**Comment by martinmr** [comment]
Some work is still needed to use the new Options API. I'll do that once that PR is merged. However, the code in backup.go shouldn't change so it can be reviewed now.

**Comment by manishrjain** [comment]
This PR still needed my approval before submission.

**Comment by manishrjain** [comment]
I don't understand why this change exists here. It was something very specific that we needed in Dgraph, which somehow is being pushed all the way into options in Badger. It is not generic enough to be put here.

**Comment by manishrjain** [comment]
As per our discussion, this change would be reverted.

**Comment by martinmr** [comment]
PR to revert the change https://github.com/dgraph-io/badger/pull/900

**Pull request merged**
