### PR TITLE
Add pid.lock file locking in the opt.Dir directory

### PR DESCRIPTION
**Pull request by srh**
Adds a pid.lock file.

Connects to https://github.com/dgraph-io/dgraph/issues/1185

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/103)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[kv.go, line 150 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDsW_P29Pb2g7QnIhN:-KpDsW_P29Pb2g7QnIhO:b-ssdmyj) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L150)):*
> ```Go
> 		}
> 	}
> 	if err := createPidFile(opt.Dir); err != nil {
> ```

call it `acquireLockFile` or `createLockFile`

---

*[kv.go, line 329 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDq_lRR7FcSkKj39sM:-KpDq_lRR7FcSkKj39sN:b-gtdaae) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L329)):*
> ```Go
> 
> const (
> 	pidFileName        = "pid.lock"
> ```

call it `LOCK` (which is what RocksDB calls it). Also, `lockFile` (Name suffix isn't required because we don't have a lockFile as a file pointer).

---

*[kv.go, line 330 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDsy0k_oSGwrhjz0sP:-KpDsy0k_oSGwrhjz0sQ:br6n4w6) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L330)):*
> ```Go
> const (
> 	pidFileName        = "pid.lock"
> 	cannotCreateErrMsg = "cannot create pid lock file"
> ```

No need for this variable. Just put the contents directly in `errors.Wrap(..)`

---

*[kv.go, line 339 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDqiK4DyFmXwEnEh_M:-KpDqiK4DyFmXwEnEh_N:bec4kqm) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L339)):*
> ```Go
> 		return errors.Wrap(err, cannotCreateErrMsg)
> 	}
> 	_, err = fmt.Fprintf(f, "%d\n", os.Getpid())
> ```

ioutil.Write

---

*[kv.go, line 345 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDrng7-R1dTl6KP24g:-KpDrng7-R1dTl6KP24h:b-grj92m) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L345)):*
> ```Go
> 	}
> 	if closeErr != nil {
> 		return errors.Wrap(err, "cannot close pid lock file")
> ```

closeErr

---

*[kv.go, line 352 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDrPBy1i-66Z-i5jOP:-KpDrPBy1i-66Z-i5jOQ:bnwfupy) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L352)):*
> ```Go
> // destroyPidFile removes the pid file.  Don't forget to syncDir after this, to ensure the changes
> // are permanently written to the file system.
> func destroyPidFile(dir string) error {
> ```

This func gets called exactly once. Might as well invoke the logic directly from the caller.

`os.Remove(filepath.Join(dir, pidFileName))`

---

*[kv.go, line 358 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDsH8ss3IhYdAwOfFO:-KpDsH8ss3IhYdAwOfFP:b-sxwy27) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L358)):*
> ```Go
> 
> // When you create or delete a file, you have to ensure the directory entry for the file is synced
> // in order to guarantee the file is visible (if the system crashes).
> ```

Is this the case? Any relevant documentation links would be useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/103)*

**Comment by srh** [comment]
Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[kv.go, line 150 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDsW_P29Pb2g7QnIhN:-KpH1Nt_Na4qpTk_c6XC:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L150)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

call it `acquireLockFile` or `createLockFile`
</blockquote></details>

Done.

---

*[kv.go, line 329 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDq_lRR7FcSkKj39sM:-KpH1OqK1Y1ALiCsBtHN:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L329)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

call it `LOCK` (which is what RocksDB calls it). Also, `lockFile` (Name suffix isn't required because we don't have a lockFile as a file pointer).
</blockquote></details>

Done.

---

*[kv.go, line 330 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDsy0k_oSGwrhjz0sP:-KpH0dCNSrPnBm3j1UmN:bhac6ow) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L330)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this variable. Just put the contents directly in `errors.Wrap(..)`
</blockquote></details>

Okay, then kv_test will have a copy.

---

*[kv.go, line 339 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDqiK4DyFmXwEnEh_M:-KpEUFOQN8XlpDA6NjtW:b-64xz89) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L339)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

ioutil.Write
</blockquote></details>

You mean ioutil.WriteFile?  It's no good because we need to O_EXCL.

---

*[kv.go, line 345 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDrng7-R1dTl6KP24g:-KpH1SmuHJPjpKMLLxB9:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L345)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

closeErr
</blockquote></details>

Done.

---

*[kv.go, line 352 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDrPBy1i-66Z-i5jOP:-KpGxIP_H1oUAPWTcvWI:b-zgorsk) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L352)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This func gets called exactly once. Might as well invoke the logic directly from the caller.

`os.Remove(filepath.Join(dir, pidFileName))`
</blockquote></details>

Reasonable if createLockFile takes the full path directly too.  Done.

---

*[kv.go, line 358 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDsH8ss3IhYdAwOfFO:-KpGxOc9UqoYO5T8Fnii:b-2hx9a8) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L358)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Is this the case? Any relevant documentation links would be useful.
</blockquote></details>

Yes, definitely.  See the man page for fsync.  Also see for example https://github.com/coreos/etcd/issues/6368 .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/103)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[kv.go, line 339 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDqiK4DyFmXwEnEh_M:-KpHDpQJuKqnn6uS4iTH:bl7ihjm) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L339)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

You mean ioutil.WriteFile?  It's no good because we need to O_EXCL.
</blockquote></details>

OK. Actually meant to remove that comment, somehow slipped through.

---

*[kv.go, line 358 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/103#-KpDsH8ss3IhYdAwOfFO:-KpHEOV8G6DVIgSauGF_:bfjckhq) ([raw file](https://github.com/dgraph-io/badger/blob/7232f81de20a716a65fd61b6472862f0fc40718a/kv.go#L358)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

Yes, definitely.  See the man page for fsync.  Also see for example https://github.com/coreos/etcd/issues/6368 .
</blockquote></details>

Can you add this link as a comment here. Because this means, every time we create a new file, we need to do this dir sync? That'd require more work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/103#-:-KpHEYsWFFSP-7x4d4mO:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm: Address the comment before submitting.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/103#-:-KpHEaRj6zrv2xtry3ox:b-2bblxq)*

**Comment by srh** [comment]
In master as of e13ddb2017fff749f856d66448554f8d190668c6.

**Pull request closed without merging**
