### PR TITLE
Avoid leaks of updateSize goroutines

### PR DESCRIPTION
**Pull request by srh**
While debugging badger deadlocks I noticed a lot of extra `updateSize` goroutines floating around.

So I tightened up the cleanup code... a bit.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/191)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm: Nice cleanup!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/191#-:-Ksvy8YenEV-NVKTdO17:b-d43tfz)*

**Comment by srh** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[kv.go, line 148 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/191#-KsvxnxXwREtwxH_hBJU:-KsvxnxXwREtwxH_hBJV:bt2vnri) ([raw file](https://github.com/dgraph-io/badger/blob/ac5706d4bc311cc5d9d655512433be0f6c3f737c/kv.go#L148)):*
> ```Go
> 	// we use an atomic op.
> 	lastUsedCasCounter uint64
> 	metricsTicker      *time.Ticker
> ```

We would want a WaitGroup too to wait for updateSize to finish running  -- so I just used a LevelCloser instead.

---

*[kv.go, line 422 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/191#-Ksvy572FUWmsDEvvbFX:-Ksvy572FUWmsDEvvbFY:b-ad1myb) ([raw file](https://github.com/dgraph-io/badger/blob/ac5706d4bc311cc5d9d655512433be0f6c3f737c/kv.go#L422)):*
> ```Go
> 		return errors.Wrap(err, "KV.Close")
> 	}
> 	s.metricsTicker.Stop()
> ```

Originally I thought I'd put s.metricsTicker into the defer block up top.  But instead let's just make the entirety of Close tolerate errors amidst cleanup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/191)*

**Comment by srh** [comment]
I should add, this doesn't tighten up the error-handling of NewKV.  But when running `go test -race` I got a deadlock, and upon SIGQUIT, I got only one `updateSize` coroutine instead of seeing several left behind by previous tests.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/191#-:-Ksvyf7tBMTkvoWyNhCx:b-jv308e)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[kv.go, line 426 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/191#-Ksvzv1CHJpEA1SSbOWx:-Ksvzv1CHJpEA1SSbOWy:bpshiyt) ([raw file](https://github.com/dgraph-io/badger/blob/3b0e597e442ad0670391fd4a45e8f4b74660c5f7/kv.go#L426)):*
> ```Go
> 	}
> 
> 	return nil
> ```

return err?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/191#-:-Ksw-RZR-jBOG46tR3ro:bnfp4nl)*

**Comment by srh** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[kv.go, line 426 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/191#-Ksvzv1CHJpEA1SSbOWx:-Ksw0h-xNDPP4m16MGyo:b-gpwa1f) ([raw file](https://github.com/dgraph-io/badger/blob/3b0e597e442ad0670391fd4a45e8f4b74660c5f7/kv.go#L426)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

return err?
</blockquote></details>

This is why humanity invented code reviews...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/191)*

**Comment by pawanrawal** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[kv.go, line 426 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/191#-Ksvzv1CHJpEA1SSbOWx:-Ksw1ttJInXpzsqe_wsk:b-j2x3tu) ([raw file](https://github.com/dgraph-io/badger/blob/3b0e597e442ad0670391fd4a45e8f4b74660c5f7/kv.go#L426)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

This is why humanity invented code reviews...
</blockquote></details>

Haha, feels good to catch it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/191)*

**Comment by srh** [comment]
In master as of 3c791c0dc2c72adea1369b69389417f1b70d6f9f.

**Pull request closed without merging**
