### PR TITLE
punch holes for gc

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/391)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[structs.go, line 59 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/391#-L2IqGABwTrojRSyrRNK:-L2IqGABwTrojRSyrRNL:bb6i1nx) ([raw file](https://github.com/dgraph-io/badger/blob/6a26da68dda2eb147c5358386a19966e7e8d4ddb/structs.go#L59)):*
> ```Go
> const (
> 	headerBufSize = 19
> 	magicByte     = 0x01
> ```

0xaa

---

*[value.go, line 217 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/391#-L2IqrTszCFGZwXGGKzJ:-L2IqrTszCFGZwXGGKzK:bczqea9) ([raw file](https://github.com/dgraph-io/badger/blob/6a26da68dda2eb147c5358386a19966e7e8d4ddb/value.go#L217)):*
> ```Go
> 		}
> 
> 		// Skip all zeros
> ```

Explain why this could happen -- about holes, etc.

---

*[value.go, line 358 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/391#-L2IrMZTZvp_3MWmZH58:-L2IrMZTZvp_3MWmZH59:b-orxd68) ([raw file](https://github.com/dgraph-io/badger/blob/6a26da68dda2eb147c5358386a19966e7e8d4ddb/value.go#L358)):*
> ```Go
> 			ne.UserMeta = e.UserMeta
> 			ne.Key = make([]byte, len(e.Key))
> 			copy(ne.Key, e.Key)
> ```

No need to copy. No need to rewrite anything. value.go can become a lot simpler.

---

*[value.go, line 363 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/391#-L2ItxHwLx28gJ79z_I_:-L2ItxHwLx28gJ79z_Ia:bu4bo0n) ([raw file](https://github.com/dgraph-io/badger/blob/6a26da68dda2eb147c5358386a19966e7e8d4ddb/value.go#L363)):*
> ```Go
> 			if holeLen := int64(e.offset - holeStartOffset); holeLen > minHoleLen {
> 				f.lock.Lock()
> 				y.PunchHole(int(f.fd.Fd()), int64(holeStartOffset), holeLen)
> ```

Maybe add a y.Ignore function, which can ignore error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/391#-:-L2IuB5qykPA7RHKKnnx:bnfp4nl)*

**Comment by manishrjain** [comment]
Submit it in v2.0 branch.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/391#-:-L2IuS7K4ltxWWpJ5kiU:b-b9sact)*

**Comment by janardhan1993** [comment]
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[structs.go, line 59 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/391#-L2IqGABwTrojRSyrRNK:-L2IvvuyxDWRronK3U6V:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/6a26da68dda2eb147c5358386a19966e7e8d4ddb/structs.go#L59)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

0xaa
</blockquote></details>

Done.

---

*[value.go, line 217 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/391#-L2IqrTszCFGZwXGGKzJ:-L2IwK7xpwjfHJl3fiHl:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/6a26da68dda2eb147c5358386a19966e7e8d4ddb/value.go#L217)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Explain why this could happen -- about holes, etc.
</blockquote></details>

Done.

---

*[value.go, line 358 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/391#-L2IrMZTZvp_3MWmZH58:-L2IwQ8fSj0xiDaKQB3N:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/6a26da68dda2eb147c5358386a19966e7e8d4ddb/value.go#L358)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to copy. No need to rewrite anything. value.go can become a lot simpler.
</blockquote></details>

Done.

---

*[value.go, line 363 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/391#-L2ItxHwLx28gJ79z_I_:-L2Iwga_U17-G0iIKSup:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/6a26da68dda2eb147c5358386a19966e7e8d4ddb/value.go#L363)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Maybe add a y.Ignore function, which can ignore error.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/391)*

**Comment by janardhan1993** [comment]
Pushed to v2.0-candidate branch

**Pull request closed without merging**
