### PR TITLE
Add support for go-module

### PR DESCRIPTION
**Pull request by thedevsaddam**
Add support for go-module

Updates #758 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/646)

### CODE REVIEW

**Comment by manishrjain** [comment]
I'm not sure how Go modules work. But, is it supposed to be used on libraries?

**Comment by Xuanwo** [comment]
Yes, and I think it's import for libraries to lock vendor's version.

**Comment by Xuanwo** [comment]
So let's get this merged ? And I will add a Makefile for new contributors to get involved easier.

**Comment by srfrog** [comment]
Thanks for submitting this. Although it seems we have some deps that don't make sense. `mousetrap` and too many indirect ones. What were your steps to generate this?

**Comment by PaluMacil** [comment]
This should probably have an issue attached. It's important because starting with Go 1.13 coming in August modules will be the default instead of the GOPATH variable. and all that comes with it. https://blog.golang.org/using-go-modules

**Comment by campoy** [comment]
I just ran `go mod tidy` and saw that some changes appeared from your files.

go.mod

```diff
diff --git a/go.mod b/go.mod
index 566e098..9a67479 100644
--- a/go.mod
+++ b/go.mod
@@ -13,5 +13,6 @@ require (
        github.com/spf13/pflag v1.0.3 // indirect
        github.com/stretchr/testify v1.2.2
        golang.org/x/net v0.0.0-20181217023233-e147a9138326
+       golang.org/x/sync v0.0.0-20190423024810-112230192c58 // indirect
        golang.org/x/sys v0.0.0-20181218192612-074acd46bca6
 )
```


go.sum

```diff
diff --git a/go.sum b/go.sum
index 623af5a..31231b0 100644
--- a/go.sum
+++ b/go.sum
@@ -22,5 +22,7 @@ github.com/stretchr/testify v1.2.2 h1:bSDNvY7ZPG5RlJ8otE/7V6gMiyenm9RtJ7IUVIAoJ1
 github.com/stretchr/testify v1.2.2/go.mod h1:a8OnRcib4nhh0OaRAV+Yts87kKdq0PP7pXfy6kDkUVs=
 golang.org/x/net v0.0.0-20181217023233-e147a9138326 h1:iCzOf0xz39Tstp+Tu/WwyGjUXCk34QhQORRxBeXXTA4=
 golang.org/x/net v0.0.0-20181217023233-e147a9138326/go.mod h1:mL1N/T3taQHkDXs73rZJwtUhF3w3ftmwwsq0BUmARs4=
+golang.org/x/sync v0.0.0-20190423024810-112230192c58 h1:8gQV6CLnAEikrhgkHFbMAEhagSSnXWGV915qUMm9mrU=
+golang.org/x/sync v0.0.0-20190423024810-112230192c58/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
 golang.org/x/sys v0.0.0-20181218192612-074acd46bca6 h1:MXtOG7w2ND9qNCUZSDBGll/SpVIq7ftozR9I8/JGBHY=
 golang.org/x/sys v0.0.0-20181218192612-074acd46bca6/go.mod h1:STP8DvDyc/dI5b8T5hshtkjS+E42TnysNCUPdjciGhY=
```

Could you update?
Thanks

**Comment by campoy** [comment]
Will merge soon, waiting for a question to be resolved on golang-nuts

https://groups.google.com/forum/#!topic/golang-nuts/Ik251Qzgpl0

**Pull request merged**
