### PR TITLE
Fix bug while picking value log file

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/365)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 846 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/365#-L0gY5pswsvHIxzCszv6:-L0gY5ptCS88M1GYp5Aa:bl7jtau) ([raw file](https://github.com/dgraph-io/badger/blob/ce2168f7a30ca3cc71463b08b18d6a21db72c76e/value.go#L846)):*
> ```Go
> 
> 	i := sort.Search(len(fids), func(i int) bool {
> 		return fids[i] >= head.Fid
> ```

Search uses binary search to find and return the smallest index i in [0, n) at which f(i) is true, assuming that on the range [0, n), f(i) == true implies f(i+1) == true. That is, Search requires that f is false for some (possibly empty) prefix of the input range [0, n) and then true for the (possibly empty) remainder;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/365)*

**Comment by janardhan1993** [comment]
What should be the behaviour of iterator with AllVersions ? Say we write key at version1 and then delete at version 2, now if we use iterator with all versions it gives only key at version 1. 
This is affecting the purge, since purgeolderversions sees only one version of key it doesn't delete it.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/365#-:-L0gYkCkKiA_M2gqZxDg:buvu7yo)*

**Comment by manishrjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[value.go, line 846 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/365#-L0gY5pswsvHIxzCszv6:-L0gb7xkw9fiAMVu1JYw:b-nplzaa) ([raw file](https://github.com/dgraph-io/badger/blob/ce2168f7a30ca3cc71463b08b18d6a21db72c76e/value.go#L846)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Search uses binary search to find and return the smallest index i in [0, n) at which f(i) is true, assuming that on the range [0, n), f(i) == true implies f(i+1) == true. That is, Search requires that f is false for some (possibly empty) prefix of the input range [0, n) and then true for the (possibly empty) remainder;
</blockquote></details>

Let's rewrite this logic. The idea is to find a value log which is < head.fid, and contains the largest amount of discardable data.

We can merge both, and do them as one step. Actually, I'm not sure if we still need the sort.Search anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/365)*

**Comment by janardhan1993** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[value.go, line 846 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/365#-L0gY5pswsvHIxzCszv6:-L0hTeTMla6-fA0CAVEY:b-u4tko) ([raw file](https://github.com/dgraph-io/badger/blob/ce2168f7a30ca3cc71463b08b18d6a21db72c76e/value.go#L846)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Let's rewrite this logic. The idea is to find a value log which is < head.fid, and contains the largest amount of discardable data.

We can merge both, and do them as one step. Actually, I'm not sure if we still need the sort.Search anymore.
</blockquote></details>

in case of fallback we choose a file randomly below head. Then we would need this search.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/365)*

**Comment by manishrjain** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[value.go, line 846 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/365#-L0gY5pswsvHIxzCszv6:-L0hUn4Cbti3v_MFFyFR:b-hu450r) ([raw file](https://github.com/dgraph-io/badger/blob/ce2168f7a30ca3cc71463b08b18d6a21db72c76e/value.go#L846)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

in case of fallback we choose a file randomly below head. Then we would need this search.
</blockquote></details>

Iterate over all, pick the first one. Still no need for this confusing search. Simplify until can't anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/365)*

**Comment by janardhan1993** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 846 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/365#-L0gY5pswsvHIxzCszv6:-L0hYdEsNZ_K_-e7DJam:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/ce2168f7a30ca3cc71463b08b18d6a21db72c76e/value.go#L846)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Iterate over all, pick the first one. Still no need for this confusing search. Simplify until can't anymore.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/365)*

**Comment by deepakjois** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/365#-:-L0ha0xOWqOaZEepSDOW:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/365#-:-L0hdd8YtPLJ5TFYINrk:bnfp4nl)*

**Pull request merged**
