### PR TITLE
Make sure to call txn.Discard in tests

### PR DESCRIPTION
**Pull request by hnakamur**
As it is said so in the doc of NewTransaction()

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/273)

### CODE REVIEW

**Comment by manishrjain** [comment]
Commit calls Discard internally, so Discard isn't required if Commit is called.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[transaction_test.go, line 74 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/273#-KwXJAFY3q6mz9f2_zc_:-KwXJAFY3q6mz9f2_zca:b1cywy1) ([raw file](https://github.com/dgraph-io/badger/blob/c7ad6e7f8af43589e9da716befb70a3ede68acd0/transaction_test.go#L74)):*
> ```Go
> 		require.Equal(t, uint64(i), kv.orc.readTs())
> 
> 		txn.Discard()
> ```

If Commit is called, Discard isn't required to be called as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/273#-:-KwXJOgzSBXcWo37_64v:b-4zowpw)*

**Comment by deepakjois** [comment]
I realised that we do not explicitly clarify that `Txn.Discard()` need not be called if `Txn.Commit()` is being called. I have now added this to the README:

> It is  necessary to call `Txn.Commit()` at the end to commit your transaction. `Txn.Commit()`
internally calls another method `Txn.Discard()` to cleanup the transaction. However, if
your code doesn’t call `Txn.Commit()` for some reason (for e.g it returns prematurely
with an error), then please make sure you call `Txn.Discard()` in a `defer` block.

@hnakamur Could you please modify your code to called `Txn.Discard()` only in cases when `Txn.Commit()` is not being called. It is best if `Txn.Discard` is being called in a `defer` block. Also note that `DB.Update()` and `DB.View()` already do this, so no need to call `Txn.Discard()` there.

**Comment by hnakamur** [comment]
@deepakjois I've updated the PR. Could you take another look? Thanks!

**Comment by deepakjois** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/273#-:-KwhIZckBOXFJLtR6Tqv:bnfp4nl)*

**Pull request merged**
