### PR TITLE
fix all tests caused by https://github.com/dgraph-io/badger/pull/261

### PR DESCRIPTION
**Pull request by kataras**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/264)

### CODE REVIEW

**Comment by peterstace** [comment]
Because `badger` is a library rather than a standalone app, we don't want to commit the vendor directory (that's the responsibility of any projects importing `badger`).

---

Review status: 0 of 831 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/264#-:-Kw7_4nWDKSRL7bf2Wgh:b-63shg8)*

**Comment by kataras** [comment]
No worries @peterstace , the vendor commit was just an optional choice, the first commit is the important here, take its code and fix the library

**Comment by manishrjain** [comment]
Thanks for the fix! Much appreciated. But, you will have to remove all the vendor code, for me to accept this and merge it in.

---

Reviewed 4 of 4 files at r1, 827 of 827 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/264#-:-Kw7y5SaVuqX75Dks2Eq:bf7u2ny)*

**Comment by deepakjois** [comment]
This is now fixed with #266. Sorry @kataras I did not notice this earlier when I made that pull request. Did not mean to step over your contribution.

We can close this now.

**Comment by kataras** [comment]
No problem @deepakjois , that's exactly I said to other guys, just copy-paste the code, nice job! I didn't want to be merged :P

**Pull request closed without merging**
