### PR TITLE
allow users to store usermetadata in lsm

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/123)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/123#-:-KpsgE2Y3STHBjnfsHKb:bnfp4nl)*

**Comment by srh** [comment]
Why is the user metadata one byte?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/123#-:-KpvpC9G2iWs0IKsf8Im:b-6o1pj)*

**Comment by janardhan1993** [comment]
1 byte was sufficient for our use case in dgraph. I should have made it more generic, my bad.
I will change the encoding to store the length of usermetadata along with the metadata, so in case the user is not storing anything we will have only 1 byte overhead per key which should be ok.

**Comment by srh** [comment]
I'm not saying we should make it more generic.  I was wondering the reason.  We could always make it more generic later.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/123#-:-Kpvy3olFlTbfIGsbpY0:b-1wp7nn)*

**Comment by srh** [comment]
But if we did make it more generic, CAS values could use the same feature and storage overhead per CAS would be optional to the user.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/123#-:-KpvyXa41CDhSmeuWgD8:br46g14)*

**Comment by srh** [comment]
Anyway, :lgtm:, we can always make that change separately.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/123#-:-KpvykCArSFXLs7p0JTf:b-pxhezk)*

**Pull request merged**
