### PR TITLE
Merging 2 Pull request (1027 & 1028) into 1 as requested

### PR DESCRIPTION
**Pull request by rebootcode**
Merging 2 Pull request (1027 & 1028) into 1 as requested

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1029)

### CODE REVIEW

**Comment by ashish-goswami** [comment]
Hey @rebootcode, thanks for the PR. Can you create a github issue for this, so that we can understand your requirement more?
I think **ContainForPrefix** is very specific for your use case. You can always write that as part of **for** loop at your end.

**Comment by rebootcode** [comment]
@ashish-goswami - new issue has been created here - https://github.com/dgraph-io/badger/issues/1030 

Please check

**Comment by rebootcode** [comment]
@ashish-goswami - I just found this iteration is pretty slow, the performance difference between ValidForPrefix and ContainForPrefix is huge.

Any idea to improve its performance or use a better function or another way?

**Comment by jarifibrahim** [comment]
The `containsForPrefix` would be slower than `ValidForPrefix` because `bytes.Contains` uses `bytes.Index(..)` https://golang.org/src/bytes/bytes.go?s=26022:26051#L983

**Comment by rebootcode** [comment]
@jarifibrahim - any other alternative option apart from "Contains", `bytes.Index` is slow

**Comment by jarifibrahim** [comment]
> @jarifibrahim - any other alternative option apart from "Contains", `bytes.Index` is slow

No, I don't know of any alternative.

@campoy What do you think about this PR?

@rebootcode Can you please copy the description from your old PR (https://github.com/dgraph-io/badger/pull/1027) and add it to this PR? It's easier to review a PR that has a proper description :)

**Pull request closed without merging**
