### PR TITLE
Fsync directory after creating files

### LINKED ISSUE #104: Directory entries not synced
It seems that we're creating files but not calling fsync() (or in Golang: `.Sync()`) on the directory containing said files.  If we don't do that, a system crash can result in the directory entry (in other words, the file) going missing.

### PR DESCRIPTION
**Pull request by srh**
Fixes #104.

I've assumed that removing files doesn't have the same urgency (I don't know Badger in and out, the assumption here is that starting the store doesn't infer anything from a file's mere existence).

Things might look slightly unfamiliar because it's based on the changes from the other two PR's I've made, #102 and #103.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/105)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[kv.go, line 376 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpHZfzALqXyO3nWG75M:-KpHZfzALqXyO3nWG75N:b5s6gic) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/kv.go#L376)):*
> ```Go
> 
> // Syncs two dirs.
> func syncBothDirs(dir1, dir2 string) error {
> ```

Can't you just open directory with O_DSYNC? That way all creates, deletes etc. would automatically be synced; avoiding code complexity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/105)*

**Comment by srh** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[kv.go, line 376 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpHZfzALqXyO3nWG75M:-KpHu4SdWDr-HdtFSKj8:b-5ae8z4) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/kv.go#L376)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can't you just open directory with O_DSYNC? That way all creates, deletes etc. would automatically be synced; avoiding code complexity.
</blockquote></details>

I don't think that works.  Being opened O_SYNC or O_DSYNC is part of the file descriptor, so you'd need a way to open the file using a directory file descriptor.  You can't do write operations on a directory file descriptor, generally speaking.  (You can only open a directory with O_RDONLY, in fact.)  The system call openat(2) exists, but it's not exposed in Go and anyway, I doubt it has that semantic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/105)*

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[kv.go, line 325 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpIZ7MmTCfoN_Ru9sw2:-KpIZ7MmTCfoN_Ru9sw3:bgxekqi) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/kv.go#L325)):*
> ```Go
> 	// haven't specifically fsynced, are guaranteed to have their directory entry removal
> 	// persisted to disk.
> 	if err := syncBothDirs(s.opt.Dir, s.opt.ValueDir); err != nil {
> ```

Just call sync twice, and avoid the syncBothDirs function. This is not performance critical, and the function adds unnecessary code.

---

*[levels.go, line 315 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpIWj0n4nmc9GBKpjuR:-KpIWj0n4nmc9GBKpjuS:bx1w5m5) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/levels.go#L315)):*
> ```Go
> 	// sync the directory as early as possible for concurrency.)
> 	for x := 0; x < i; x++ {
> 		<-fileCreated
> ```

This isn't required. the `<-che` below is doing the same waiting. You can call syncDir after that.

---

*[levels.go, line 327 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpIX6udeOvvxahuc3bQ:-KpIX6udeOvvxahuc3bR:b-5al4zq) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/levels.go#L327)):*
> ```Go
> 	}
> 
> 	if syncErr != nil && firstErr == nil {
> ```

This can be rewritten:

if firstErr == nil {
  firstErr = syncDir(s.kv.opt.Dir)
}

You anyways only want to call syncDir if firstErr was nil. (no need for syncErr var).

---

*[value.go, line 650 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpIYNvK2FwZA9-3G5Jo:-KpIYNvK2FwZA9-3G5Jp:b-sp8r4g) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/value.go#L650)):*
> ```Go
> 				return errors.Wrapf(err, "While creating new value log: %q", newlf.path)
> 			}
> 			if err := syncDir(l.dirPath); err != nil {
> ```

if l.opt.SyncWrites is false, then do we need to do this?

---

*[value.go, line 653 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpIYD3-MPwsz4PEGDly:-KpIYD3-MPwsz4PEGDlz:b-pg2ge1) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/value.go#L653)):*
> ```Go
> 				return errors.Wrapf(err,
> 					"Could not sync directory entry of value log: %q",
> 					newlf.path)
> ```

can fit in last line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/105)*

**Comment by srh** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[kv.go, line 325 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpIZ7MmTCfoN_Ru9sw2:-KpMKVNYFkNrr0bVliKI:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/kv.go#L325)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just call sync twice, and avoid the syncBothDirs function. This is not performance critical, and the function adds unnecessary code.
</blockquote></details>

Done.

---

*[levels.go, line 315 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpIWj0n4nmc9GBKpjuR:-KpMKXa2qz6KUXRmgFhE:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/levels.go#L315)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This isn't required. the `<-che` below is doing the same waiting. You can call syncDir after that.
</blockquote></details>

Done.

---

*[levels.go, line 327 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpIX6udeOvvxahuc3bQ:-KpMKYlvWrnTc0YxzCuc:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/levels.go#L327)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This can be rewritten:

if firstErr == nil {
  firstErr = syncDir(s.kv.opt.Dir)
}

You anyways only want to call syncDir if firstErr was nil. (no need for syncErr var).
</blockquote></details>

Done.

---

*[value.go, line 650 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpIYNvK2FwZA9-3G5Jo:-KpMFEqQoI9gQrEZ7OMq:b17m51j) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/value.go#L650)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if l.opt.SyncWrites is false, then do we need to do this?
</blockquote></details>

I guess not.  Changing that to call conditionally.  But also, I'll add a syncDir() call to valueLog::sync().

---

*[value.go, line 653 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpIYD3-MPwsz4PEGDly:-KpMGYjz70kXhHCyzQeX:b190o1j) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/value.go#L653)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

can fit in last line.
</blockquote></details>

So for 100 columns, we're basing that on there being 4 spaces per tab?  I was doing 8.  Doing 4 now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/105)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 653 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/105#-KpIYD3-MPwsz4PEGDly:-KpQx5GohP0PrJu5rVRm:b-bmzmxh) ([raw file](https://github.com/dgraph-io/badger/blob/1f5ef796b62fd4060fd9c77d9ddadaf651ecc4d3/value.go#L653)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

So for 100 columns, we're basing that on there being 4 spaces per tab?  I was doing 8.  Doing 4 now.
</blockquote></details>

I think `gofmt` takes care of all that. But, Go doesn't enforce any column size, so we set it to 100 for Dgraph.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/105#-:-KpQxHMeqxsLgRhfv3Af:bnfp4nl)*

**Pull request closed without merging**
