### PR TITLE
Make value log GC pick files before on-disk head pointer.

### LINKED ISSUE #265: Value log GC is picking up files after head pointer
We should only be GCing log files, which fall before the value log head pointer stored on disk in LSM (level 0 and onwards), not memtable. Currently, value log GC doesn't keep track of or use the head pointer at all when making a decision about which log file to pick.

### PR DESCRIPTION
**Pull request by deepakjois**
We should only be GCing log files, which fall before the value log head
pointer stored on disk in LSM (level 0 and onwards), not memtable.

This change introduces an additional argument representing the head
pointer that is passed through into the GC related methods, and then
used to compare and pick a log file in the valueLog.pickLog() method.

Fixes #265.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/279)

### CODE REVIEW

**Comment by deepakjois** [comment]
@manishrjain Still thinking of a good way to test this. If you have any tips, let me know.

**Comment by manishrjain** [comment]
:lgtm: You can turn off compaction, then write a bunch of data, and try to run value log GC. It should do nothing.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 807 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/279#-KwhtBSF-m462tpkofWO:-KwhtBSF-m462tpkofWP:bk41h2b) ([raw file](https://github.com/dgraph-io/badger/blob/4493478c63751df6471a08082cc2b1415854f180/value.go#L807)):*
> ```Go
> 	defer vlog.filesLock.RUnlock()
> 	fids := vlog.sortedFids()
> 	if len(fids) <= 1 || headValPointer.Fid == 0 {
> ```

This cond can be moved to the top, before acquiring lock.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/279#-:-KwhtKB0cSV0odaJE57g:b-di6gwm)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[value.go, line 811 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kwhu1pbbNTERfahAsj9:-Kwhu1pbbNTERfahAsjA:b-6rggub) ([raw file](https://github.com/dgraph-io/badger/blob/4493478c63751df6471a08082cc2b1415854f180/value.go#L811)):*
> ```Go
> 	}
> 	// This file shouldn't be being written to.
> 	idx := rand.Intn(int(headValPointer.Fid))
> ```

This might not work. Because we're talking about indices here, as opposed to fids. Better to search the space to find the index corresponding to this fid, and then find an index below that index.

---

*[value.go, line 813 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kwhte7-NqbL6Trqhquw:-Kwhte7-NqbL6Trqhqux:b3v08bg) ([raw file](https://github.com/dgraph-io/badger/blob/4493478c63751df6471a08082cc2b1415854f180/value.go#L813)):*
> ```Go
> 	idx := rand.Intn(int(headValPointer.Fid))
> 	if idx > 0 {
> 		idx = rand.Intn(idx) // Another level of rand to favor smaller fids.
> ```

shouldn't this be idx + 1? I think it should be, so the original idx is also a possible reply.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/279)*

**Comment by deepakjois** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[value.go, line 807 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/279#-KwhtBSF-m462tpkofWO:-Kx6Kgn6ZrKn7QVkfAia:bcmmz8q) ([raw file](https://github.com/dgraph-io/badger/blob/4493478c63751df6471a08082cc2b1415854f180/value.go#L807)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This cond can be moved to the top, before acquiring lock.
</blockquote></details>

Actually no. We need to acquire a lock before we get `fids`. At least that is what I gathered from the comments on vlog.sortedFids() method.

---

*[value.go, line 811 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kwhu1pbbNTERfahAsj9:-Kx6KsoppZofMWvrGgy5:b-nvlfsr) ([raw file](https://github.com/dgraph-io/badger/blob/4493478c63751df6471a08082cc2b1415854f180/value.go#L811)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This might not work. Because we're talking about indices here, as opposed to fids. Better to search the space to find the index corresponding to this fid, and then find an index below that index.
</blockquote></details>

Done. I also changed the logic around here. Also added a check to exclude the last fid(which is being written to) from candidates to be picked.

---

*[value.go, line 813 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kwhte7-NqbL6Trqhquw:-Kx6L3wccb715yp3FBTK:bezwfdb) ([raw file](https://github.com/dgraph-io/badger/blob/4493478c63751df6471a08082cc2b1415854f180/value.go#L813)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

shouldn't this be idx + 1? I think it should be, so the original idx is also a possible reply.
</blockquote></details>

Changed the logic. See comment above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/279)*

**Comment by deepakjois** [comment]
Please take another look. There is a case I am wondering about. I am wondering if it is possible that the head pointer resolves to a file that is not in the list of fids. Added a TODO in the code.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/279#-:-Kx6LHsHb-av_uIzcUwD:b-fqowiu)*

**Comment by manishrjain** [comment]
With your change, it shouldn't. But, previously it could.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[db.go, line 1002 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6NHBKlz6XBZDXKjvR:-Kx6NHBKlz6XBZDXKjvS:b-8r845n) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/db.go#L1002)):*
> ```Go
> 	headKey := y.KeyWithTs(head, math.MaxUint64)
> 	// Need to pass with timestamp, lsm get removes the last 8 bytes and compares key
> 	headValStruct, err := db.lc.get(headKey)
> ```

val, err := db.lc.get(headKey)

---

*[db.go, line 1007 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6NDpsiE-OSwut4kBe:-Kx6NDpsiE-OSwut4kBf:bhcqlv2) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/db.go#L1007)):*
> ```Go
> 	}
> 
> 	var headValPointer valuePointer
> ```

var head valuePointer

---

*[value.go, line 807 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/279#-KwhtBSF-m462tpkofWO:-Kx6LbM2UGPX-FGvRxO0:b-5k5s36) ([raw file](https://github.com/dgraph-io/badger/blob/4493478c63751df6471a08082cc2b1415854f180/value.go#L807)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

Actually no. We need to acquire a lock before we get `fids`. At least that is what I gathered from the comments on vlog.sortedFids() method.
</blockquote></details>

I meant `headValPointer.Fid`, but nvm. Can keep it here.

---

*[value.go, line 803 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6Lgj0t57d9eOkCYbk:-Kx6Lgj0t57d9eOkCYbl:b-wgahrl) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/value.go#L803)):*
> ```Go
> }
> 
> func (vlog *valueLog) pickLog(headValPointer valuePointer) *logFile {
> ```

No need to have a pointer suffix. Just call it `head`.

---

*[value.go, line 818 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6Ly1-525jvnJIUhHG:-Kx6Ly1-525jvnJIUhHH:bx7wqo0) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/value.go#L818)):*
> ```Go
> 		return nil
> 	}
> ```

Remove vert space.

---

*[value.go, line 819 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6MGVexEtlMXqc_GSe:-Kx6MGVexEtlMXqc_GSf:b-mgjxkm) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/value.go#L819)):*
> ```Go
> 	}
> 
> 	if i == len(fids)-1 { // this file shouldn’t be being written to
> ```

This condition shouldn't be here. Whatever i is, you want i - 1. The file which has the head, shouldn't be written to. Not the last file in fids (the main issue is that the last to last file might be where the head is, or two below or three below, etc.).

---

*[value.go, line 850 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6MoSQvSSYDG6ICZmL:-Kx6MoSQvSSYDG6ICZmM:btl2wu0) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/value.go#L850)):*
> ```Go
> }
> 
> func (vlog *valueLog) doRunGC(gcThreshold float64, headValPointer valuePointer) error {
> ```

Just call it head. The valuePointer is already the type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/279#-:-Kx6NZA06Sod-QNqqn1S:b-yxz2o6)*

**Comment by deepakjois** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[db.go, line 1002 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6NHBKlz6XBZDXKjvR:-Kx6SST5XL76ZVdvmTuL:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/db.go#L1002)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

val, err := db.lc.get(headKey)
</blockquote></details>

Done.

---

*[db.go, line 1007 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6NDpsiE-OSwut4kBe:-Kx6STKeBk2-5XikHB4R:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/db.go#L1007)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

var head valuePointer
</blockquote></details>

Done.

---

*[value.go, line 803 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6Lgj0t57d9eOkCYbk:-Kx6SU8T1CuRJhEBszV1:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/value.go#L803)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to have a pointer suffix. Just call it `head`.
</blockquote></details>

Done.

---

*[value.go, line 818 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6Ly1-525jvnJIUhHG:-Kx6SgYAjdciFoKwlFVn:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/value.go#L818)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove vert space.
</blockquote></details>

Done.

---

*[value.go, line 819 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6MGVexEtlMXqc_GSe:-Kx6Sh1amG-UDsW7FxEE:b-td5ifu) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/value.go#L819)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This condition shouldn't be here. Whatever i is, you want i - 1. The file which has the head, shouldn't be written to. Not the last file in fids (the main issue is that the last to last file might be where the head is, or two below or three below, etc.).
</blockquote></details>

Ok, so we need to pick a value log file which:

* does not contain the head, and 
* which has been written to disk before the file containing head has been written to disk. i.e. it has an fid less than `head.Fid`.

So that means the line below should be 

`idx := rand.Intn(i)`

and not,

`idx := rand.Intn(i+1)`

Am I right? I have made that change under this assumption.

---

*[value.go, line 850 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6MoSQvSSYDG6ICZmL:-Kx6Tlk0Plqtjy8UWoWv:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/value.go#L850)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just call it head. The valuePointer is already the type.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/279)*

**Comment by deepakjois** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[value.go, line 807 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/279#-KwhtBSF-m462tpkofWO:-Kx6U5jBeWGphRuySSR4:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/4493478c63751df6471a08082cc2b1415854f180/value.go#L807)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I meant `headValPointer.Fid`, but nvm. Can keep it here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/279)*

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[value.go, line 819 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6MGVexEtlMXqc_GSe:-Kx6WUKa7BcRG3Kqr93x:b-8vopz6) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/value.go#L819)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

Ok, so we need to pick a value log file which:

* does not contain the head, and 
* which has been written to disk before the file containing head has been written to disk. i.e. it has an fid less than `head.Fid`.

So that means the line below should be 

`idx := rand.Intn(i)`

and not,

`idx := rand.Intn(i+1)`

Am I right? I have made that change under this assumption.

</blockquote></details>

True. And that leads me back to the original comment about the second round of rand. It should be idx+1, and not idx.

---

*[value.go, line 818 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6WezNKMMvCBfR7xSa:-Kx6WezNKMMvCBfR7xSb:b-4g5hym) ([raw file](https://github.com/dgraph-io/badger/blob/4ad4fa9703780fa2ab394b10e7379f0813a21788/value.go#L818)):*
> ```Go
> 	}
> 
> 	idx := rand.Intn(i)
> ```

// Add a comment about not including the index which contains the head Fid.

---

*[value.go, line 820 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6WbNTfzbQG6GjxYKz:-Kx6WbNTfzbQG6GjxYL-:b-lpdelq) ([raw file](https://github.com/dgraph-io/badger/blob/4ad4fa9703780fa2ab394b10e7379f0813a21788/value.go#L820)):*
> ```Go
> 	idx := rand.Intn(i)
> 	if idx > 0 {
> 		idx = rand.Intn(idx) // Another level of rand to favor smaller fids.
> ```

idx+1 here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/279)*

**Comment by deepakjois** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[value.go, line 819 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6MGVexEtlMXqc_GSe:-Kx6XxELTsRfrkfWNZac:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/f6bdfa0af45295befdf8d828b863c65d9d192cf8/value.go#L819)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

True. And that leads me back to the original comment about the second round of rand. It should be idx+1, and not idx.
</blockquote></details>

Done.

---

*[value.go, line 818 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6WezNKMMvCBfR7xSa:-Kx6XyN1E3YxYmg7gppX:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/4ad4fa9703780fa2ab394b10e7379f0813a21788/value.go#L818)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

// Add a comment about not including the index which contains the head Fid.
</blockquote></details>

Done.

---

*[value.go, line 820 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/279#-Kx6WbNTfzbQG6GjxYKz:-Kx6Xxpdze416yCrl6J0:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/4ad4fa9703780fa2ab394b10e7379f0813a21788/value.go#L820)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

idx+1 here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/279)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/279#-:-Kx6gIdczlwnjvMc1fFC:bnfp4nl)*

**Pull request merged**
