### PR TITLE
Add test for value log replay

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/253)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Use custom comparator instead of bytes.compare. Otherwise y.keywithTs(a,0) would be greater than y.keywithts(aa,0) if we use bytes.compare.

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/253#-:-KvUfyeAlr0jORUMFoLD:b-erwxek)*

**Comment by janardhan1993** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[kv.go, line 84 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/253#-KvUgExF-lnRSBLMLohq:-KvUgExF-lnRSBLMLohr:b-n3wlzq) ([raw file](https://github.com/dgraph-io/badger/blob/a01277526bbbb589cb0e003e85ed62bb5a4e0d63/kv.go#L84)):*
> ```Go
> )
> 
> func replayFunction(out *KV) func(entry, valuePointer) error {
> ```

Moved this function out so that this part is testable. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/253)*

**Comment by manishrjain** [comment]
:lgtm: 

---

Reviewed 6 of 18 files at r1, 7 of 12 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[table/iterator.go, line 283 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/253#-KvWCJpcJjQH-FujzU0-:-KvWCJpcJjQH-FujzU00:b-elwt91) ([raw file](https://github.com/dgraph-io/badger/blob/a1ff3f3517247a24c0ae1a78136f33b947d0b3f7/table/iterator.go#L283)):*
> ```Go
> 
> 	var idx int
> 	if len(itr.t.blockIndex) > 1 {
> ```

Looks like an unnecessary micro-optimization. blockIndex would very rarely have only one entry, so this would always trigger anyway.

---

*[y/y.go, line 85 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/253#-KvWCs4eJXPSihgR9n39:-KvWCs4fNcWWLjz7wjxA:bo7493e) ([raw file](https://github.com/dgraph-io/badger/blob/a1ff3f3517247a24c0ae1a78136f33b947d0b3f7/y/y.go#L85)):*
> ```Go
> // KeyWithTs generates a new key by appending ts to key.
> // TODO: Mention in docs, key shouldn't have 0x00 when keys are of
> // unequal length. (Probably escape 0x00 in key and ts)
> ```

How would we escape 0x00?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/253#-:-KvWDIKaX-6QLF_cADho:bg7igkv)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[y/y.go, line 92 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/253#-KvZYrQcSS871ZZ8-zx7:-KvZYrQcSS871ZZ8-zx8:bb6og66) ([raw file](https://github.com/dgraph-io/badger/blob/a1b3ee3e8c4eaa3b32d08299213ef442fd829b24/y/y.go#L92)):*
> ```Go
> 
> func ParseTs(key []byte) uint64 {
> 	if len(key) < 8 {
> ```

<= 8

---

*[y/y.go, line 103 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/253#-KvZYcHmAxL4uJE9yvOE:-KvZYcHmAxL4uJE9yvOF:btlvoj3) ([raw file](https://github.com/dgraph-io/badger/blob/a1b3ee3e8c4eaa3b32d08299213ef442fd829b24/y/y.go#L103)):*
> ```Go
> // All keys should have timestamp.
> func CompareKeys(key1 []byte, key2 []byte) int {
> 	AssertTruef(len(key1) >= 8 && len(key2) >= 8, "%q %q", key1, key2)
> ```

can't be equal.

---

*[y/y.go, line 115 at r3](https://reviewable.io:443/reviews/dgraph-io/badger/253#-KvZYne2l3JP87SEknz3:-KvZYne2l3JP87SEknz4:b-j8nfs9) ([raw file](https://github.com/dgraph-io/badger/blob/a1b3ee3e8c4eaa3b32d08299213ef442fd829b24/y/y.go#L115)):*
> ```Go
> 	}
> 
> 	AssertTruef(len(key) >= 8, "key=%q", key)
> ```

can't be equal. We shouldn't allow empty keys.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/253#-:-KvZYwSjyU8cIA9vx0xo:bnfp4nl)*

**Pull request closed without merging**
