### PR TITLE
fix(stream): improve error handling

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
This fixes error handling during streaming.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1772)

### CODE REVIEW

**Comment by akon-dey** [comment]
@SaveTheRbtz thank you for cleaning this up. Please add a unit test to cover these fixes.

**Comment by SaveTheRbtz** [comment]
@akon-dey any suggestions how to best test it?  It looks like I can only do that by changing the `StreamDB` API to dependency inject the writer.

**Comment by akon-dey** [comment]
@SaveTheRbtz I guess it's more work and the code looks good (also from offline feedback from former maintainers). I will merge it. Thank you for working on this.

**Comment by SaveTheRbtz** [comment]
I did a stab at trying to figure out how to best test it.

Converting `StreamWriter` to an interface may work, e.g.: https://github.com/dgraph-io/badger/compare/master...SaveTheRbtz:streamTests?expand=1
I'm not sure how much of that worth the added complexity, but for the ease of testing all public structures in this package should likely be interfaces, so that they can easily be mocked in all kinds of tests (incl. tests by the users of the library, when they want to mock badger database.)

**Pull request merged**
