### PR TITLE
Update gogo/protobuf to 1.2.1

### PR DESCRIPTION
**Pull request by Kubuxu**
This PR updates generated code to one generated with gogo/protobuf v1.2.1 and also fixes `gen.sh` script.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/728)

### CODE REVIEW

**Comment by Kubuxu** [comment]
Appveyor failed because of:
```
Mmap value log file. Path=C:\Users\appveyor\AppData\Local\Temp\1\badger777207792\000000.vlog. Error=truncate: truncate C:\Users\appveyor\AppData\Local\Temp\1\badger777207792\000000.vlog: There is not enough space on the disk
```

**Comment by manishrjain** [comment]
We use KV defined here in Dgraph. Not sure if this change would break Dgraph or not -- Dgraph uses vanilla protobuf.

**Comment by Kubuxu** [comment]
gogo/protobuf and golang/protobuf can coexist without any issues. You can use their `*/proto` packages interchangeably.

**Comment by gedw99** [comment]
@Kubuxu are you sure ? I also would be broken otherwise. Got a link maybe ?

**Comment by Kubuxu** [comment]
I've updated it to use golang import.

**Pull request closed without merging**
