### PR TITLE
Fix valueLog/logFile locking

### PR DESCRIPTION
**Pull request by srh**
This fixes problems referred to by the comment at https://github.com/dgraph-io/badger/pull/177#issuecomment-324483634

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/188)

### CODE REVIEW

**Comment by srh** [comment]
On a general note, I gave the lock fields actual names. It is possible to use the "go to all uses" feature of VS Code and maybe some other IDE's if the field has a name.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[value.go, line 101 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/188#-KsuUcOOf14CKpXenZeJ:-KsuUcOPHhYIQj0APnIm:bdm9wf8) ([raw file](https://github.com/dgraph-io/badger/blob/a7b4b8b8da7d4fb15da98d148f5181f0562bbd35/value.go#L101)):*
> ```Go
> 
> func (lf *logFile) doneWriting() error {
> 	// Sync before acquiring lock.  (We call this from write() and thus know we have shared access
> ```

Independent of the other changes is our moving this lock acquisition down.

---

*[value.go, line 111 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/188#-KsuUgceO4rc1V_X60Ep:-KsuUgceO4rc1V_X60Eq:b-jbdupf) ([raw file](https://github.com/dgraph-io/badger/blob/a7b4b8b8da7d4fb15da98d148f5181f0562bbd35/value.go#L111)):*
> ```Go
> 	//
> 	// If there's a benefit to reopening the file read-only, it might be on Windows.  I don't know
> 	// what the benefit is.  Consider keeping the file read-write, or use fcntl to change permissions.
> ```

^^^ I was wondering about this.  Is there a reason we re-open the file, other than some safety of having it open read-only?

---

*[value.go, line 332 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/188#-KsuUkDA-bjvQJkiK5Uk:-KsuUkDA-bjvQJkiK5Ul:bzk578) ([raw file](https://github.com/dgraph-io/badger/blob/a7b4b8b8da7d4fb15da98d148f5181f0562bbd35/value.go#L332)):*
> ```Go
> 		})
> 		if idx == len(vlog.files) || vlog.files[idx].fid != f.fid {
> 			vlog.filesLock.Unlock()
> ```

Independent of the other changes is this fix to 

---

*[value.go, line 639 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/188#-KsuVTKcrWdBDDlsEorW:-KsuVTKcrWdBDDlsEorX:brya07u) ([raw file](https://github.com/dgraph-io/badger/blob/a7b4b8b8da7d4fb15da98d148f5181f0562bbd35/value.go#L639)):*
> ```Go
> 	}
> 	curlf := vlog.files[len(vlog.files)-1]
> 	curlf.lock.RLock()
> ```

The other main change is that readers must get shared access to the logFile before releasing shared access to the valueLog.  This is as was discussed in Slack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/188#-:-KsuV0kfvcToO4wF4U8G:bwb8fc5)*

**Comment by manishrjain** [comment]
Adding lock fields seems an unnecessary change. A ctrl+f could have given you that? Because all the users are in the same file. Other than that, :lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[value.go, line 111 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/188#-KsuUgceO4rc1V_X60Ep:-KsuiIO4K7mQp9cc6asx:b-ilnu84) ([raw file](https://github.com/dgraph-io/badger/blob/a7b4b8b8da7d4fb15da98d148f5181f0562bbd35/value.go#L111)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

^^^ I was wondering about this.  Is there a reason we re-open the file, other than some safety of having it open read-only?
</blockquote></details>

It's cleaner to make a file supposed to be immutable read only. Blocking a few reads / writes for this small duration, is a small price to pay for this.

---

*[value.go, line 332 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/188#-KsuUkDA-bjvQJkiK5Uk:-KsulILMtixqsJLUit1u:b32w0x) ([raw file](https://github.com/dgraph-io/badger/blob/a7b4b8b8da7d4fb15da98d148f5181f0562bbd35/value.go#L332)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

Independent of the other changes is this fix to 
</blockquote></details>

OK

---

*[value.go, line 639 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/188#-KsuVTKcrWdBDDlsEorW:-Ksulqe6I-F1XJ0WrgMS:b2nhktp) ([raw file](https://github.com/dgraph-io/badger/blob/a7b4b8b8da7d4fb15da98d148f5181f0562bbd35/value.go#L639)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

The other main change is that readers must get shared access to the logFile before releasing shared access to the valueLog.  This is as was discussed in Slack.
</blockquote></details>

OK.

---

*[value.go, line 733 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/188#-Ksum9puo6N6v1IelugG:-Ksum9puo6N6v1IelugH:b-wspfj) ([raw file](https://github.com/dgraph-io/badger/blob/a7b4b8b8da7d4fb15da98d148f5181f0562bbd35/value.go#L733)):*
> ```Go
> 	defer vlog.filesLock.RUnlock()
> 
> 	idx := sort.Search(len(vlog.files), func(idx int) bool {
> ```

Unrelated to this change, but caught my eye. This seems expensive to do for every read call. We should switch to a map instead of a list of files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/188#-:-Ksuj0XATRCMoFG1FvEQ:bc5wfs)*

**Comment by srh** [comment]
How do you know all the users are in the same file?  The first iteration of this review was broken because I had missed stuff by trying to find all uses of the locks manually somehow.  Also the lock for the value log isn't locking the entire object, and for logFile it's basically a lock on the file descriptor, not the whole structure either.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/188#-:-KsuoUJ8WsPofw4TvP_4:b-cvqrsl)*

**Comment by srh** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[value.go, line 733 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/188#-Ksum9puo6N6v1IelugG:-KsuplrwdyiL3pd3noaP:b2s2c8n) ([raw file](https://github.com/dgraph-io/badger/blob/a7b4b8b8da7d4fb15da98d148f5181f0562bbd35/value.go#L733)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Unrelated to this change, but caught my eye. This seems expensive to do for every read call. We should switch to a map instead of a list of files.
</blockquote></details>

Made issue https://github.com/dgraph-io/badger/issues/189 for this. Working on it now.  (Generally speaking I'm doing cleanup work while working on https://github.com/dgraph-io/badger/issues/178.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/188)*

**Comment by manishrjain** [comment]
> Also the lock for the value log isn't locking the entire object, and for logFile it's basically a lock on the file descriptor, not the whole structure either.

Fair point.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/188#-:-KsuylG84bLdzwXg0fFl:b-bp8dx9)*

**Comment by srh** [comment]
In master as of edbce1ba8ec4e07ff2d881291d314598512a6a0c.

**Pull request closed without merging**
