### PR TITLE
fix goroutine leak caused by log file lock

### PR DESCRIPTION
**Pull request by h12w**
This commit fixes a goroutine leak caused by log file lock (part of #421).

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/426)

### CODE REVIEW

**Comment by funny-falcon** [comment]
Couldn't it be linked with #410 and #407 ?

**Comment by funny-falcon** [comment]
Looks like it doesn't fix #410 :-(

**Comment by manishrjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[value.go, line 578 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/426#-L6J-J1Jv6mpDIF2jO9Y:-L6J-J1Jv6mpDIF2jO9Z:b-3psbew) ([raw file](https://github.com/dgraph-io/badger/blob/db715825c86226e480485f7a0b8d8daddb2dc9f3/value.go#L578)):*
> ```Go
> 		}
> 		f.fd = nil      // indicate the logFile has been closed
> 		f.lock.Unlock() // unlock to release prefetch goroutines
> ```

This shouldn't be needed. All iterators and read-write ops should be closed before calling DB.Close().

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/426)*

**Comment by manishrjain** [comment]
This commit fixes the issue at the source. https://github.com/dgraph-io/badger/commit/8d041dd05458b8c3a85eefcae81952933ef3f72e

**Pull request closed without merging**
