### PR TITLE
Add more error handling. Make Get() return error as well

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/48)

### CODE REVIEW

**Comment by szymonm** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[badger/kv.go, line 340 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/48#-KlNfZ3cr_S1K3oNHDS0:-KlNfZ3cr_S1K3oNHDS1:b-b9cwh0) ([raw file](https://github.com/dgraph-io/badger/blob/6a1deea6a052e1b90546910c715abce2e73f71ea/badger/kv.go#L340)):*
> ```Go
> // getValueHelper returns the value in memtable or disk for given key.
> // Note that value will include meta byte.
> func (s *KV) get(key []byte) (y.ValueStruct, error) {
> ```

error is always nil or I miss something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/48)*

**Comment by manishrjain** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[badger/kv.go, line 340 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/48#-KlNfZ3cr_S1K3oNHDS0:-KlNhvvZxUrOqmq-WD0b:b-66jb4x) ([raw file](https://github.com/dgraph-io/badger/blob/6a1deea6a052e1b90546910c715abce2e73f71ea/badger/kv.go#L340)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

error is always nil or I miss something?
</blockquote></details>

s.lc.get(key) can return error. It is only nil for memtables, not for levels.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/48)*

**Comment by szymonm** [comment]
Reviewed 4 of 10 files at r1.
Review status: 4 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[badger/kv.go, line 340 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/48#-KlNfZ3cr_S1K3oNHDS0:-KlNiDPzyLvegRgrbwrA:byr4flj) ([raw file](https://github.com/dgraph-io/badger/blob/6a1deea6a052e1b90546910c715abce2e73f71ea/badger/kv.go#L340)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

s.lc.get(key) can return error. It is only nil for memtables, not for levels.
</blockquote></details>

Right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/48)*

**Comment by szymonm** [comment]
:lgtm:

---

Review status: 4 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/48#-:-KlNiWkTgwdtbkRxqgx8:bnfp4nl)*

**Comment by szymonm** [comment]
Reviewed 1 of 10 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/48)*

**Comment by szymonm** [comment]
@manishrjain what do we need to merge this?

**Comment by manishrjain** [comment]
This has already been merged.

**Pull request closed without merging**
