### PR TITLE
Refactoring: simplify LevelCloser

### PR DESCRIPTION
**Pull request by srh**
This gets rid of Closer (we were using it with a static set of keys) and simplifies LevelCloser down to its essence.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/200)

### CODE REVIEW

**Comment by srh** [comment]
A separate PR will rename LevelCloser to Closer (I thought it would make the diff confusing here).

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[kv.go, line 123 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/200#-KtOC1sYV5h81Qzx0lSq:-KtOC1sYV5h81Qzx0lSr:b-d8bjp0) ([raw file](https://github.com/dgraph-io/badger/blob/2e3d57a2926e25d7853d9e6efbc6be7cd8f48040/kv.go#L123)):*
> ```Go
> 	return len(entry.Key) + 16 + y.MetaSize + y.UserMetaSize + y.CasSize
> }
> ```

One part of the change:  Put the LevelClosers in this struct, instead of in a y.Closer.  Except for "replay".

---

*[kv.go, line 277 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/200#-KtOCA9V6E5Z7SqVteJX:-KtOCA9V6E5Z7SqVteJY:b-ua6nc5) ([raw file](https://github.com/dgraph-io/badger/blob/2e3d57a2926e25d7853d9e6efbc6be7cd8f48040/kv.go#L277)):*
> ```Go
> 		vptr.Decode(val)
> 	}
> ```

replayCloser doesn't actually go into the closers because we're done using it in this function.

---

*[y/y.go, line 94 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/200#-KtOCNzPsrBBJx4T8Yxl:-KtOCNzPsrBBJx4T8Yxm:bh7rkp1) ([raw file](https://github.com/dgraph-io/badger/blob/2e3d57a2926e25d7853d9e6efbc6be7cd8f48040/y/y.go#L94)):*
> ```Go
> 	return s.buf[0:sz]
> }
> ```

Some changes to LevelCloser, too:  Got rid of nomore (we now error if you send duplicate signals -- we don't).  Got rid of running (now we keep that count in the WaitGroup).  Nothing was re-registering the same string with Closer, so we didn't need the complications around that.

Also, if we have unbalanced calls to Done(), we don't silently consume them -- WaitGroup will panic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/200#-:-KtOBt8C-1go1ncG1pSS:b1692n9)*

**Comment by srh** [comment]
Or I won't make a separate PR -- it just renames LevelCloser/NewLevelCloser to Closer/NewCloser.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/200#-:-KtODBHwBYUr_7xU6gtV:b-si3hov)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/200#-:-KtOyQEmF2Xa4uC4Vp3v:bnfp4nl)*

**Comment by srh** [comment]
In master as of 77b77835e56ea47a27b9e0c2d4bbf5cb1996126f.

**Pull request closed without merging**
