### PR TITLE
Fix link to docs

### PR DESCRIPTION
**Pull request by mbj36**
added `blob` to link

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/1536)

### CODE REVIEW

**Review by jarifibrahim — APPROVED** [review]

**Comment by jarifibrahim** [comment]
@mbj36 you can merge this PR after signing the CLA (Travis 32 bit is failing and you can ignore it). Please make sure the docs look fine locally.

**Comment by mbj36** [comment]
@jarifibrahim I have signed the CLA, not sure why it shows Pending, Also i don't have merge access

**Comment by jarifibrahim** [comment]
@mbj36 The commit was made by
```
commit 82d41291371bac3d76ea21959f906b46e959161d (HEAD -> fix-link, origin/fix-link)
Author: Mohit  Bajoria <mohitbaj36@gmail.com>
Date:   Tue Sep 22 01:10:22 2020 +0530

    Fix link to docs
```
and I don't think this email is associated with your Github account. Can you double-check which email IDs your Github account has?

**Comment by jarifibrahim** [comment]
Also, please try to use the `<user>/branch` name convention. It makes it easier to keep track of the branches. :)

**Pull request merged**
