### PR TITLE
close iterator in purgeolderversions

### LINKED ISSUE #344: the item view not timestamp?
when I use item.Version() get the item version, I find it likes 56, 57,58... not timestamp?
and when i call PurgeOlderVersions and RunValueLogGC(0.5), i get Value log GC attempt didn't result in any cleanup

### PR DESCRIPTION
**Pull request by janardhan1993**
Fixes #344 

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/348)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[db.go, line 968 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/348#-L02ewUx8vIC40eU0j3a:-L02ewUyYnaHOiil4HNV:b5q6wk3) ([raw file](https://github.com/dgraph-io/badger/blob/4c525df7bbdfc62f6eb1223d27bb34bae2629363/db.go#L968)):*
> ```Go
> 
> 			// Batch up 1000 entries at a time and write
> 			if count == 1000 || count == int(db.opt.maxBatchCount-1) {
> ```

There was a func I had added which could check if the size exceeded or not. See if you can use that here. It's used in Set and Delete.

---

*[value.go, line 965 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/348#-L02f9sANXiSNAonEhhz:-L02f9sANXiSNAonEhi-:bovakaj) ([raw file](https://github.com/dgraph-io/badger/blob/4c525df7bbdfc62f6eb1223d27bb34bae2629363/value.go#L965)):*
> ```Go
> 	vlog.elog.Printf("Fid: %d Data status=%+v\n", lf.fid, r)
> 
> 	minTotal := vlog.opt.ValueLogFileSize / (100 << 20)
> ```

What's this doing? Add a comment. I also don't understand the significance of 10.0 from before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/348)*

**Comment by deepakjois** [comment]
I dont really understand what the code is doing so I can’t lgtm it.

The commit message is misleading. This code is doing more than just closing the iterator. Maybe break apart this change into more than one commit? The closing of the iterator can happen in one commit, and the rest of the code (which is presumably fixing a bug) in another commit.

Please add more context to the commit message.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[value_test.go, line 532 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/348#-L02fL4lwyD2yrbSfhYo:-L02fL4lwyD2yrbSfhYp:bgnfrpk) ([raw file](https://github.com/dgraph-io/badger/blob/4c525df7bbdfc62f6eb1223d27bb34bae2629363/value_test.go#L532)):*
> ```Go
> }
> 
> func TestPurgeOlderVersions2(t *testing.T) {
> ```

Could you rename this to something more descriptive, based on what it is actually testing. `TestPurgeOlderVersions2` doesnt really convey the intent of the test.

I bring this up, because I have seen other tests in the codebase that use this numbered naming convention, and I remember being confused when I tried to figure out what they did.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/348#-:-L02g4gyOvZDmCURz9sj:b39bczo)*

**Comment by janardhan1993** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[db.go, line 968 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/348#-L02ewUx8vIC40eU0j3a:-L03-DkkcE8OFEO2yY6x:bef8ty3) ([raw file](https://github.com/dgraph-io/badger/blob/4c525df7bbdfc62f6eb1223d27bb34bae2629363/db.go#L968)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

There was a func I had added which could check if the size exceeded or not. See if you can use that here. It's used in Set and Delete.
</blockquote></details>

That function can't be reused, i can create a new function which takes count and size as argument.

---

*[value.go, line 965 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/348#-L02f9sANXiSNAonEhhz:-L03-S6SZ1Ez_FupWHkK:by5wmpx) ([raw file](https://github.com/dgraph-io/badger/blob/4c525df7bbdfc62f6eb1223d27bb34bae2629363/value.go#L965)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What's this doing? Add a comment. I also don't understand the significance of 10.0 from before.
</blockquote></details>

I thought we wanted the iterate to see atleast 10mb of data since we start at random point in the vlog.  On deeper lock it appears that we don't pick a start point in that last 100mb. So i am not sure what that 10 mb check was for.

---

*[value_test.go, line 532 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/348#-L02fL4lwyD2yrbSfhYo:-L02w7tWThGzviGusY5b:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/4c525df7bbdfc62f6eb1223d27bb34bae2629363/value_test.go#L532)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

Could you rename this to something more descriptive, based on what it is actually testing. `TestPurgeOlderVersions2` doesnt really convey the intent of the test.

I bring this up, because I have seen other tests in the codebase that use this numbered naming convention, and I remember being confused when I tried to figure out what they did.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/348)*

**Comment by manishrjain** [comment]
:lgtm: Couple of comments.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[value.go, line 965 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/348#-L02f9sANXiSNAonEhhz:-L07cUdvGiJqtYeshn-r:b-shjfzn) ([raw file](https://github.com/dgraph-io/badger/blob/4c525df7bbdfc62f6eb1223d27bb34bae2629363/value.go#L965)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

I thought we wanted the iterate to see atleast 10mb of data since we start at random point in the vlog.  On deeper lock it appears that we don't pick a start point in that last 100mb. So i am not sure what that 10 mb check was for.
</blockquote></details>

Unless you understand this, don't change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/348#-:-L07c_YBj_qcCTlGcXyW:bojlezm)*

**Comment by deepakjois** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[value_test.go, line 533 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/348#-L07kB8kzqNkBDG8ObLw:-L07kB8lp2wGhurHPHO2:b-7n9fdy) ([raw file](https://github.com/dgraph-io/badger/blob/7e54d89d3fb0da827399140270417e29c8b20876/value_test.go#L533)):*
> ```Go
> 
> func TestValueLogGC(t *testing.T) {
> 	dir, err := ioutil.TempDir("", "badger")
> ```

Wrap this in `runBadgerTest()` to avoid the boilerplate:

```Go
runBadgerTest(t, opt, func(t *testing.T, db *DB) {
  sz := 1 << 10
//…
})
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/348)*

**Comment by deepakjois** [comment]
Sorry if I come across as a bit nitpicky, but I see three distinct changes in this commit:

* Close iterator in PurgeOlderVersions
* Ensure batching of entries does not violate maxBatchSize or maxBatchCount constraint
* Add a test for Value Log GC (which does not seem directly related to the 2 changes above)

Please consider making 3 different commits in this PR before merging it.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/348#-:-L07kiCfYrM-Ae4qUbwq:b-u7e4k7)*

**Comment by deepakjois** [comment]
Otherwise :lgtm:, apart from the one comment.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/348#-:-L07lX7aRJsRrZct6wt7:b-7bx8cv)*

**Comment by janardhan1993** [comment]
Will separate it into three commit

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[value_test.go, line 533 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/348#-L07kB8kzqNkBDG8ObLw:-L07ubnyMLBFhJPp4Uzn:bu5uu0d) ([raw file](https://github.com/dgraph-io/badger/blob/7e54d89d3fb0da827399140270417e29c8b20876/value_test.go#L533)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

Wrap this in `runBadgerTest()` to avoid the boilerplate:

```Go
runBadgerTest(t, opt, func(t *testing.T, db *DB) {
  sz := 1 << 10
//…
})
```
</blockquote></details>

We need most of the boiler plate for the creation of the options,(different than the default test options). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/348#-:-L07szwPJ3c4AZQiby8U:bjqdczc)*

**Comment by deepakjois** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[value_test.go, line 533 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/348#-L07kB8kzqNkBDG8ObLw:-L07wwDtwmJETvBPZNK6:bla2g5a) ([raw file](https://github.com/dgraph-io/badger/blob/7e54d89d3fb0da827399140270417e29c8b20876/value_test.go#L533)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We need most of the boiler plate for the creation of the options,(different than the default test options). 
</blockquote></details>

Just two lines right? All the file creation and open can be removed:

```Go
opt := getTestOptions(dir)
opt.ValueLogFileSize = 1 << 20
runBadgerTest(t, opt, func(t *testing.T, db *DB) {
  sz := 1 << 10
  //…
})
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/348)*

**Comment by janardhan1993** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[value_test.go, line 533 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/348#-L07kB8kzqNkBDG8ObLw:-L083B_dV11y_80rmlj2:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/7e54d89d3fb0da827399140270417e29c8b20876/value_test.go#L533)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

Just two lines right? All the file creation and open can be removed:

```Go
opt := getTestOptions(dir)
opt.ValueLogFileSize = 1 << 20
runBadgerTest(t, opt, func(t *testing.T, db *DB) {
  sz := 1 << 10
  //…
})
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/348)*

**Pull request merged**
