### PR TITLE
Limit number of goroutines started in Table.readIndex()

### PR DESCRIPTION
**Pull request by gavriva**
I suggest to limit number of goroutines used to load index. In my tests I saw > 20k goroutines started in this function that does not look efficient from my point of view. go runtime will waste to much time to manage them. In my implementation limited numbers of goroutines serve reads in parallel.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/179)

### CODE REVIEW

**Comment by manishrjain** [comment]
Nice change. I have some comments to improve code readability.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[table/table.go, line 260 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-KsbzvEM9ZNi-Qlf-37n:-KsbzvEM9ZNi-Qlf-37o:bil8aqw) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L260)):*
> ```Go
> 	}
> 
> 	var wg sync.WaitGroup
> ```

Instead of using sync.WaitGroup and errorMutex, you can create an error chan, which can be used to retrieve the errors. Would make the code simpler.

---

*[table/table.go, line 264 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-F6pVfhyC3IU1lMk:-Ksc-F6pVfhyC3IU1lMl:b7ediqx) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L264)):*
> ```Go
> 	wg.Add(len(t.blockIndex))
> 
> 	var errorMutex sync.Mutex
> ```

che := make(chan error, numConcurrentLoads)

---

*[table/table.go, line 267 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc0DICgTwZRLKvYpli:-Ksc0DICgTwZRLKvYplj:b3o8gso) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L267)):*
> ```Go
> 	var readError error
> 
> 	commands := make(chan int, numConcurrentLoads*2)
> ```

```
blocks := make(chan int, len(t.blockIndex))
for i := 0; i < len(t.blockIndex); i++ {
  blocks <- i
}
close(blocks)
```
// This can be done right where you declare blocks; so it's ready for consumption.

---

*[table/table.go, line 280 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-7tQUV9f_A2zSsRj:-Ksc-7tQUV9f_A2zSsRk:b8z89ee) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L280)):*
> ```Go
> 				buf, err := t.read(offset, h.Size())
> 				if err != nil {
> 					errorMutex.Lock()
> ```

```
che <- errors.Wrap(err, "...")
continue
```

---

*[table/table.go, line 298 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-PyVmsd3Rn9EBpIp:-Ksc-PyVmsd3Rn9EBpIq:b2nreh6) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L298)):*
> ```Go
> 					errorMutex.Lock()
> 					if readError != nil {
> 						readError = errors.Wrap(err, "While reading first key in block")
> ```

Same as above.

---

*[table/table.go, line 307 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-RFPsub_Wonam_X9:-Ksc-RFPsub_Wonam_XA:bqvo7jb) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L307)):*
> ```Go
> 
> 				ko.key = buf
> 				wg.Done()
> ```

che <- nil

---

*[table/table.go, line 312 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc0hEENkE7ddMCzrhx:-Ksc-wky4vshRYJlDSbB:bc28x7t) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L312)):*
> ```Go
> 	}
> 
> 	for i := 0; i < len(t.blockIndex); i++ {
> ```

No need to do it here.

---

*[table/table.go, line 316 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-XJAGvrnhpC7Tiai:-Ksc-XJAGvrnhpC7Tiaj:bsfih7x) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L316)):*
> ```Go
> 	}
> 
> 	wg.Wait()
> ```

```
for i := 0; ... {
  if err := <- che; err != nil {
    return err
  }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/179#-:-Ksc0kgVt2TxNLeALc8l:b-r8el33)*

**Comment by gavriva** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[table/table.go, line 260 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-KsbzvEM9ZNi-Qlf-37n:-Ksh9C6cvognwLtDuZZj:b-9d6bvp) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L260)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Instead of using sync.WaitGroup and errorMutex, you can create an error chan, which can be used to retrieve the errors. Would make the code simpler.
</blockquote></details>

Erros are very error, extreme case, moreover we return only the first one from the function. Creating channel for that looks as overhead. I can replace variable+mutex with channel with errors if you think overhead is not important.

---

*[table/table.go, line 316 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-XJAGvrnhpC7Tiai:-KshCF1jZdZ1_P8N78X1:b-2oxs18) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L316)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

```
for i := 0; ... {
  if err := <- che; err != nil {
    return err
  }
}
```
</blockquote></details>

I think we should read len(t.blockIndex) errors from che, to be sure that all goroutines are stopped. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/179)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[table/table.go, line 260 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-KsbzvEM9ZNi-Qlf-37n:-KslkmwMZupUycoNk9vR:b-ejueyy) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L260)):*
<details><summary><i>Previously, gavriva wrote…</i></summary><blockquote>

Erros are very error, extreme case, moreover we return only the first one from the function. Creating channel for that looks as overhead. I can replace variable+mutex with channel with errors if you think overhead is not important.
</blockquote></details>

I'm not sure if waitgroup is more performant than channel. The reason I recommend using error chan, is because it simplifies the code.

---

*[table/table.go, line 316 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-XJAGvrnhpC7Tiai:-KslkcCuRHeEM_w1tLwh:bb77ufg) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L316)):*
<details><summary><i>Previously, gavriva wrote…</i></summary><blockquote>

I think we should read len(t.blockIndex) errors from che, to be sure that all goroutines are stopped. 
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/179)*

**Comment by gavriva** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[table/table.go, line 264 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-F6pVfhyC3IU1lMk:-KsnpqeYbDPkyl8UiqAR:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L264)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

che := make(chan error, numConcurrentLoads)
</blockquote></details>

Done.

---

*[table/table.go, line 267 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc0DICgTwZRLKvYpli:-Ksnq2SueS_BS7Bb1xNB:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L267)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

```
blocks := make(chan int, len(t.blockIndex))
for i := 0; i < len(t.blockIndex); i++ {
  blocks <- i
}
close(blocks)
```
// This can be done right where you declare blocks; so it's ready for consumption.
</blockquote></details>

Done.

---

*[table/table.go, line 280 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-7tQUV9f_A2zSsRj:-KsnpumYERDlHjMxFc4o:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L280)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

```
che <- errors.Wrap(err, "...")
continue
```
</blockquote></details>

Done.

---

*[table/table.go, line 298 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-PyVmsd3Rn9EBpIp:-KsnpzSiO7lV01dEthe2:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L298)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---

*[table/table.go, line 307 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-RFPsub_Wonam_X9:-Ksnq-5sIXVvErPJjhfF:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L307)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

che <- nil
</blockquote></details>

Done.

---

*[table/table.go, line 312 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc0hEENkE7ddMCzrhx:-Ksnq5_r9lfnH8ccI9eK:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L312)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to do it here.
</blockquote></details>

Done.

---

*[table/table.go, line 316 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/179#-Ksc-XJAGvrnhpC7Tiai:-Ksnq0DTmGMdWc3zataj:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/e7dd9d644c41bbedc1b7962d8b2dca0dbe7c325c/table/table.go#L316)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/179)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/179#-:-KsrSrNI0Lz-8U3HjLzE:bnfp4nl)*

**Pull request merged**
