### PR TITLE
Add method to delete older keys

### PR DESCRIPTION
**Pull request by deepakjois**
This is a WIP. Please note the TODOs

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/badger/262)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[db.go, line 873 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw4tbW-ueHyRSMse_3j:-Kw4tbW-ueHyRSMse_3k:bm7ix8p) ([raw file](https://github.com/dgraph-io/badger/blob/ea6199f63346c15df81301bb43cf46cdd7ea36b8/db.go#L873)):*
> ```Go
> // older versions for the database that are no longer needed.
> //
> // * TODO Should we cap the number of deletions to a max value?
> ```

Not cap them, but flush them out every 1000 keys.

---

*[db.go, line 877 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw4tiN9KxL8bBwYg3mc:-Kw4tiN9KxL8bBwYg3md:b-pkym3z) ([raw file](https://github.com/dgraph-io/badger/blob/ea6199f63346c15df81301bb43cf46cdd7ea36b8/db.go#L877)):*
> ```Go
> // * TODO What is the best way to handle a read transaction that might be
> // running when this function is called, and has a readTs < this txn. How do we
> // ‘abort’ that txn? Maybe we add a threshold to the oracle and check that threshold in Txn.Get()
> ```

Yeah, when this function is called, it can set this timestamp in Oracle. Any other function could check that in Commit and Get.

But, then the issue is, what happens if that txn has a long running iteration going on. Do we check for every iterate loop? That'd be too much overhead.

I'd say let's punt on this solution. A user can decide when to call this function. They shouldn't be doing any long running read txns when calling this. A bit of education there can help avoid unnecessary complexity for us.

---

*[db.go, line 889 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw4tD8V1FqjCMAwqKUw:-Kw4tD8V1FqjCMAwqKUx:bgsbj3k) ([raw file](https://github.com/dgraph-io/badger/blob/ea6199f63346c15df81301bb43cf46cdd7ea36b8/db.go#L889)):*
> ```Go
> 		for it.Rewind(); it.Valid(); it.Next() {
> 			item := it.Item()
> 			if !bytes.Equal(lastKey, item.Key()) {
> ```

Can't compare bytes directly, because all keys are suffixed with timestamp. Use y.Compare (or something like that).

---

*[db.go, line 895 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw4tSSiOmvhjXQtdgaZ:-Kw4tSSiOmvhjXQtdga_:bqzzfsz) ([raw file](https://github.com/dgraph-io/badger/blob/ea6199f63346c15df81301bb43cf46cdd7ea36b8/db.go#L895)):*
> ```Go
> 
> 			// Found an older version. Mark for deletion
> 			entries = append(entries,
> ```

A concern might be that this might grow too big, causing OOM. So, better to flush out a batch of say 1000, using batch set async.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262)*

**Comment by manishrjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[db.go, line 900 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw8kVwA_mjI9p1gWdTz:-Kw8kVwA_mjI9p1gWdU-:b-mlnttv) ([raw file](https://github.com/dgraph-io/badger/blob/d0b7dfa2d43f5eb66a2bdee5d792618332eeee30/db.go#L900)):*
> ```Go
> 			// Batch up 1000 entries at a time and write
> 			if count == 1000 {
> 				err := txn.db.batchSet(entries)
> ```

Prefer async.

---

*[db.go, line 907 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw8kXu4iS0gVF_BPSMD:-Kw8kXu4iS0gVF_BPSME:b88voat) ([raw file](https://github.com/dgraph-io/badger/blob/d0b7dfa2d43f5eb66a2bdee5d792618332eeee30/db.go#L907)):*
> ```Go
> 				entries = []*entry{}
> 			}
> 		}
> ```

Shoot off the remaining entries if any.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262)*

**Comment by deepakjois** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[db.go, line 873 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw4tbW-ueHyRSMse_3j:-Kw8zo0pEprtP2zsU5bv:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/ea6199f63346c15df81301bb43cf46cdd7ea36b8/db.go#L873)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Not cap them, but flush them out every 1000 keys.
</blockquote></details>

Done.

---

*[db.go, line 877 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw4tiN9KxL8bBwYg3mc:-Kw8zp9v44CioA-f93kD:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/ea6199f63346c15df81301bb43cf46cdd7ea36b8/db.go#L877)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Yeah, when this function is called, it can set this timestamp in Oracle. Any other function could check that in Commit and Get.

But, then the issue is, what happens if that txn has a long running iteration going on. Do we check for every iterate loop? That'd be too much overhead.

I'd say let's punt on this solution. A user can decide when to call this function. They shouldn't be doing any long running read txns when calling this. A bit of education there can help avoid unnecessary complexity for us.
</blockquote></details>

Done.

---

*[db.go, line 889 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw4tD8V1FqjCMAwqKUw:-Kw8zpzBq5KfSoN0NglS:b-s8q04h) ([raw file](https://github.com/dgraph-io/badger/blob/ea6199f63346c15df81301bb43cf46cdd7ea36b8/db.go#L889)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can't compare bytes directly, because all keys are suffixed with timestamp. Use y.Compare (or something like that).
</blockquote></details>

As I mentioned, this is the iteration interface where the keys are already stripped off their timestamps.

---

*[db.go, line 895 at r1](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw4tSSiOmvhjXQtdgaZ:-Kw8zwtDiefIIOvnC8oR:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/ea6199f63346c15df81301bb43cf46cdd7ea36b8/db.go#L895)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

A concern might be that this might grow too big, causing OOM. So, better to flush out a batch of say 1000, using batch set async.
</blockquote></details>

Done.

---

*[db.go, line 900 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw8kVwA_mjI9p1gWdTz:-Kw9-3SKSejO2pZFb_oO:bc3qf2m) ([raw file](https://github.com/dgraph-io/badger/blob/d0b7dfa2d43f5eb66a2bdee5d792618332eeee30/db.go#L900)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Prefer async.
</blockquote></details>

Copying a comment I made elsewhere: _I could do it, but won’t the error handling will become a little bit complicated. We will have to wait for all the callbacks to finish before we return from the db.View() method. Do we already do that somewhere, where I can take a look at the pattern?_

---

*[db.go, line 907 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw8kXu4iS0gVF_BPSMD:-Kw9-7-cIEzh35Uk1zyE:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/d0b7dfa2d43f5eb66a2bdee5d792618332eeee30/db.go#L907)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Shoot off the remaining entries if any.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262)*

**Comment by deepakjois** [comment]
The build is failing pending #267

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[db.go, line 900 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw8kVwA_mjI9p1gWdTz:-Kw91KpeDaPpJao9Sr1n:b-vh7wsl) ([raw file](https://github.com/dgraph-io/badger/blob/d0b7dfa2d43f5eb66a2bdee5d792618332eeee30/db.go#L900)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

Copying a comment I made elsewhere: _I could do it, but won’t the error handling will become a little bit complicated. We will have to wait for all the callbacks to finish before we return from the db.View() method. Do we already do that somewhere, where I can take a look at the pattern?_
</blockquote></details>

Just a simple sync.WaitGroup wrapped in a func should be sufficient. If there's error, stop iteration, wait for sync.waitgroup, and then return any of those errors. Should be straight forward.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262)*

**Comment by deepakjois** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[db.go, line 900 at r2](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw8kVwA_mjI9p1gWdTz:-Kw9EqRZMFcuD61xD_yT:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/d0b7dfa2d43f5eb66a2bdee5d792618332eeee30/db.go#L900)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just a simple sync.WaitGroup wrapped in a func should be sufficient. If there's error, stop iteration, wait for sync.waitgroup, and then return any of those errors. Should be straight forward.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[db.go, line 885 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9GFlvQs6hY856jo-m:-Kw9GFlvQs6hY856jo-n:b-220wz8) ([raw file](https://github.com/dgraph-io/badger/blob/5939ca553ed0aae32a98af0567843bfa901750f4/db.go#L885)):*
> ```Go
> 		var count int
> 		var wg sync.WaitGroup
> 		var errDuringWrite error
> ```

No need for this. See code below.

---

*[db.go, line 906 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9FKY_Cd-rCgR3WNQ0:-Kw9FKY_Cd-rCgR3WNQ1:b8j05qs) ([raw file](https://github.com/dgraph-io/badger/blob/5939ca553ed0aae32a98af0567843bfa901750f4/db.go#L906)):*
> ```Go
> 			if count == 1000 {
> 				wg.Add(1)
> 				err := txn.db.batchSetAsync(entries, func(err error) {
> ```

Move this function out as a nested func.

che := make(chan error, 1)
cb := func(err error) {
  defer wg.Done()
  if err == nil {
    return
  }
  select {
    case che <- err:
    default:
  }
}

and finally.

select {
  case err := <- che:
    return err
   default:
    return nil
}

---

*[db.go, line 925 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9G5m_CUSJvQweS_k6:-Kw9G5m_CUSJvQweS_k7:b9qgdz0) ([raw file](https://github.com/dgraph-io/badger/blob/5939ca553ed0aae32a98af0567843bfa901750f4/db.go#L925)):*
> ```Go
> 			err := txn.db.batchSetAsync(entries, func(err error) {
> 				if err != nil {
> 					errDuringWrite = err
> ```

This would cause race cond.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262)*

**Comment by deepakjois** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[db.go, line 906 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9FKY_Cd-rCgR3WNQ0:-Kw9IO6Yyx425do_nNMq:b-165jg7) ([raw file](https://github.com/dgraph-io/badger/blob/5939ca553ed0aae32a98af0567843bfa901750f4/db.go#L906)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move this function out as a nested func.

che := make(chan error, 1)
cb := func(err error) {
  defer wg.Done()
  if err == nil {
    return
  }
  select {
    case che <- err:
    default:
  }
}

and finally.

select {
  case err := <- che:
    return err
   default:
    return nil
}
</blockquote></details>

I don’t understand this code (looks incomplete),  but it seems like you are suggesting I use channels to pass errors. I will try that.

---

*[db.go, line 925 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9G5m_CUSJvQweS_k6:-Kw9U_VDVBZQlg77CEAA:b-8krnnz) ([raw file](https://github.com/dgraph-io/badger/blob/5939ca553ed0aae32a98af0567843bfa901750f4/db.go#L925)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This would cause race cond.
</blockquote></details>

Ya see that now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262)*

**Comment by deepakjois** [comment]
Added async writing and error handling. It’s  gotten a bit complicated, but it seems to work and tests pass.

**Comment by manishrjain** [comment]
True. It's gotten a bit more complicated than I expected, due to the error handling; but still pretty straightforward to understand. And the performance gain is great for this long-running transaction which iterates over all the keys.

---

Review status: 0 of 2 files reviewed at latest revision, 10 unresolved discussions.

---

*[db.go, line 906 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9FKY_Cd-rCgR3WNQ0:-Kw9iD90jkNjbC8w8-kq:b-e6vawz) ([raw file](https://github.com/dgraph-io/badger/blob/5939ca553ed0aae32a98af0567843bfa901750f4/db.go#L906)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

I don’t understand this code (looks incomplete),  but it seems like you are suggesting I use channels to pass errors. I will try that.
</blockquote></details>

Wasn't incomplete. The empty default were there on purpose. Anyway, looking at your code.

---

*[db.go, line 891 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9iR2fBLmq-jB2_JOb:-Kw9iR2fBLmq-jB2_JOc:b-26mm22) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L891)):*
> ```Go
> 		batchSetAsyncIfNoErr := func(entries []*entry) error {
> 			select {
> 			case err := <-errChan:
> ```

This would trigger only once before aborting. If so, add a comment.

---

*[db.go, line 901 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9ilnHjkKUD4xkrq6n:-Kw9ilnHjkKUD4xkrq6o:bc6rnsz) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L901)):*
> ```Go
> 					}
> 				})
> 				if err != nil {
> ```

Just return err. Or better still, just do:

`return txn.db.batchSetAsync(...)`

---

*[db.go, line 905 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9ikpBQczfpM_eHy6U:-Kw9ikpBQczfpM_eHy6V:b-htufx7) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L905)):*
> ```Go
> 				}
> 			}
> 			return nil
> ```

No need for this

---

*[db.go, line 925 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9itgcIywgZYsVrKyu:-Kw9itgcIywgZYsVrKyv:b-n1m14x) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L925)):*
> ```Go
> 			if count == 1000 {
> 				err := batchSetAsyncIfNoErr(entries)
> 				if err != nil {
> ```

`if err := batch...; err != nil { ... }`

---

*[db.go, line 936 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9j-h4848fHI3ZBxKx:-Kw9j-h4848fHI3ZBxKy:bj8bld6) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L936)):*
> ```Go
> 		if count > 0 {
> 			err := batchSetAsyncIfNoErr(entries)
> 			if err != nil {
> ```

same as above.

---

*[db.go, line 941 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9jDe8pJwjglJGnARV:-Kw9jDe8pJwjglJGnARW:butadrs) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L941)):*
> ```Go
> 		}
> 
> 		go func() {
> ```

Don't need this in a goroutine. Just block here.

---

*[db.go, line 943 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9jBcimoVrxuXfe_m7:-Kw9jBcimoVrxuXfe_m8:bi6xqlk) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L943)):*
> ```Go
> 		go func() {
> 			wg.Wait()
> 			close(finished)
> ```

You don't need finished.

---

*[db.go, line 949 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9jKLKpwoaUyP7xrPp:-Kw9jKLKpwoaUyP7xrPq:bs5kfvn) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L949)):*
> ```Go
> 		case err := <-errChan:
> 			return err
> 		case <-finished:
> ```

default: return nil

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262#-:-Kw9jifArdPDkMmXR2CK:b-ytwggf)*

**Comment by deepakjois** [comment]
Review status: 0 of 2 files reviewed at latest revision, 10 unresolved discussions.

---

*[db.go, line 885 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9GFlvQs6hY856jo-m:-Kw9nsmlpWYRFSJWlBw0:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/5939ca553ed0aae32a98af0567843bfa901750f4/db.go#L885)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this. See code below.
</blockquote></details>

Done.

---

*[db.go, line 906 at r4](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9FKY_Cd-rCgR3WNQ0:-Kw9onfwH_oIof47yOZO:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/5939ca553ed0aae32a98af0567843bfa901750f4/db.go#L906)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Wasn't incomplete. The empty default were there on purpose. Anyway, looking at your code.
</blockquote></details>

Done.

---

*[db.go, line 901 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9ilnHjkKUD4xkrq6n:-Kw9oTAoraNeuUdFALq7:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L901)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just return err. Or better still, just do:

`return txn.db.batchSetAsync(...)`
</blockquote></details>

Done.

---

*[db.go, line 905 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9ikpBQczfpM_eHy6U:-Kw9oTgG4fSGpcMcce_M:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L905)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this
</blockquote></details>

Done.

---

*[db.go, line 925 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9itgcIywgZYsVrKyu:-Kw9ooV-374rR2bun-MS:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L925)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`if err := batch...; err != nil { ... }`
</blockquote></details>

Done.

---

*[db.go, line 936 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9j-h4848fHI3ZBxKx:-Kw9oooAD5VmsSWf09w6:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L936)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done.

---

*[db.go, line 941 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9jDe8pJwjglJGnARV:-Kw9nDxx2Q1okgZtSm2s:b-ad2by6) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L941)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't need this in a goroutine. Just block here.
</blockquote></details>

We cannot block here. We need to be ready to receive an error. If we don’t receive an error, the callback wont be able to proceed, wg.Done() will not be called, wg.Wait() will wait forever and deadlock will happen.

---

*[db.go, line 943 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9jBcimoVrxuXfe_m7:-Kw9nSc0rNg229_C5HnT:bfs4pjb) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L943)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't need finished.
</blockquote></details>

See comment above.

Since `wg.Wait()` is blocking, we need a way to `select` between whether an error has occurred or all the async writes have finished successfully.

---

*[db.go, line 949 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9jKLKpwoaUyP7xrPp:-Kw9pOT9v4y_7O08wg9x:bq4wfr7) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L949)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

default: return nil
</blockquote></details>

See comments above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262)*

**Comment by manishrjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[db.go, line 941 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9jDe8pJwjglJGnARV:-Kw9rxbjT4YHSj3xPuNO:bw9hz7k) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L941)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

We cannot block here. We need to be ready to receive an error. If we don’t receive an error, the callback wont be able to proceed, wg.Done() will not be called, wg.Wait() will wait forever and deadlock will happen.
</blockquote></details>

When pushing to a channel, you can do this to avoid a blockage. If you do this, you won't have to do all this extra work.

`select { case ch <- err: \n default: \n }`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262)*

**Comment by deepakjois** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[db.go, line 891 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9iR2fBLmq-jB2_JOb:-Kw9x1aKQ37LXqAxEZkH:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L891)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This would trigger only once before aborting. If so, add a comment.
</blockquote></details>

Done.

---

*[db.go, line 941 at r5](https://reviewable.io:443/reviews/dgraph-io/badger/262#-Kw9jDe8pJwjglJGnARV:-Kw9wgYZnp_6xYMK6YTe:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/8ecd4272389e2b9fe36f34169d78be19e33e2a24/db.go#L941)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

When pushing to a channel, you can do this to avoid a blockage. If you do this, you won't have to do all this extra work.

`select { case ch <- err: \n default: \n }`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262)*

**Comment by manishrjain** [comment]
:lgtm: with one final comment.

---

Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[db.go, line 874 at r6](https://reviewable.io:443/reviews/dgraph-io/badger/262#-KwCfXcH3E4MwWhs5zTj:-KwCfXcH3E4MwWhs5zTk:b4hgijv) ([raw file](https://github.com/dgraph-io/badger/blob/9ba4fbdc5c2e70a70cbfb4ebad7ca010371a5c8c/db.go#L874)):*
> ```Go
> // there are no long-running read transactions running before this function is
> // called, otherwise they will not work as expected.
> func (db *DB) DeleteOlderVersions() error {
> ```

Rename to `PurgeOlderVersions()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262#-:-KwCfWrSeqV5NJ28SKcN:bxzpxzy)*

**Comment by deepakjois** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[db.go, line 874 at r6](https://reviewable.io:443/reviews/dgraph-io/badger/262#-KwCfXcH3E4MwWhs5zTj:-KwDV-sNZh7F6CTb-PI-:b-896fix) ([raw file](https://github.com/dgraph-io/badger/blob/9ba4fbdc5c2e70a70cbfb4ebad7ca010371a5c8c/db.go#L874)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Rename to `PurgeOlderVersions()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/badger/262)*

**Pull request merged**
